USE [TIFFANYBR_DIFF]
go

CREATE TABLE [dbo].[SLJCFGNF_INSERTED](
	[ltqtde] [numeric](5, 2) NOT NULL,
	[ctqtde] [numeric](5, 2) NOT NULL,
	[corigem] [numeric](5, 2) NOT NULL,
	[c1nf] [numeric](5, 2) NOT NULL,
	[c2nf] [numeric](5, 2) NOT NULL,
	[caicm] [numeric](5, 2) NOT NULL,
	[caipi] [numeric](5, 2) NOT NULL,
	[cbairr] [numeric](5, 2) NOT NULL,
	[cbicm] [numeric](5, 2) NOT NULL,
	[ccep] [numeric](5, 2) NOT NULL,
	[ccfop] [numeric](5, 2) NOT NULL,
	[ccgc] [numeric](5, 2) NOT NULL,
	[cclas1] [numeric](5, 2) NOT NULL,
	[cclas2] [numeric](5, 2) NOT NULL,
	[cclas3] [numeric](5, 2) NOT NULL,
	[cclas4] [numeric](5, 2) NOT NULL,
	[cclas5] [numeric](5, 2) NOT NULL,
	[cclas6] [numeric](5, 2) NOT NULL,
	[cclfis] [numeric](5, 2) NOT NULL,
	[ccodpro] [numeric](5, 2) NOT NULL,
	[cdescser] [numeric](5, 2) NOT NULL,
	[cdespro] [numeric](5, 2) NOT NULL,
	[cdtemi] [numeric](5, 2) NOT NULL,
	[cdtemif] [numeric](5, 2) NOT NULL,
	[cdupnum] [numeric](5, 2) NOT NULL,
	[cendcob] [numeric](5, 2) NOT NULL,
	[cender] [numeric](5, 2) NOT NULL,
	[cesp] [numeric](5, 2) NOT NULL,
	[cesta] [numeric](5, 2) NOT NULL,
	[cfat1num] [numeric](5, 2) NOT NULL,
	[cfat1val] [numeric](5, 2) NOT NULL,
	[cfat1vec] [numeric](5, 2) NOT NULL,
	[cfat2num] [numeric](5, 2) NOT NULL,
	[cfat2val] [numeric](5, 2) NOT NULL,
	[cfat2vec] [numeric](5, 2) NOT NULL,
	[cfat3num] [numeric](5, 2) NOT NULL,
	[cfat3val] [numeric](5, 2) NOT NULL,
	[cfat3vec] [numeric](5, 2) NOT NULL,
	[cfat4num] [numeric](5, 2) NOT NULL,
	[cfat4val] [numeric](5, 2) NOT NULL,
	[cfat4vec] [numeric](5, 2) NOT NULL,
	[cfat5num] [numeric](5, 2) NOT NULL,
	[cfat5val] [numeric](5, 2) NOT NULL,
	[cfat5vec] [numeric](5, 2) NOT NULL,
	[cfat6num] [numeric](5, 2) NOT NULL,
	[cfat6val] [numeric](5, 2) NOT NULL,
	[cfat6vec] [numeric](5, 2) NOT NULL,
	[cfatnum] [numeric](5, 2) NOT NULL,
	[cfatvec] [numeric](5, 2) NOT NULL,
	[cfone] [numeric](5, 2) NOT NULL,
	[cfrete] [numeric](5, 2) NOT NULL,
	[ciest] [numeric](5, 2) NOT NULL,
	[cmarca] [numeric](5, 2) NOT NULL,
	[cmuni] [numeric](5, 2) NOT NULL,
	[cnatop] [numeric](5, 2) NOT NULL,
	[cnfent] [numeric](5, 2) NOT NULL,
	[cnfsai] [numeric](5, 2) NOT NULL,
	[cnome] [numeric](5, 2) NOT NULL,
	[cnumero] [numeric](5, 2) NOT NULL,
	[cobs] [numeric](5, 2) NOT NULL,
	[cobsi] [numeric](5, 2) NOT NULL,
	[coutras] [numeric](5, 2) NOT NULL,
	[cpbru] [numeric](5, 2) NOT NULL,
	[cplaca] [numeric](5, 2) NOT NULL,
	[cplacauf] [numeric](5, 2) NOT NULL,
	[cpliq] [numeric](5, 2) NOT NULL,
	[cqtde] [numeric](5, 2) NOT NULL,
	[cqtvol] [numeric](5, 2) NOT NULL,
	[cseguro] [numeric](5, 2) NOT NULL,
	[cstrib] [numeric](5, 2) NOT NULL,
	[cticm] [numeric](5, 2) NOT NULL,
	[ctipi] [numeric](5, 2) NOT NULL,
	[ctnota] [numeric](5, 2) NOT NULL,
	[ctnotaf] [numeric](5, 2) NOT NULL,
	[ctpfrete] [numeric](5, 2) NOT NULL,
	[ctprod] [numeric](5, 2) NOT NULL,
	[ctrcgc] [numeric](5, 2) NOT NULL,
	[ctrend] [numeric](5, 2) NOT NULL,
	[ctrest] [numeric](5, 2) NOT NULL,
	[ctrie] [numeric](5, 2) NOT NULL,
	[ctrmun] [numeric](5, 2) NOT NULL,
	[ctrnome] [numeric](5, 2) NOT NULL,
	[cunid] [numeric](5, 2) NOT NULL,
	[cvalext] [numeric](5, 2) NOT NULL,
	[cvaliss] [numeric](5, 2) NOT NULL,
	[cvalser] [numeric](5, 2) NOT NULL,
	[cvipi] [numeric](5, 2) NOT NULL,
	[cvltot] [numeric](5, 2) NOT NULL,
	[cvluni] [numeric](5, 2) NOT NULL,
	[esppads] [char](10) NOT NULL,
	[fatbrutos] [numeric](6, 2) NOT NULL,
	[impclas1] [char](10) NOT NULL,
	[impclas2] [char](10) NOT NULL,
	[impclas3] [char](10) NOT NULL,
	[impclas4] [char](10) NOT NULL,
	[impclas5] [char](10) NOT NULL,
	[impclas6] [char](10) NOT NULL,
	[impclas7] [char](10) NOT NULL,
	[imppads] [char](50) NOT NULL,
	[l1nf] [numeric](5, 2) NOT NULL,
	[l2nf] [numeric](5, 2) NOT NULL,
	[lbairr] [numeric](5, 2) NOT NULL,
	[lbicm] [numeric](5, 2) NOT NULL,
	[lcep] [numeric](5, 2) NOT NULL,
	[lcfop] [numeric](5, 2) NOT NULL,
	[lcgc] [numeric](5, 2) NOT NULL,
	[lclas1] [numeric](5, 2) NOT NULL,
	[lclas2] [numeric](5, 2) NOT NULL,
	[lclas3] [numeric](5, 2) NOT NULL,
	[lclas4] [numeric](5, 2) NOT NULL,
	[lclas5] [numeric](5, 2) NOT NULL,
	[lclas6] [numeric](5, 2) NOT NULL,
	[ldescser] [numeric](5, 2) NOT NULL,
	[ldtemi] [numeric](5, 2) NOT NULL,
	[ldtemif] [numeric](5, 2) NOT NULL,
	[ldupnum] [numeric](5, 2) NOT NULL,
	[lendcob] [numeric](5, 2) NOT NULL,
	[lender] [numeric](5, 2) NOT NULL,
	[lesp] [numeric](5, 2) NOT NULL,
	[lesta] [numeric](5, 2) NOT NULL,
	[lfat1num] [numeric](5, 2) NOT NULL,
	[lfat1val] [numeric](5, 2) NOT NULL,
	[lfat1vec] [numeric](5, 2) NOT NULL,
	[lfat2num] [numeric](5, 2) NOT NULL,
	[lfat2val] [numeric](5, 2) NOT NULL,
	[lfat2vec] [numeric](5, 2) NOT NULL,
	[lfat3num] [numeric](5, 2) NOT NULL,
	[lfat3val] [numeric](5, 2) NOT NULL,
	[lfat3vec] [numeric](5, 2) NOT NULL,
	[lfat4num] [numeric](5, 2) NOT NULL,
	[lfat4val] [numeric](5, 2) NOT NULL,
	[lfat4vec] [numeric](5, 2) NOT NULL,
	[lfat5num] [numeric](5, 2) NOT NULL,
	[lfat5val] [numeric](5, 2) NOT NULL,
	[lfat5vec] [numeric](5, 2) NOT NULL,
	[lfat6num] [numeric](5, 2) NOT NULL,
	[lfat6val] [numeric](5, 2) NOT NULL,
	[lfat6vec] [numeric](5, 2) NOT NULL,
	[lfatnum] [numeric](5, 2) NOT NULL,
	[lfatvec] [numeric](5, 2) NOT NULL,
	[lfone] [numeric](5, 2) NOT NULL,
	[lfrete] [numeric](5, 2) NOT NULL,
	[liest] [numeric](5, 2) NOT NULL,
	[linprod] [numeric](5, 2) NOT NULL,
	[lmarca] [numeric](5, 2) NOT NULL,
	[lmuni] [numeric](5, 2) NOT NULL,
	[lnatop] [numeric](5, 2) NOT NULL,
	[lnfent] [numeric](5, 2) NOT NULL,
	[lnfsai] [numeric](5, 2) NOT NULL,
	[lnome] [numeric](5, 2) NOT NULL,
	[lnumero] [numeric](5, 2) NOT NULL,
	[lobs] [numeric](5, 2) NOT NULL,
	[loutras] [numeric](5, 2) NOT NULL,
	[lpbru] [numeric](5, 2) NOT NULL,
	[lplaca] [numeric](5, 2) NOT NULL,
	[lplacauf] [numeric](5, 2) NOT NULL,
	[lpliq] [numeric](5, 2) NOT NULL,
	[lqtvol] [numeric](5, 2) NOT NULL,
	[lseguro] [numeric](5, 2) NOT NULL,
	[lticm] [numeric](5, 2) NOT NULL,
	[ltipi] [numeric](5, 2) NOT NULL,
	[ltnota] [numeric](5, 2) NOT NULL,
	[ltnotaf] [numeric](5, 2) NOT NULL,
	[ltpfrete] [numeric](5, 2) NOT NULL,
	[ltprod] [numeric](5, 2) NOT NULL,
	[ltrcgc] [numeric](5, 2) NOT NULL,
	[ltrend] [numeric](5, 2) NOT NULL,
	[ltrest] [numeric](5, 2) NOT NULL,
	[ltrie] [numeric](5, 2) NOT NULL,
	[ltrmun] [numeric](5, 2) NOT NULL,
	[ltrnome] [numeric](5, 2) NOT NULL,
	[lvalext] [numeric](5, 2) NOT NULL,
	[lvaliss] [numeric](5, 2) NOT NULL,
	[lvalser] [numeric](5, 2) NOT NULL,
	[ncdser] [numeric](4, 0) NOT NULL,
	[nldser] [numeric](3, 0) NOT NULL,
	[oaden] [numeric](2, 0) NOT NULL,
	[ocor] [numeric](2, 0) NOT NULL,
	[oemb] [numeric](2, 0) NOT NULL,
	[oorig] [numeric](2, 0) NOT NULL,
	[otam] [numeric](2, 0) NOT NULL,
	[pirs] [numeric](9, 2) NOT NULL,
	[piss] [numeric](9, 2) NOT NULL,
	[tamanhos] [numeric](3, 0) NOT NULL,
	[tamcolobs] [numeric](3, 0) NOT NULL,
	[tamcolobsi] [numeric](3, 0) NOT NULL,
	[tamdesc] [numeric](3, 0) NOT NULL,
	[tamlinobs] [numeric](3, 0) NOT NULL,
	[tamlinobsi] [numeric](3, 0) NOT NULL,
	[lbaicob] [numeric](5, 2) NOT NULL,
	[cbaicob] [numeric](5, 2) NOT NULL,
	[lmuncob] [numeric](5, 2) NOT NULL,
	[cmuncob] [numeric](5, 2) NOT NULL,
	[lestcob] [numeric](5, 2) NOT NULL,
	[cestcob] [numeric](5, 2) NOT NULL,
	[lcepcob] [numeric](5, 2) NOT NULL,
	[ccepcob] [numeric](5, 2) NOT NULL,
	[cdtsaidas] [numeric](5, 2) NOT NULL,
	[ldtsaidas] [numeric](5, 2) NOT NULL,
	[letras] [numeric](1, 0) NOT NULL,
	[series] [char](5) NOT NULL,
	[cpespro] [numeric](5, 2) NOT NULL,
	[impc1] [bit] NOT NULL,
	[impc2] [bit] NOT NULL,
	[impc3] [bit] NOT NULL,
	[impc4] [bit] NOT NULL,
	[impc5] [bit] NOT NULL,
	[impc6] [bit] NOT NULL,
	[impc7] [bit] NOT NULL,
	[cposfis] [numeric](5, 2) NOT NULL,
	[csufras] [numeric](5, 2) NOT NULL,
	[lposfis] [numeric](5, 2) NOT NULL,
	[lsufras] [numeric](5, 2) NOT NULL,
	[cclas7] [numeric](5, 2) NOT NULL,
	[lclas7] [numeric](5, 2) NOT NULL,
	[ldesconto] [numeric](5, 2) NOT NULL,
	[cdesconto] [numeric](5, 2) NOT NULL,
	[cfat10num] [numeric](5, 2) NOT NULL,
	[cfat10val] [numeric](5, 2) NOT NULL,
	[cfat10vec] [numeric](5, 2) NOT NULL,
	[cfat7num] [numeric](5, 2) NOT NULL,
	[cfat7val] [numeric](5, 2) NOT NULL,
	[cfat7vec] [numeric](5, 2) NOT NULL,
	[cfat8num] [numeric](5, 2) NOT NULL,
	[cfat8val] [numeric](5, 2) NOT NULL,
	[cfat8vec] [numeric](5, 2) NOT NULL,
	[cfat9num] [numeric](5, 2) NOT NULL,
	[cfat9val] [numeric](5, 2) NOT NULL,
	[cfat9vec] [numeric](5, 2) NOT NULL,
	[ctnotar] [numeric](5, 2) NOT NULL,
	[lfat10num] [numeric](5, 2) NOT NULL,
	[lfat10val] [numeric](5, 2) NOT NULL,
	[lfat10vec] [numeric](5, 2) NOT NULL,
	[lfat7num] [numeric](5, 2) NOT NULL,
	[lfat7val] [numeric](5, 2) NOT NULL,
	[lfat7vec] [numeric](5, 2) NOT NULL,
	[lfat8num] [numeric](5, 2) NOT NULL,
	[lfat8val] [numeric](5, 2) NOT NULL,
	[lfat8vec] [numeric](5, 2) NOT NULL,
	[lfat9num] [numeric](5, 2) NOT NULL,
	[lfat9val] [numeric](5, 2) NOT NULL,
	[lfat9vec] [numeric](5, 2) NOT NULL,
	[ltnotar] [numeric](5, 2) NOT NULL,
	[marpads] [char](10) NOT NULL,
	[lcendemp] [char](12) NOT NULL,
	[lcrazemp] [char](12) NOT NULL,
	[tpcasas] [numeric](1, 0) NOT NULL,
	[tipos] [char](20) NOT NULL,
	[emps] [char](3) NOT NULL,
	[ctamfolhas] [char](80) NOT NULL,
	[cidchaves] [char](20) NOT NULL,
	[lcnfselo] [char](12) NOT NULL,
	[lcselo] [char](12) NOT NULL,
	[pesovols] [numeric](11, 2) NOT NULL
) ON [PRIMARY]

go




