USE TIFFANYBR_DIFF
GO

IF EXISTS (SELECT NAME FROM tiffanybr_DIFF.SYS.sysobjects WHERE NAME = 'TR_UPDATE_INSERT_CLIENT')

DROP TRIGGER TR_UPDATE_INSERT_CLIENT
GO

CREATE TRIGGER TR_UPDATE_INSERT_CLIENT

ON SLJCFGNF_INSERTED

FOR INSERT 

AS

delete from TIFFANYBR_DIFF..SLJCFGNF
where CIDCHAVES in (select CIDCHAVES from SLJCFGNF_INSERTED)

insert into TIFFANYBR_DIFF..SLJCFGNF
select * from SLJCFGNF_INSERTED
where cidchaves not in (select cidchaves from TIFFANYBR_DIFF..SLJCFGNF)

TRUNCATE TABLE SLJCFGNF_INSERTED

/*FIM DA PROCEDURE*/



