11)	MOSTRE ATRAVÉS DO DICIONARIO DE DADOS, 
TODOS OS TRIGGERS QUE FORAM GERADOS NESTA LISTA 
(ANTES DE EXECUTAR O COMANDO USE O COMANDO SET LONG 30000)


SET LONG 30000;

SELECT * FROM USER_SOURCE
WHERE TYPE IN ('PROCEDURE');