CREATE TABLE  SLJCLI_RR
(Tipo Char ( 1  ) ,
[CNPJ / CPF] char ( 14  ) ,
[Inscricao Est / RG] Char ( 20  ) ,
[Razão Social] char ( 40  ) ,
Identificação char ( 40  ) ,
Endereço char ( 40  ) ,
Numero char ( 6  ) ,
Complemento Char ( 20  ) ,
Cidade Char ( 20  ) ,
Estado char ( 2  ) ,
Cep Char ( 9  ) ,
DDD char ( 3  ) ,
Telefone char ( 15  ) ,
Fax char ( 15  ) ,
email char ( 50  ) ,
grupo Char ( 10  ) ,
bairro char ( 40  ) ,
obs char ( 250  ) ,
[cod capta iclis] char ( 10  ) ,
Pais_2 char ( 30  ) ,
[Data de Nascimento] char ( 10  ) ,
Segmento char ( 10  ) ,
Vendedor char ( 10  ) ,
[Data de Cadastro] char ( 10  ) ,
[Data Ult Alt Cadastro] char ( 10  ) ,
Classificação char ( 10  ) ,
[Data Última Compra] char ( 10  ) ,
[Tabela de Desconto] char ( 10  ) ,
[Inscricao Suframa] Char ( 15  ) ,
[telefone 2] Char ( 20  ) ,
Municipio Char ( 7  ) ,
Pais Char ( 5  ) ,
Situcao Char ( 3  ) ,
Inativo char ( 1  ) ,
Validade Char ( 10  ) ,
Cargo Char ( 10  ) ,
Empresa Char ( 3  ) ,
ceptrabs char ( 9 ) ,
Conjuges char ( 40 ) ,
dtcasas char ( 10 ) ,
endtrabs char ( 48 ) ,
estcivils char ( 20 ) ,
sexos char ( 1 ) ,
cpfcs char ( 11 ) ,
rgcs char ( 10),
emptrabs char ( 50 ) ,
teltrabs char ( 20 ) ,
bairtrabs char ( 40 ) ,
cidatrabs char ( 30 ) ,
estatrabs char ( 2 ) ,
profiss char ( 20  ) ,
procons char ( 20  ) ,
salarios Numeric  ( 9 ,2 ) ,
dtadmis char ( 10  ) ,
ccargos char ( 20  ) ,
ctpdocs char ( 10  ) ,
cndocs char ( 20  ) ,
numtrabs char ( 10  ) ,
compltrabs char ( 25  ) ,
cnpjtrabs char ( 20  ) ,
rendafams Numeric  ( 9 ,2 ) ,
cempcons char ( 50  ) ,
ctelcons char ( 20  ) ,
ccarcons char ( 20  ) ,
pais_ char ( 49  ) ,
maes char ( 49  ) ,
nacionals char ( 15  ) ,
sexcons char ( 1  ) ,
class char ( 20  ) ,
subclass char ( 20  ) ,
codagrups char ( 10  ) ,
mailnfes char ( 150  ) ,
iclirdzs char ( 10  ) ,
ccartoes char ( 60  ) ,
dtncons char ( 10 ) ,
Numero_ char ( 10  ) ,
ctelems char ( 1  ) ,
fidelidade char ( 1  ) ,
DtEmisDoc char ( 10  ) ,
OrgaoEmis char ( 10  ) )

