select 
	'alter database ' + name + ' set single_user with rollback immediate' + char(10) +
	'alter database ' + name + ' set offline with rollback immediate' + char(10) +
	'go' + char(10)
from sys.databases where name not in 

('master',
'model',
'msdb',
'tempdb',
'distribution',
'ReportServer',
'ReportServerTempDB',
'bd_ddd',
'rdslj03',
'marlos',
'ab_estoque',
'CPT_AUGURI',
'CPT_AUGURI2',
'bristar_erp',
'danyhome',
'jv_iguatemi',
'mirandouro_mrsljest',
'tb_contab',
'tiffanybr',
'tiffanybr_df',
'tiffanylivros',
'convex_nt',
'ilb_hyp2',
'inel_pdv_patio',
'Nature_captasql2',
'orcamento_dkza',
'rachel_erp',
'Dl_fop01',
'Dw_vivara',
'Labcip',
'Monitordba',
'Monitoria',
'Tiffanybr',
'Teste_cptweb',
'Tst_anpacit',
'tst_nuovan',
'jv_cpt',
'mb',
'dl_cpt2009',
'connexion',
'carlaamorim_erp',
'dl_livros',
'jv_cpt',
'ab_estoque',
'marlos',
'dl_estoque',
'dl_contab2009',
'AnaliseDeConsistencia',
'tst_horas',
'corsages_full')