--CRIANDO O BANCO DE DADOS ANEXANDO O .MDF
CREATE DATABASE AES
      ON (FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\AES.MDF') 
      FOR ATTACH;
      
--CRIANDO O BANCO DE DADOS + ANEXANDO O .MDF E RECRIANDO O LOG
CREATE DATABASE AES
      ON (FILENAME = 'C:\Program Files\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\DATA\AES.MDF') 
      FOR ATTACH_REBUILD_LOG;
