6)	RECRIE O PACKAGE PKG_CLIENTE E VERIFIQUE O STATUS DELE E O PACKAGE BODY PKG_CLIENTE

CREATE OR REPLACE PACKAGE PKG_CLIENTE IS

PROCEDURE PRC_INSERE_CLIENTE(P_COD_CLIENTE IN CLIENTE.COD_CLIENTE%TYPE,P_NOM_CLIENTE IN CLIENTE.NOM_CLIENTE%TYPE,
P_DES_RAZAO_SOCIAL IN CLIENTE.DES_RAZAO_SOCIAL%TYPE,P_TIP_PESSOA IN CLIENTE.TIP_PESSOA%TYPE,
P_NUM_CPF_CNPJ IN CLIENTE.NUM_CPF_CNPJ%TYPE,P_DAT_CADASTRO IN CLIENTE.DAT_CADASTRO%TYPE,
P_DAT_CANCELAMENTO IN CLIENTE.DAT_CANCELAMENTO%TYPE,P_STA_ATIVO IN CLIENTE.STA_ATIVO%TYPE);

PROCEDURE PRC_DELETA_CLIENTE (P_COD_CLIENTE IN CLIENTE.COD_CLIENTE%TYPE);

FUNCTION FUN_CONSULTA_CLIENTE (P_COD_CLIENTE IN CLIENTE.COD_CLIENTE%TYPE) RETURN CLIENTE.NOM_CLIENTE%TYPE;

END;
/

CREATE OR REPLACE PACKAGE BODY PKG_CLIENTE IS

PROCEDURE PRC_INSERE_CLIENTE(P_COD_CLIENTE IN CLIENTE.COD_CLIENTE%TYPE,P_NOM_CLIENTE IN CLIENTE.NOM_CLIENTE%TYPE,
P_DES_RAZAO_SOCIAL IN CLIENTE.DES_RAZAO_SOCIAL%TYPE,P_TIP_PESSOA IN CLIENTE.TIP_PESSOA%TYPE,
P_NUM_CPF_CNPJ IN CLIENTE.NUM_CPF_CNPJ%TYPE,P_DAT_CADASTRO IN CLIENTE.DAT_CADASTRO%TYPE,
P_DAT_CANCELAMENTO IN CLIENTE.DAT_CANCELAMENTO%TYPE,P_STA_ATIVO IN CLIENTE.STA_ATIVO%TYPE) IS

BEGIN

INSERT INTO CLIENTE VALUES(P_COD_CLIENTE,P_NOM_CLIENTE,P_DES_RAZAO_SOCIAL,P_TIP_PESSOA,P_NUM_CPF_CNPJ,P_DAT_CADASTRO,
P_DAT_CANCELAMENTO,P_STA_ATIVO);   

END;

PROCEDURE PRC_DELETA_CLIENTE(P_COD_CLIENTE IN CLIENTE.COD_CLIENTE%TYPE)IS

BEGIN

DELETE CLIENTE
WHERE COD_CLIENTE=P_COD_CLIENTE;

END;

FUNCTION FUN_CONSULTA_CLIENTE (P_COD_CLIENTE IN CLIENTE.COD_CLIENTE%TYPE) RETURN CLIENTE.NOM_CLIENTE%TYPE IS

X CLIENTE.NOM_CLIENTE%TYPE;

BEGIN

SELECT NOM_CLIENTE INTO X FROM CLIENTE WHERE
COD_CLIENTE=P_COD_CLIENTE;

RETURN X;

END;

END PKG_CLIENTE;
/

SELECT OBJECT_NAME
FROM ALL_OBJECTS
WHERE OBJECT_NAME = 'PKG_CLIENTE';