INSERT INTO ROSARIO_erp..SLJCLI_RR (Tipo,	[CNPJ / CPF],	[Inscricao Est / RG],	[Razão Social],	Identificação,	Endereço,	Numero,	Complemento,	Cidade,	Estado,	Cep,	DDD,	Telefone,	Fax, 	email,	grupo,	bairro,	obs,	[cod capta iclis],	Pais_2,	[Data de Nascimento],	Segmento,	Vendedor,	[Data de Cadastro],	[Data Ult Alt Cadastro],	Classificação,	[Data Última Compra],	[Tabela de Desconto],	[Inscricao Suframa] ,	[telefone 2],	Municipio,	Pais,	Situcao,	Inativo,	Validade,	Cargo,	Empresa,	ceptrabs ,	Conjuges ,	dtcasas ,	endtrabs,	estcivils ,	sexos,	cpfcs,	rgcs,	emptrabs,	teltrabs,	bairtrabs,	cidatrabs ,	estatrabs,	profiss,	procons,	salarios,	dtadmis,	ccargos,	ctpdocs,	cndocs,	numtrabs,	compltrabs,	cnpjtrabs,	rendafams,	cempcons,	ctelcons,	ccarcons,	pais_,	maes,	nacionals,	sexcons,	class,	subclass,	codagrups,	mailnfes,	iclirdzs,	ccartoes,	dtncons,	Numero_,	ctelems,	fidelidade,	DtEmisDoc,	OrgaoEmis)
SELECT
'6' as Tipo ,
--CASE WHEN tt_cli.tipdoc	= 'RG' THEN '1' ELSE '2' END AS	tpclis	,
isnull(SUBSTRING(tt_cli.numdoc, 1, 14), '') 	AS	cpfs,
--isnull(SUBSTRING(tt_cli.numdoc, 1, 14), '') AS	rgs	,
'' AS	rgs	,
isnull(SUBSTRING(tt_cli.nomcli, 1, 40), '')	AS	razaos	,
'' AS IDENTIFICACAO,
isnull(SUBSTRING(tt_end_TMP.endere, 1, 40), '')	AS	endes	,
'' as numero,
isnull(SUBSTRING(tt_end_TMP.comple,1, 20), '')	AS	compls	,
isnull(SUBSTRING(tt_end_TMP.nomcid, 1, 20), '')	AS	cidas	,
isnull(tt_end_TMP.sigest, '')	AS	estas	,
ISNULL(substring(tt_end_TMP.codcep + tt_end_TMP.codlog, 1,5) + '-' + substring(tt_end_TMP.codcep + tt_end_TMP.codlog, 6,3), '') AS CEP,
--isnull(tt_end_TMP.codcep + tt_end_TMP.codlog, '') 	AS	ceps	,
isnull(tt_end_TMP.codddd, '')	AS	ddds	,
isnull(tt_end_TMP.numfon, '')	AS	tel1s	,
'' as fax,
isnull(tw_cli_TMP.e_mail, '')	AS	emails	,
isnull('CLIVAR', '') AS	grupos	,
isnull(tt_end_TMP.bairro, '')	AS	bairs	,
isnull(SUBSTRING(TW_CLI_TMP.obsout, 1, 250), '')	AS	obs	,
'' as iclis,
'' pais_2,
isnull(TW_CLI_TMP.datnas, '')	AS	nascs	,
'' as segmento,
'' as vendedor,
'' as [Data de Cadastro],
'' as [Data Ult Alt Cadastro],
'' as Classificacao,
'' as [Data Última Compra],
'' as [Tabela de Desconto],
'' as [Inscricao Suframa],
'' as [telefone 2] ,
isnull(tt_end_TMP.codcid, '')	AS	nmuncips	,
'' as pais,
'' as situacao,
'0' as inativo,
'' as validade,
'' as cargo,
'' as empresa,
'' as ceptrabs,
 isnull(TW_CLI_TMP.conjug, '')	AS	conjuges	,
 '' as dtcasas,
 '' as endtrabs,
 '' as estcivils,
 '' as sexos,
 '' as cpfcs,
 '' as rgcs,
 '' as emptrabs,
 '' as teltrabs,
 '' as	bairtrabs,
'' as	cidatrabs ,
'' as	estatrabs,
'' as	profiss,
'' as	procons,
'0' as	salarios,
'' as	dtadmis,
'' as	ccargos,
'' as	ctpdocs,
'' as	cndocs,
'' as	numtrabs,
'' as	compltrabs,
'' as	cnpjtrabs,
'0' as	rendafams,
'' as	cempcons,
'' as	ctelcons,
'' as	ccarcons,
'' as	pais_,
'' as	maes,
'' as	nacionals,
'' as	sexcons,
'' as	class,
'' as	subclass,
'' as	codagrups,
'' as	mailnfes,
'' as	iclirdzs,
'' as	ccartoes,
'' as	dtncons,
'' as	Numero_,
'' as	ctelems,
'' as	fidelidade,
'' as	DtEmisDoc,
isnull(TW_CLI_TMP.id_org, '') as id_org
FROM TT_CLI
JOIN TT_END_TMP ON TT_CLI.CODCLI = TT_END_TMP.CODCLI AND TT_CLI.FILCLI = TT_END_TMP.FILCLI 
LEFT JOIN TW_CLI_TMP ON TT_CLI.NUMDOC = TW_CLI_TMP.NUMDOC  AND TT_CLI.FILCLI = TW_CLI_TMP.FILCLI 


--isnull('FUNCIONARI', '') AS	grupovens	,

--isnull(tt_cli.nomcli, '')	AS	rclis	,



--isnull(tt_cli.insest, '')	AS	IE


--TRUNCATE TABLE ROSARIO_erp..SLJCLI_RR

