select * from cctbpres
order by dt_pagamento

insert into cctbpres (dt_pagamento ,nm_semana_pagto)


insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-01-01'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-01-02'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-01-08'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-01-09'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-01-15'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-01-16'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-01-22'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-01-23'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-01-29'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-01-30'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-02-05'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-02-06'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-02-12'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-02-13'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-02-19'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-02-20'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-02-26'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-02-27'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-03-05'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-03-06'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-03-12'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-03-13'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-03-19'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-03-20'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-03-26'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-03-27'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-04-02'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-04-03'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-04-09'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-04-10'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-04-16'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-04-17'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-04-23'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-04-24'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-04-30'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-05-01'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-05-07'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-05-08'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-05-14'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-05-15'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-05-21'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-05-22'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-05-28'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-05-29'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-06-04'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-06-05'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-06-11'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-06-12'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-06-18'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-06-19'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-06-25'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-06-26'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-07-02'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-07-03'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-07-09'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-07-10'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-07-16'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-07-17'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-07-23'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-07-24'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-07-30'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-07-31'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-08-06'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-08-07'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-08-13'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-08-14'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-08-20'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-08-21'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-08-27'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-08-28'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-09-03'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-09-04'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-09-10'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-09-11'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-09-17'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-09-18'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-09-24'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-09-25'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-10-01'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-10-02'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-10-08'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-10-09'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-10-15'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-10-16'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-10-22'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-10-23'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-10-29'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-10-30'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-11-05'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-11-06'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-11-12'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-11-13'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-11-19'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-11-20'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-11-26'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-11-27'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-12-03'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-12-04'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-12-10'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-12-11'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-12-17'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-12-18'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-12-24'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-12-25'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-12-31'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-01-01'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-01-07'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-01-08'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-01-14'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-01-15'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-01-21'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-01-22'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-01-28'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-01-29'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-02-04'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-02-05'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-02-11'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-02-12'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-02-18'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-02-19'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-02-25'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-02-26'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-03-03'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-03-04'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-03-10'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-03-11'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-03-17'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-03-18'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-03-24'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-03-25'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-03-31'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-04-01'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-04-07'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-04-08'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-04-14'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-04-15'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-04-21'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-04-22'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-04-28'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-04-29'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-05-05'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-05-06'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-05-12'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-05-13'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-05-19'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-05-20'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-05-26'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-05-27'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-06-02'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-06-03'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-06-09'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-06-10'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-06-16'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-06-17'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-06-23'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-06-24'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-06-30'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-07-01'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-07-07'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-07-08'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-07-14'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-07-15'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-07-21'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-07-22'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-07-28'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-07-29'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-08-04'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-08-05'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-08-11'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-08-12'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-08-18'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-08-19'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-08-25'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-08-26'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-09-01'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-09-02'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-09-08'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-09-09'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-09-15'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-09-16'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-09-22'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-09-23'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-09-29'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-09-30'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-10-06'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-10-07'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-10-13'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-10-14'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-10-20'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-10-21'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-10-27'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-10-28'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-11-03'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-11-04'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-11-10'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-11-11'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-11-17'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-11-18'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-11-24'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-11-25'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-12-01'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-12-02'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-12-08'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-12-09'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-12-15'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-12-16'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-12-22'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-12-23'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-12-29'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-12-30'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-01-05'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-01-06'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-01-12'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-01-13'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-01-19'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-01-20'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-01-26'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-01-27'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-02-02'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-02-03'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-02-09'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-02-10'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-02-16'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-02-17'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-02-23'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-02-24'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-03-02'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-03-03'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-03-09'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-03-10'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-03-16'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-03-17'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-03-23'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-03-24'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-03-30'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-03-31'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-04-06'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-04-07'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-04-13'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-04-14'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-04-20'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-04-21'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-04-27'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-04-28'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-05-04'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-05-05'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-05-11'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-05-12'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-05-18'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-05-19'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-05-25'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-05-26'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-06-01'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-06-02'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-06-08'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-06-09'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-06-15'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-06-16'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-06-22'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-06-23'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-06-29'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-06-30'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-07-06'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-07-07'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-07-13'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-07-14'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-07-20'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-07-21'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-07-27'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-07-28'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-08-03'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-08-04'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-08-10'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-08-11'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-08-17'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-08-18'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-08-24'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-08-25'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-08-31'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-09-01'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-09-07'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-09-08'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-09-14'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-09-15'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-09-21'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-09-22'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-09-28'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-09-29'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-10-05'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-10-06'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-10-12'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-10-13'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-10-19'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-10-20'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-10-26'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-10-27'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-11-02'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-11-03'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-11-09'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-11-10'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-11-16'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-11-17'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-11-23'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-11-24'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-11-30'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-12-01'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-12-07'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-12-08'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-12-14'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-12-15'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-12-21'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-12-22'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-12-28'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-12-29'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-01-04'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-01-05'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-01-11'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-01-12'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-01-18'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-01-19'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-01-25'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-01-26'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-02-01'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-02-02'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-02-08'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-02-09'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-02-15'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-02-16'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-02-22'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-02-23'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-03-01'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-03-02'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-03-08'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-03-09'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-03-15'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-03-16'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-03-22'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-03-23'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-03-29'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-03-30'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-04-05'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-04-06'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-04-12'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-04-13'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-04-19'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-04-20'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-04-26'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-04-27'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-05-03'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-05-04'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-05-10'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-05-11'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-05-17'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-05-18'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-05-24'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-05-25'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-05-31'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-06-01'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-06-07'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-06-08'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-06-14'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-06-15'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-06-21'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-06-22'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-06-28'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-06-29'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-07-05'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-07-06'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-07-12'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-07-13'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-07-19'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-07-20'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-07-26'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-07-27'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-08-02'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-08-03'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-08-09'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-08-10'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-08-16'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-08-17'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-08-23'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-08-24'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-08-30'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-08-31'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-09-06'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-09-07'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-09-13'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-09-14'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-09-20'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-09-21'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-09-27'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-09-28'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-10-04'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-10-05'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-10-11'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-10-12'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-10-18'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-10-19'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-10-25'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-10-26'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-11-01'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-11-02'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-11-08'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-11-09'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-11-15'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-11-16'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-11-22'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-11-23'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-11-29'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-11-30'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-12-06'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-12-07'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-12-13'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-12-14'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-12-20'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-12-21'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-12-27'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-12-28'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-01-03'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-01-04'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-01-10'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-01-11'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-01-17'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-01-18'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-01-24'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-01-25'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-01-31'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-02-01'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-02-07'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-02-08'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-02-14'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-02-15'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-02-21'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-02-22'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-02-28'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-03-01'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-03-07'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-03-08'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-03-14'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-03-15'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-03-21'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-03-22'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-03-28'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-03-29'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-04-04'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-04-05'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-04-11'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-04-12'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-04-18'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-04-19'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-04-25'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-04-26'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-05-02'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-05-03'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-05-09'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-05-10'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-05-16'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-05-17'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-05-23'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-05-24'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-05-30'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-05-31'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-06-06'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-06-07'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-06-13'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-06-14'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-06-20'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-06-21'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-06-27'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-06-28'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-07-04'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-07-05'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-07-11'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-07-12'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-07-18'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-07-19'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-07-25'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-07-26'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-08-01'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-08-02'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-08-08'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-08-09'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-08-15'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-08-16'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-08-22'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-08-23'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-08-29'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-08-30'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-09-05'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-09-06'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-09-12'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-09-13'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-09-19'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-09-20'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-09-26'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-09-27'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-10-03'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-10-04'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-10-10'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-10-11'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-10-17'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-10-18'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-10-24'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-10-25'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-10-31'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-11-01'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-11-07'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-11-08'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-11-14'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-11-15'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-11-21'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-11-22'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-11-28'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-11-29'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-12-05'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-12-06'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-12-12'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-12-13'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-12-19'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-12-20'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-12-26'	,'SABADO ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-12-27'	,'DOMINGO')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-03-07'	,'SEGUNDA')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-03-08'	,'TERÇA  ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-04-21'	,'QUINTA ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-04-22'	,'SEXTA  ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-06-23'	,'QUINTA ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-09-07'	,'QUARTA ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-10-12'	,'QUARTA ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-11-02'	,'QUARTA ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2011-11-15'	,'TERÇA  ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-02-20'	,'SEGUNDA')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-02-21'	,'TERÇA  ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-04-06'	,'SEXTA  ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-05-01'	,'TERÇA  ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-06-07'	,'QUINTA ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-09-07'	,'SEXTA  ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-10-12'	,'SEXTA  ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-11-02'	,'SEXTA  ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-11-15'	,'QUINTA ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2012-12-25'	,'TERÇA  ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-01-01'	,'TERÇA  ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-02-12'	,'TERÇA  ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-02-13'	,'QUARTA ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-03-29'	,'SEXTA  ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-05-01'	,'QUARTA ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-05-30'	,'QUINTA ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-11-15'	,'SEXTA  ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2013-12-25'	,'QUARTA ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-01-01'	,'QUARTA ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-03-04'	,'TERÇA  ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-03-05'	,'QUARTA ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-04-18'	,'SEXTA  ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-04-21'	,'SEGUNDA')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-05-01'	,'QUINTA ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-06-19'	,'QUINTA ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2014-12-25'	,'QUINTA ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-01-01'	,'QUINTA ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-02-17'	,'TERÇA  ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-02-18'	,'QUARTA ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-03-03'	,'SEXTA  ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-04-21'	,'TERÇA  ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-05-01'	,'SEXTA  ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-06-04'	,'QUINTA ')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-09-07'	,'SEGUNDA')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-10-12'	,'SEGUNDA')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-11-02'	,'SEGUNDA')
insert into cctbpres (dt_pagamento ,nm_semana_pagto)	values('2015-12-25'	,'SEXTA  ')

                                                                                                                                                                                                   