--INSERT TABELAS EXCEDENTES
SELECT +' SELECT * INTO DB_TB_EXCEDENTES..' + NAME + ' FROM DB_VIVARA.DBO.' + NAME 
FROM DB_VIVARA.SYS.sysobjects
	WHERE TYPE = 'U' AND TYPE <> 'S'
		AND NAME  COLLATE SQL_Latin1_General_CP1_CI_AS NOT IN (SELECT NOME FROM DB_TB_VARQUIVO.DBO.VARQUIVO)



--CONFERE TABELAS INSERIDAS
/*
SELECT NAME FROM DB_TB_EXCEDENTES.SYS.sysobjects
WHERE TYPE = 'U' AND TYPE <> 'S'
*/



/****************************************************************************************************************************************************/




--DROP TABELAS EXCEDENTES
SELECT +' DROP TABLE DB_VIVARA.DBO.' + NAME 
FROM DB_VIVARA.SYS.sysobjects
	WHERE TYPE = 'U' AND TYPE <> 'S'
		AND NAME  COLLATE SQL_Latin1_General_CP1_CI_AS NOT IN (SELECT NOME FROM DB_TB_VARQUIVO.DBO.VARQUIVO)





--CONFERE SE EXISTE ALGUMA TABELA EXCEDENTE
/*
SELECT NAME 
FROM DB_VIVARA.SYS.sysobjects
	WHERE TYPE = 'U' AND TYPE <> 'S'
		AND NAME  COLLATE SQL_Latin1_General_CP1_CI_AS NOT IN (SELECT NOME FROM DB_TB_VARQUIVO.DBO.VARQUIVO)
*/