USE [andre_finasa]
GO
/****** Object:  StoredProcedure [dbo].[SP_ATUALIZANUMEROS]    Script Date: 07/09/2012 10:19:53 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [dbo].[SP_ATUALIZANUMEROS]
AS
BEGIN
IF  NOT EXISTS (SELECT * FROM sys.objects
			WHERE object_id = OBJECT_ID(N'[dbo].LOG_ANDRE')
			AND type in (N'U'))
BEGIN
 CREATE TABLE LOG_ANDRE(
 DATA DATETIME,
 HISTORICO VARCHAR (255)
 )
 END
 END
-- DECLARA AS VARIAVEIS QUE SÃO USADAS
DECLARE @CONTADOR INT
DECLARE @PARA INT
TRUNCATE TABLE LOG_ANDRE



-- COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE COMECE COM: 6,7,8 E 9
	
			INSERT INTO LOG_ANDRE VALUES (GETDATE(),'50')
			UPDATE tbfone
			SET    nr_telefone = CAST('9' AS CHAR(1))+ CAST(nr_telefone AS CHAR(8))
			WHERE   nr_ddd = '11'
					AND LEN(nr_telefone) = 8
					AND SUBSTRING(nr_telefone, 1, 1) IN ( '6', '7', '8', '9' )
		IF @@ERROR = 0
			BEGIN	
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'60')
	          
			END
    
		ELSE
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'70')
	
			END
		INSERT INTO LOG_ANDRE VALUES (GETDATE(),'80')		  



--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5300 E 5324
		
			INSERT INTO LOG_ANDRE VALUES (GETDATE(),'90')

			UPDATE tbfone
			SET NR_TELEFONE = 	CAST('9' AS CHAR(1))+ CAST(nr_telefone AS CHAR(8))
			WHERE   nr_ddd = '11'
					AND LEN(nr_telefone) = 8
					AND CAST((SUBSTRING(nr_telefone, 1, 4))AS INT) BETWEEN 5300 AND 5324
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'100')
		
		
			END
		
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'110')
	
		
			END			    
        
        INSERT INTO LOG_ANDRE VALUES (GETDATE(),'120')

            

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5472 E 5474


			INSERT INTO LOG_ANDRE VALUES (GETDATE(),'130')

			UPDATE tbfone
			SET NR_TELEFONE = 	CAST('9' AS CHAR(1))+ CAST(nr_telefone AS CHAR(8))
			WHERE nr_ddd = '11'  
				  AND LEN(nr_telefone) = 8
				  AND CAST((SUBSTRING(nr_telefone, 1, 4))AS INT) BETWEEN 5472 AND 5474
        
		IF @@ERROR = 0
			BEGIN 

			INSERT INTO LOG_ANDRE VALUES (GETDATE(),'140')
			END	
		
		ELSE 
			BEGIN
		
		INSERT INTO LOG_ANDRE VALUES (GETDATE(),'150')
		
	
		
			END			    
        INSERT INTO LOG_ANDRE VALUES (GETDATE(),'160')


INSERT INTO LOG_ANDRE VALUES (GETDATE(),'170')


--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5769 E 5786

		BEGIN TRAN
			UPDATE tbfone
			SET NR_TELEFONE = 	CAST('9' AS CHAR(1))+ CAST(nr_telefone AS CHAR(8))
			WHERE nr_ddd = '11' 
			AND LEN(nr_telefone) = 8
            AND CAST((SUBSTRING(nr_telefone, 1, 4))AS INT) BETWEEN 5769 AND 5786
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'180')
		COMMIT
			
			END
		
		ELSE 
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'190')
			
		ROLLBACK
		
			END			    

        INSERT INTO LOG_ANDRE VALUES (GETDATE(),'200')


INSERT INTO LOG_ANDRE VALUES (GETDATE(),'210')



--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5200 E 5211

		
			UPDATE tbfone
			SET NR_TELEFONE = 	CAST('9' AS CHAR(1))+ CAST(nr_telefone AS CHAR(8))
			WHERE nr_ddd = '11' 
			AND LEN(nr_telefone) = 8
            AND CAST((SUBSTRING(nr_telefone, 1, 4))AS INT) BETWEEN 5200 AND 5211
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'220')
		
		
			END
		
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'230')
	
		
			END			    

INSERT INTO LOG_ANDRE VALUES (GETDATE(),'240')

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'250')


--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5214 E 5251

	
			UPDATE tbfone
			SET NR_TELEFONE = 	CAST('9' AS CHAR(1))+ CAST(nr_telefone AS CHAR(8))
			WHERE nr_ddd = '11' 
			      AND LEN(nr_telefone) = 8
                  AND CAST((SUBSTRING(nr_telefone, 1, 4))AS INT) BETWEEN 5214 AND 5251
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'260')
	
		
			END
		
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'270')
		
		
			END			    


INSERT INTO LOG_ANDRE VALUES (GETDATE(),'280')



--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5268 E 5299

		INSERT INTO LOG_ANDRE VALUES (GETDATE(),'290')
	
			UPDATE tbfone
			SET NR_TELEFONE = 	CAST('9' AS CHAR(1))+ CAST(nr_telefone AS CHAR(8))
			WHERE nr_ddd = '11' 
			      AND LEN(nr_telefone) = 8
                  AND CAST((SUBSTRING(nr_telefone, 1, 4))AS INT) BETWEEN 5268 AND 5299
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'300')

		
			END
		
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'310')
		
		
			END			    
        
        INSERT INTO LOG_ANDRE VALUES (GETDATE(),'320')


--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5329 E 5351

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'330')
		
			UPDATE tbfone
			SET NR_TELEFONE = 	CAST('9' AS CHAR(1))+ CAST(nr_telefone AS CHAR(8))
			WHERE nr_ddd = '11' 
			      AND LEN(nr_telefone) = 8
                  AND CAST((SUBSTRING(nr_telefone, 1, 4))AS INT) BETWEEN 5329 AND 5351
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'340')

		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'350')
		
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'360')				    
			END

    



--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5420 E 5471

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'370')
		
		UPDATE tbfone
		SET NR_TELEFONE = 	CAST('9' AS CHAR(1))+ CAST(nr_telefone AS CHAR(8))
		WHERE nr_ddd = '11' 
		      AND LEN(nr_telefone) = 8
              AND CAST((SUBSTRING(nr_telefone, 1, 4))AS INT) BETWEEN 5420 AND 5471
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'380')

		
			END
		
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'390')
	
		
			END			    
       
        INSERT INTO LOG_ANDRE VALUES (GETDATE(),'400') 

    

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5475 AND 5499
	
	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'410 ')
		
		UPDATE tbfone
		SET NR_TELEFONE = 	CAST('9' AS CHAR(1))+ CAST(nr_telefone AS CHAR(8))
		WHERE nr_ddd = '11'
		      AND LEN(nr_telefone) = 8
              AND CAST((SUBSTRING(nr_telefone, 1, 4))AS INT) BETWEEN 5475 AND 5499
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'420')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'430')
		
			END			    
    
    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'440')    
    

    

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5787 AND 5799

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'450')
		
		UPDATE tbfone
		SET NR_TELEFONE = 	CAST('9' AS CHAR(1))+ CAST(nr_telefone AS CHAR(8))
		WHERE nr_ddd = '11'
			  AND LEN(nr_telefone) = 8
              AND CAST((SUBSTRING(nr_telefone, 1, 4))AS INT) BETWEEN 5787 AND 5799
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'460')
				
			END
		
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'470')
		
		
			END			    
        INSERT INTO LOG_ANDRE VALUES (GETDATE(),'480')


--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5252 AND 5267

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'490')
		
		UPDATE tbfone
		SET NR_TELEFONE = 	CAST('9' AS CHAR(1))+ CAST(nr_telefone AS CHAR(8))
		WHERE  nr_ddd = '11' 
		       AND LEN(nr_telefone) = 8
               AND CAST((SUBSTRING(nr_telefone, 1, 4))AS INT) BETWEEN 5252 AND 5267
		IF @@ERROR = 0
			BEGIN 
			INSERT INTO LOG_ANDRE VALUES (GETDATE(),'500')
		
		
			END
		
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'510')
				
			END			    
        
        INSERT INTO LOG_ANDRE VALUES (GETDATE(),'520')



--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5400 AND 5419

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'530')
		
		UPDATE tbfone
		SET NR_TELEFONE = 	CAST('9' AS CHAR(1))+ CAST(nr_telefone AS CHAR(8))
		WHERE nr_ddd = '11' 
		      AND LEN(nr_telefone) = 8
              AND CAST((SUBSTRING(nr_telefone, 1, 4))AS INT) BETWEEN 5400 AND 5419
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'540')
		
		
			END 
		
		ELSE 
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'550')
		
			END			    
       
			INSERT INTO LOG_ANDRE VALUES (GETDATE(),'560') 

    

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5700 AND 5768

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'570')
		
		UPDATE tbfone
		SET NR_TELEFONE = 	CAST('9' AS CHAR(1))+ CAST(nr_telefone AS CHAR(8))
		WHERE nr_ddd = '11' 
			  AND LEN(nr_telefone) = 8
              AND CAST((SUBSTRING(nr_telefone, 1, 4))AS INT) BETWEEN 5700 AND 5768
		IF @@ERROR = 0
			BEGIN 
			INSERT INTO LOG_ANDRE VALUES (GETDATE(),'580')
		
			END
		
		ELSE 
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'590')
		
		
			END			    
        
			INSERT INTO LOG_ANDRE VALUES (GETDATE(),'600')
           
    
-- FAZ UM UPDATE NA BASE PARA TODOS OS TELEFONES QUE TIVEREM MENOS DE 8 DIGITOS FIQUEM COMO 'RUIM'    
UPDATE TBFONE 
SET CD_STATUS = 2               
WHERE LEN(NR_TELEFONE) < 8 

-------------------------------------------------------------------------------------------------------


-- UPDATE PARA ADCIONAR O DIGITO NOVE NOS TELEFONES QUE COMECAREM COM 6,7,8 E 9 
INSERT INTO LOG_ANDRE VALUES (GETDATE(),'625')


--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE COMECAM COM 6,7,8 E 9

    
	UPDATE cadcontr
	SET    fonrec1 = CAST('9' AS CHAR(1))+ CAST(fonrec1 AS CHAR(8))
	WHERE  dddrec1 = 11
		   AND LEN(fonrec1) = 8
           AND SUBSTRING(fonrec1, 1, 1) IN ( '6', '7', '8', '9' )
    IF @@ERROR = 0
		BEGIN	
			INSERT INTO LOG_ANDRE VALUES (GETDATE(),'640')
	
		END
    
    ELSE
		BEGIN 
			INSERT INTO LOG_ANDRE VALUES (GETDATE(),'650')
	
		END
	
	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'660')		  
 

-- A PARTIR DAQUI É FEITO O UPDATE DOS TELEFONES QUE COMECAM COM 5....
INSERT INTO LOG_ANDRE VALUES (GETDATE(),'670')


--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5300 AND 5324

		
		UPDATE cadcontr
		SET fonrec1 = 	CAST('9' AS CHAR(1))+ CAST(fonrec1 AS CHAR(8))
		WHERE dddrec1 = 11
			  AND LEN(fonrec1) = 8
              AND CAST((SUBSTRING(fonrec1, 1, 4))AS INT) BETWEEN 5300 AND 5324
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'680')
				
			END
		
		ELSE
		
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'690')
				
			END			    

    
    
    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'700')
    
	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'710')    

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5472 AND 5474

		
		UPDATE cadcontr
		SET fonrec1 = 	CAST('9' AS CHAR(1))+ CAST(fonrec1 AS CHAR(8))
		WHERE dddrec1 = 11 
			  AND LEN(fonrec1) = 8
              AND CAST((SUBSTRING(fonrec1, 1, 4))AS INT) BETWEEN 5472 AND 5474
        
		IF @@ERROR = 0
			BEGIN 
		
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'720')
			END	
		ELSE 
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'730')
		 
		
			END			    
 
    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'740')
    
    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'750')


--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5779 AND 5786

		
		UPDATE cadcontr
		SET fonrec1 = 	CAST('9' AS CHAR(1))+ CAST(fonrec1 AS CHAR(8))
		WHERE dddrec1 = 11
			  AND  LEN(fonrec1) = 8
              AND CAST((SUBSTRING(fonrec1, 1, 4))AS INT) BETWEEN 5769 AND 5786
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'760')
			END
		ELSE 
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'770')
			
				
			END			    

INSERT INTO LOG_ANDRE VALUES (GETDATE(),'780')

INSERT INTO LOG_ANDRE VALUES (GETDATE(),'790')

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5200 AND 5211

		UPDATE cadcontr
		SET fonrec1 = 	CAST('9' AS CHAR(1))+ CAST(fonrec1 AS CHAR(8))
		WHERE dddrec1 = 11
			  AND LEN(fonrec1) = 8
              AND CAST((SUBSTRING(fonrec1, 1, 4))AS INT) BETWEEN 5200 AND 5211
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'800')
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'810')
			END			    


INSERT INTO LOG_ANDRE VALUES (GETDATE(),'820')

INSERT INTO LOG_ANDRE VALUES (GETDATE(),'830')

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5214 AND 5251

		
		UPDATE cadcontr
		SET fonrec1 = 	CAST('9' AS CHAR(1))+ CAST(fonrec1 AS CHAR(8))
		WHERE dddrec1 = 11
			  AND LEN(fonrec1) = 8
			  AND CAST((SUBSTRING(fonrec1, 1, 4))AS INT) BETWEEN 5214 AND 5251
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'840')
		
			END
		
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'850')
		
		
			END			    


    
INSERT INTO LOG_ANDRE VALUES (GETDATE(),'860')

INSERT INTO LOG_ANDRE VALUES (GETDATE(),'870')    

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5268 AND 5299

		
		UPDATE cadcontr
		SET fonrec1 = 	CAST('9' AS CHAR(1))+ CAST(fonrec1 AS CHAR(8))
		WHERE dddrec1 = 11
			  AND LEN(fonrec1) = 8
              AND CAST((SUBSTRING(fonrec1, 1, 4))AS INT) BETWEEN 5268 AND 5299
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'880')
				
			END
		
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'890')
		
			END			    
    

    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'900')    

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'910')

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5329 AND 5351

		
		UPDATE cadcontr
		SET fonrec1 = 	CAST('9' AS CHAR(1))+ CAST(fonrec1 AS CHAR(8))
		WHERE dddrec1 = 11
			  AND LEN(fonrec1) = 8
              AND CAST((SUBSTRING(fonrec1, 1, 4))AS INT) BETWEEN 5329 AND 5351
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'920')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'930')
		
			END
    
	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'940')				        

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'950')

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5420 AND 5471

		
		UPDATE cadcontr
		SET fonrec1 = 	CAST('9' AS CHAR(1))+ CAST(fonrec1 AS CHAR(8))
		WHERE dddrec1 = 11 
		      AND   LEN(fonrec1) = 8
              AND CAST((SUBSTRING(fonrec1, 1, 4))AS INT) BETWEEN 5420 AND 5471
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'960')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'970')
		
			END			    


    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'980')     

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'990')    

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5475 AND 5499

		
		UPDATE cadcontr
		SET fonrec1 = 	CAST('9' AS CHAR(1))+ CAST(fonrec1 AS CHAR(8))
		WHERE dddrec1 = 11
		      AND LEN(fonrec1) = 8
              AND CAST((SUBSTRING(fonrec1, 1, 4))AS INT) BETWEEN 5475 AND 5499
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'1000')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'1010')
		
			END			    

    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'1020')    

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'1030')        

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5787 AND 5799

		
		UPDATE cadcontr
		SET fonrec1 = 	CAST('9' AS CHAR(1))+ CAST(fonrec1 AS CHAR(8))
		WHERE  dddrec1 = 11
			   AND LEN(fonrec1) = 8
               AND CAST((SUBSTRING(fonrec1, 1, 4))AS INT) BETWEEN 5787 AND 5799
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'1040')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'1050')
		
			END			    

    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'1060')

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'1070')    

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5252 AND 5267

		
		UPDATE cadcontr
		SET fonrec1 = 	CAST('9' AS CHAR(1))+ CAST(fonrec1 AS CHAR(8))
		WHERE  dddrec1 = 11
			   AND LEN(fonrec1) = 8
               AND CAST((SUBSTRING(fonrec1, 1, 4))AS INT) BETWEEN 5252 AND 5267
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'1080')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'1090')
		
			END			    

    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'1100')    

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'1110')    

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5400 AND 5419

		
		UPDATE cadcontr
		SET fonrec1 = 	CAST('9' AS CHAR(1))+ CAST(fonrec1 AS CHAR(8))
		WHERE LEN(fonrec1) = 8
			  AND dddrec1 = 11
              AND CAST((SUBSTRING(fonrec1, 1, 4))AS INT) BETWEEN 5400 AND 5419
		IF @@ERROR = 0
			BEGIN 
			INSERT INTO LOG_ANDRE VALUES (GETDATE(),'1120')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'1130')
				
			END			    

    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'1140')     
    
    

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5700 AND 5768

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'1150')
		
		UPDATE cadcontr
		SET fonrec1 = 	CAST('9' AS CHAR(1))+ CAST(fonrec1 AS CHAR(8))
		WHERE dddrec1 = 11
			  AND  LEN(fonrec1) = 8
              AND CAST((SUBSTRING(fonrec1, 1, 4))AS INT) BETWEEN 5700 AND 5768
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'1160')
		
			END
		ELSE 
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'1170')
		
			END			    
                
    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'1180')    

 
-----------------------------------------------------------------------------------------------


-- UPDATE PARA ADCIONAR O DIGITO NOVE NOS TELEFONES QUE COMECAREM COM 6,7,8 E 9 
INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2020')
--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE COMECEM COM 6,7,8 E 9

      
    UPDATE cadcontr
    SET    fonrec2 = CAST('9' AS CHAR(1))+ CAST(fonrec2 AS CHAR(8))
    WHERE  dddrec2 = 11
		   AND LEN(fonrec2) = 8	 
           AND SUBSTRING(fonrec2, 1, 1) IN ( '6', '7', '8', '9' )
	IF @@ERROR = 0
		BEGIN	
			INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2030')
	
		END
    ELSE
		BEGIN 
			INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2040')
	
		END

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2050')		  

-- A PARTIR DAQUI É FEITO O UPDATE DOS TELEFONES QUE COMECAM COM 5....
INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2060')
--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5300 AND 5324

		
		UPDATE cadcontr
		SET fonrec2 = 	CAST('9' AS CHAR(1))+ CAST(fonrec2 AS CHAR(8))
		WHERE dddrec2 = 11
			  AND LEN(fonrec2) = 8
              AND CAST((SUBSTRING(fonrec2, 1, 4))AS INT) BETWEEN 5300 AND 5324
		IF @@ERROR = 0
			BEGIN 
			INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2070')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2080')
		
			END			    

    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2090')            
    
	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2100')    
--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5472 AND 5474

		UPDATE cadcontr
		SET fonrec2 = 	CAST('9' AS CHAR(1))+ CAST(fonrec2 AS CHAR(8))
		WHERE dddrec2 = 11 
			  AND LEN(fonrec2) = 8
              AND CAST((SUBSTRING(fonrec2, 1, 4))AS INT) BETWEEN 5472 AND 5474
        
		IF @@ERROR = 0
		BEGIN 
			
			INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2110')
		END	
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2120')
		
			END			    
  
    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2130')
    
	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2140')
--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5769 AND 5786

		
		UPDATE cadcontr
		SET fonrec2 = 	CAST('9' AS CHAR(1))+ CAST(fonrec2 AS CHAR(8))
		WHERE dddrec2 = 11
			  AND LEN(fonrec2) = 8
              AND CAST((SUBSTRING(fonrec2, 1, 4))AS INT) BETWEEN 5769 AND 5786
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2150')
		
			END
		ELSE 
			BEGIN
		INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2160')
			
		
			END			    

    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2170')

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2180')
--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5200 AND 5211

		
		UPDATE cadcontr
		SET fonrec2 = 	CAST('9' AS CHAR(1))+ CAST(fonrec2 AS CHAR(8))
		WHERE dddrec2 = 11
			  AND LEN(fonrec2) = 8
              AND CAST((SUBSTRING(fonrec2, 1, 4))AS INT) BETWEEN 5200 AND 5211
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2190')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2200')
		
			END			    

    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2210')
	
	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2230')
--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5214 AND 5251


		
		UPDATE cadcontr
		SET fonrec2 = 	CAST('9' AS CHAR(1))+ CAST(fonrec2 AS CHAR(8))
		WHERE dddrec2 = 11
			  AND LEN(fonrec2) = 8
              AND CAST((SUBSTRING(fonrec2, 1, 4))AS INT) BETWEEN 5214 AND 5251
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2240')
	
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2250')
		
			END			    


    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2260')
    
	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2270')    
--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5268 AND 5299

		
		UPDATE cadcontr
		SET fonrec2 = 	CAST('9' AS CHAR(1))+ CAST(fonrec2 AS CHAR(8))
		WHERE dddrec2 = 11
		      AND LEN(fonrec2) = 8
              AND CAST((SUBSTRING(fonrec2, 1, 4))AS INT) BETWEEN 5268 AND 5299
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2280')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2290')
		
			END			    

    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2300')

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2310')
--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5329 AND 5351

		
		UPDATE cadcontr
		SET fonrec2 = 	CAST('9' AS CHAR(1))+ CAST(fonrec2 AS CHAR(8))
		WHERE dddrec2 = 11
			  AND LEN(fonrec2) = 8
              AND CAST((SUBSTRING(fonrec2, 1, 4))AS INT) BETWEEN 5329 AND 5351
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2320')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2330')
		
			END

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2340')				        

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2350')
--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5420 AND 5471

		
		UPDATE cadcontr
		SET fonrec2 = 	CAST('9' AS CHAR(1))+ CAST(fonrec2 AS CHAR(8))
		WHERE dddrec2 = 11 
			  AND LEN(fonrec2) = 8
              AND CAST((SUBSTRING(fonrec2, 1, 4))AS INT) BETWEEN 5420 AND 5471
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2360')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2370')
		
			END			    

    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2380') 
    
	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2390')
--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5475 AND 5499

		
		UPDATE cadcontr
		SET fonrec2 = 	CAST('9' AS CHAR(1))+ CAST(fonrec2 AS CHAR(8))
		WHERE dddrec2 = 11
			  AND LEN(fonrec2) = 8
              AND CAST((SUBSTRING(fonrec2, 1, 4))AS INT) BETWEEN 5475 AND 5499
		IF @@ERROR = 0
			BEGIN 
     			INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2400')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2410')
		
			END			    

    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2420')        

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2430')
--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5787 AND 5799

		
		UPDATE cadcontr
		SET fonrec2 = 	CAST('9' AS CHAR(1))+ CAST(fonrec2 AS CHAR(8))
		WHERE dddrec2 = 11
			  AND LEN(fonrec2) = 8
              AND CAST((SUBSTRING(fonrec2, 1, 4))AS INT) BETWEEN 5787 AND 5799
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2440')
	
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2450')
		
			END			    

    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2460')    

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2470')    
--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5252 AND 5267

		
		UPDATE cadcontr
		SET fonrec2 = 	CAST('9' AS CHAR(1))+ CAST(fonrec2 AS CHAR(8))
		WHERE  dddrec2 = 11
			   AND LEN(fonrec2) = 8
               AND CAST((SUBSTRING(fonrec2, 1, 4))AS INT) BETWEEN 5252 AND 5267
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2480')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2490')
		
			END			    
 
    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2500')    
    
	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2510')    
--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5400 AND 5419

		
		UPDATE cadcontr
		SET fonrec2 = 	CAST('9' AS CHAR(1))+ CAST(fonrec2 AS CHAR(8))
		WHERE dddrec2 = 11
			  AND LEN(fonrec2) = 8
              AND CAST((SUBSTRING(fonrec2, 1, 4))AS INT) BETWEEN 5400 AND 5419
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2520')
		
			END
		ELSE 
			BEGIN
			INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2530')
		
			END			    

       INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2540') 
           
	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2550')
--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5700 AND 5768

		
		UPDATE cadcontr
		SET fonrec2 = 	CAST('9' AS CHAR(1))+ CAST(fonrec2 AS CHAR(8))
		WHERE dddrec2 = 11
		     AND LEN(fonrec2) = 8
             AND CAST((SUBSTRING(fonrec2, 1, 4))AS INT) BETWEEN 5700 AND 5768
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2560')
			END
		ELSE 
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2570')
		
			END			    
               
    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2580')    
    
                   


----------------------------------------------------------------------------------------
-- Começa o update na tblocali

-- UPDATE PARA ADCIONAR O DIGITO NOVE NOS TELEFONES QUE COMECAREM COM 6,7,8 E 9 
INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2650')
-- UPDATE PARA ADCIONAR O DIGITO NOVE NOS TELEFONES QUE COMECAREM COM 6,7,8 E 9 
		
	UPDATE tblocali
	SET    nr_telefone = CAST('9' AS CHAR(1))+ CAST(nr_telefone AS CHAR(8))
	WHERE  nr_ddd = '11'
		   AND LEN(nr_telefone) = 8	
           AND SUBSTRING(nr_telefone, 1, 1) IN ( '6', '7', '8', '9' )
	IF @@ERROR = 0
		BEGIN	
			INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2670')
		END
    ELSE
		BEGIN 
			INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2680')
	
		END

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2690')		  

-- A PARTIR DAQUI É FEITO O UPDATE DOS TELEFONES QUE COMECAM COM 5....
INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2700')

		UPDATE tblocali
		SET nr_telefone = 	CAST('9' AS CHAR(1))+ CAST(nr_telefone AS CHAR(8))
		WHERE nr_ddd = '11' 
		      AND LEN(nr_telefone) = 8
              AND CAST((SUBSTRING(nr_telefone, 1, 4))AS INT) BETWEEN 5300 AND 5324
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2800')
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2810')
		
			END			    


    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2820')

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2830 ')
                    
-- UPDATE PARA ADCIONAR O DIGITO NOVE NOS TELEFONES QUE ESTAO ENTRE  5472 AND 5474
			
		UPDATE tblocali
		SET nr_telefone = 	CAST('9' AS CHAR(1))+ CAST(nr_telefone AS CHAR(8))
		WHERE nr_ddd = '11' 
		      AND  LEN(nr_telefone) = 8
              AND CAST((SUBSTRING(nr_telefone, 1, 4))AS INT) BETWEEN 5472 AND 5474
        
		IF @@ERROR = 0
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2840') 
		
			END	
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2850')
		 
			END			    

   
        INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2860')

		INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2870')        
-- UPDATE PARA ADCIONAR O DIGITO NOVE NOS TELEFONES QUE ESTAO ENTRE  5769 AND 5786
		

		UPDATE tblocali
		SET nr_telefone = 	CAST('9' AS CHAR(1))+ CAST(nr_telefone AS CHAR(8))
		WHERE nr_ddd = '11' 
		      AND LEN(nr_telefone) = 8
              AND CAST((SUBSTRING(nr_telefone, 1, 4))AS INT) BETWEEN 5769 AND 5786
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2880')
		
			END
		ELSE 
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2890')
			
			END			    

 
    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2900')

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2910')
-- UPDATE PARA ADCIONAR O DIGITO NOVE NOS TELEFONES QUE ESTAO ENTRE  5200 AND 5211

		
		UPDATE tblocali
		SET nr_telefone = 	CAST('9' AS CHAR(1))+ CAST(nr_telefone AS CHAR(8))
		WHERE nr_ddd = '11'
		      AND LEN(nr_telefone) = 8
              AND CAST((SUBSTRING(nr_telefone, 1, 4))AS INT) BETWEEN 5200 AND 5211
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2920')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2930')
			END			    

    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2940')
        
	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2950')        

-- UPDATE PARA ADCIONAR O DIGITO NOVE NOS TELEFONES QUE ESTAO ENTRE  5214 AND 5251
		
		UPDATE tblocali
		SET nr_telefone = 	CAST('9' AS CHAR(1))+ CAST(nr_telefone AS CHAR(8))
		WHERE nr_ddd = '11' 
			      AND LEN(nr_telefone) = 8
                  AND CAST((SUBSTRING(nr_telefone, 1, 4))AS INT) BETWEEN 5214 AND 5251
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2960')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2970')
		
			END			    


    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2980')
            
	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'2990')            
-- UPDATE PARA ADCIONAR O DIGITO NOVE NOS TELEFONES QUE ESTAO ENTRE  5268 AND 5299
		
		UPDATE tblocali
		SET nr_telefone = 	CAST('9' AS CHAR(1))+ CAST(nr_telefone AS CHAR(8))
		WHERE nr_ddd = '11' 
		      AND LEN(nr_telefone) = 8
              AND CAST((SUBSTRING(nr_telefone, 1, 4))AS INT) BETWEEN 5268 AND 5299
		IF @@ERROR = 0
			BEGIN 
			INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3000')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3010')
		    END			    

        INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3020')

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3030')            

-- UPDATE PARA ADCIONAR O DIGITO NOVE NOS TELEFONES QUE ESTAO ENTRE  5329 AND 5351
		
		UPDATE tblocali
		SET nr_telefone = 	CAST('9' AS CHAR(1))+ CAST(nr_telefone AS CHAR(8))
		WHERE nr_ddd = '11' 
		      AND LEN(nr_telefone) = 8
              AND CAST((SUBSTRING(nr_telefone, 1, 4))AS INT) BETWEEN 5329 AND 5351
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3040')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3050')
		
			END
 
			INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3060')				    
			
	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3070')			    

-- UPDATE PARA ADCIONAR O DIGITO NOVE NOS TELEFONES QUE ESTAO ENTRE  542 AND 5471

		
		UPDATE tblocali
		SET nr_telefone = 	CAST('9' AS CHAR(1))+ CAST(nr_telefone AS CHAR(8))
		WHERE nr_ddd = '11' 
		      AND  LEN(nr_telefone) = 8
              AND CAST((SUBSTRING(nr_telefone, 1, 4))AS INT) BETWEEN 5420 AND 5471
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3080')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3090')
		
			END			    


    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3100') 
       
	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3010 ')           

-- UPDATE PARA ADCIONAR O DIGITO NOVE NOS TELEFONES QUE ESTAO ENTRE  5475 AND 5499

		
		UPDATE tblocali
		SET nr_telefone = 	CAST('9' AS CHAR(1))+ CAST(nr_telefone AS CHAR(8))
		WHERE nr_ddd = '11' 
			  AND LEN(nr_telefone) = 8
              AND CAST((SUBSTRING(nr_telefone, 1, 4))AS INT) BETWEEN 5475 AND 5499
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3020')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3030')
		
			END			    

 
    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3040')
        
	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3050')    
	
	-- UPDATE PARA ADCIONAR O DIGITO NOVE NOS TELEFONES QUE ESTAO ENTRE  5787 AND 5799
		
		UPDATE tblocali
		SET nr_telefone = 	CAST('9' AS CHAR(1))+ CAST(nr_telefone AS CHAR(8))
		WHERE nr_ddd = '11' 
			  AND LEN(nr_telefone) = 8
              AND CAST((SUBSTRING(nr_telefone, 1, 4))AS INT) BETWEEN 5787 AND 5799
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3060')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3070')
		
			END			    

   
        INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3080')
        
	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3090')    

-- UPDATE PARA ADCIONAR O DIGITO NOVE NOS TELEFONES QUE ESTAO ENTRE  5252 AND 5267

		
		UPDATE tblocali
		SET nr_telefone = 	CAST('9' AS CHAR(1))+ CAST(nr_telefone AS CHAR(8))
		WHERE nr_ddd = '11' 
		      AND LEN(nr_telefone) = 8
              AND CAST((SUBSTRING(nr_telefone, 1, 4))AS INT) BETWEEN 5252 AND 5267
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3100')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3120')
		
			END			    
  
        INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3130')

    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3140')
-- UPDATE PARA ADCIONAR O DIGITO NOVE NOS TELEFONES QUE ESTAO ENTRE  5400 AND 5419
		
		UPDATE tblocali
		SET nr_telefone = 	CAST('9' AS CHAR(1))+ CAST(nr_telefone AS CHAR(8))
		WHERE nr_ddd = '11' 
			  AND LEN(nr_telefone) = 8
              AND CAST((SUBSTRING(nr_telefone, 1, 4))AS INT) BETWEEN 5400 AND 5419
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3140')
		
			END
		ELSE 
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3150')
		
			END			    

       INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3160') 

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3170')

-- UPDATE PARA ADCIONAR O DIGITO NOVE NOS TELEFONES QUE ESTAO ENTRE  5700 AND 5768
		
			UPDATE tblocali
			SET nr_telefone = 	CAST('9' AS CHAR(1))+ CAST(nr_telefone AS CHAR(8))
			WHERE nr_ddd = '11'
			      AND LEN(nr_telefone) = 8
                  AND CAST((SUBSTRING(nr_telefone, 1, 4))AS INT) BETWEEN 5700 AND 5768
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3180')
		
			END
		ELSE 
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3190')
			END			    
                 

   INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3200')
    
    
                   


--AQUI ACABA
--------------------------------------------------------------------------------------
-- Atualiza a tabela celular...

/*

-- UPDATE PARA ADCIONAR O DIGITO NOVE NOS TELEFONES QUE COMECAREM COM 6,7,8 E 9 
		  
		INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3250')
		UPDATE tblocali
		SET    nr_celular = CAST('9' AS CHAR(1))+ CAST(nr_celular AS CHAR(8))
		WHERE  nr_ddd_cel = '11' 				 
			   AND	LEN(nr_celular) = 8
     		   AND SUBSTRING(nr_celular, 1, 1) IN ( '6', '7', '8', '9' )
		IF @@ERROR = 0
			BEGIN	
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3260')
		
		END
		
		ELSE
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3270')
		
			END
		INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3280')		  
 


-- UPDATE PARA ADCIONAR O DIGITO NOVE NOS TELEFONES QUE ESTAO ENTRE  5300 AND 5324
		
		INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3290')

		UPDATE tblocali
		SET nr_celular = 	CAST('9' AS CHAR(1))+ CAST(nr_celular AS CHAR(8))
		WHERE nr_ddd_cel = '11' 
			      AND LEN(nr_celular) = 8
                  AND CAST((SUBSTRING(nr_celular, 1, 4))AS INT) BETWEEN 5300 AND 5324
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3300')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3310')
		
			END			    
        INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3320')
 
            

-- UPDATE PARA ADCIONAR O DIGITO NOVE NOS TELEFONES QUE ESTAO ENTRE  5472 AND 5474		
		
	    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3330')

		UPDATE tblocali
		SET nr_celular = 	CAST('9' AS CHAR(1))+ CAST(nr_celular AS CHAR(8))
		WHERE nr_ddd_cel = '11'  
		      AND LEN(nr_celular) = 8
              AND CAST((SUBSTRING(nr_celular, 1, 4))AS INT) BETWEEN 5472 AND 5474
        
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3340')
			
			END	
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3350')
		 
			END			    
        INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3360')
  


-- UPDATE PARA ADCIONAR O DIGITO NOVE NOS TELEFONES QUE ESTAO ENTRE  5769 AND 5786
		
		INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3370')
		UPDATE tblocali
		SET nr_celular = 	CAST('9' AS CHAR(1))+ CAST(nr_celular AS CHAR(8))
		WHERE nr_ddd_cel = '11' 
			  AND LEN(nr_celular) = 8
              AND CAST((SUBSTRING(nr_celular, 1, 4))AS INT) BETWEEN 5769 AND 5786
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3380')
		
			END
		ELSE 
			BEGIN
			INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3390')
			
		
			END			    
        INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3400')
    

-- UPDATE PARA ADCIONAR O DIGITO NOVE NOS TELEFONES QUE ESTAO ENTRE  5200 AND 5211
	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3410')
		
		UPDATE tblocali
		SET nr_celular = 	CAST('9' AS CHAR(1))+ CAST(nr_celular AS CHAR(8))
		WHERE nr_ddd_cel = '11' 
			  AND LEN(nr_celular) = 8
              AND CAST((SUBSTRING(nr_celular, 1, 4))AS INT) BETWEEN 5200 AND 5211
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3420')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3430')
		
			END			    
        INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3440')
 

-- UPDATE PARA ADCIONAR O DIGITO NOVE NOS TELEFONES QUE ESTAO ENTRE  5214 AND 5251
	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3450')
		
		UPDATE tblocali
		SET nr_celular = 	CAST('9' AS CHAR(1))+ CAST(nr_celular AS CHAR(8))
		WHERE nr_ddd_cel = '11' 
		      AND LEN(nr_celular) = 8
              AND CAST((SUBSTRING(nr_celular, 1, 4))AS INT) BETWEEN 5214 AND 5251
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3460')
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3470')
		
			END			    
        INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3480')


-- UPDATE PARA ADCIONAR O DIGITO NOVE NOS TELEFONES QUE ESTAO ENTRE  5268 AND 5299
	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3490')
		
		UPDATE tblocali
		SET nr_celular = 	CAST('9' AS CHAR(1))+ CAST(nr_celular AS CHAR(8))
		WHERE nr_ddd_cel = '11' 
			  AND LEN(nr_celular) = 8
              AND CAST((SUBSTRING(nr_celular, 1, 4))AS INT) BETWEEN 5268 AND 5299
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3500')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3510')
		
			END			    
        INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3520')


-- UPDATE PARA ADCIONAR O DIGITO NOVE NOS TELEFONES QUE ESTAO ENTRE  5329 AND 5351
	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3530')
		
		UPDATE tblocali
		SET nr_celular = 	CAST('9' AS CHAR(1))+ CAST(nr_celular AS CHAR(8))
		WHERE nr_ddd_cel = '11' 
		      AND LEN(nr_celular) = 8
              AND CAST((SUBSTRING(nr_celular, 1, 4))AS INT) BETWEEN 5329 AND 5351
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3540')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3550')
		
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3560')				    
			END
  
    

-- UPDATE PARA ADCIONAR O DIGITO NOVE NOS TELEFONES QUE ESTAO ENTRE  5420 AND 5471
	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3570')
		
		UPDATE tblocali
		SET nr_celular = 	CAST('9' AS CHAR(1))+ CAST(nr_celular AS CHAR(8))
		WHERE nr_ddd_cel = '11'  
		      AND LEN(nr_celular) = 8
              AND CAST((SUBSTRING(nr_celular, 1, 4))AS INT) BETWEEN 5420 AND 5471
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3580')
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3590')
			END			    
       INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3600') 
    
    

-- UPDATE PARA ADCIONAR O DIGITO NOVE NOS TELEFONES QUE ESTAO ENTRE  5475 AND 5499
	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3610 ')
		
		UPDATE tblocali
		SET nr_celular = 	CAST('9' AS CHAR(1))+ CAST(nr_celular AS CHAR(8))
		WHERE nr_ddd_cel = '11' 
			  AND LEN(nr_celular) = 8
              AND CAST((SUBSTRING(nr_celular, 1, 4))AS INT) BETWEEN 5475 AND 5499
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3620')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3630')
		
			END			    
    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3640')    

    

-- UPDATE PARA ADCIONAR O DIGITO NOVE NOS TELEFONES QUE ESTAO ENTRE  5787 AND 5799
	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3650')
		
		UPDATE tblocali
		SET nr_celular = 	CAST('9' AS CHAR(1))+ CAST(nr_celular AS CHAR(8))
		WHERE nr_ddd_cel = '11' 
			  AND LEN(nr_celular) = 8
              AND CAST((SUBSTRING(nr_celular, 1, 4))AS INT) BETWEEN 5787 AND 5799
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3660')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3670')
		
			END			    
        INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3680')
   

-- UPDATE PARA ADCIONAR O DIGITO NOVE NOS TELEFONES QUE ESTAO ENTRE  5252 AND 5267
	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3690')
		
		UPDATE tblocali
		SET nr_celular = 	CAST('9' AS CHAR(1))+ CAST(nr_celular AS CHAR(8))
		WHERE  nr_ddd_cel = '11' 
			   AND LEN(nr_celular) = 8
               AND CAST((SUBSTRING(nr_celular, 1, 4))AS INT) BETWEEN 5252 AND 5267
		IF @@ERROR = 0
			BEGIN 
			INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3700')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3710')
		    END			    
        INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3720')
     
    

-- UPDATE PARA ADCIONAR O DIGITO NOVE NOS TELEFONES QUE ESTAO ENTRE  5400 AND 5419
	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3730')
		
		UPDATE tblocali
		SET nr_celular = 	CAST('9' AS CHAR(1))+ CAST(nr_celular AS CHAR(8))
		WHERE nr_ddd_cel = '11' 
		      AND LEN(nr_celular) = 8
              AND CAST((SUBSTRING(nr_celular, 1, 4))AS INT) BETWEEN 5400 AND 5419
		IF @@ERROR = 0
			BEGIN 
			INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3740')
		
			END
		ELSE 
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3750')
		
			END			    
       INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3760') 

    

-- UPDATE PARA ADCIONAR O DIGITO NOVE NOS TELEFONES QUE ESTAO ENTRE  5700 AND 5768
	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3770')
		UPDATE tblocali
		SET nr_celular = 	CAST('9' AS CHAR(1))+ CAST(nr_celular AS CHAR(8))
		WHERE nr_ddd_cel = '11' 
		      AND LEN(nr_celular) = 8
              AND CAST((SUBSTRING(nr_celular, 1, 4))AS INT) BETWEEN 5700 AND 5768
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3780')
		
			END
		ELSE 
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3790')
			END			    
        INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3800')
*/
--------------------------------------------------------------------------------------------------
-- Começa o update da cadcontr.. [FONE REF]






--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE COMECAM COM 6,7,8 E 9

    
	UPDATE cadcontr
	SET    [FONE REF] = CAST('9' AS CHAR(1))+ CAST([FONE REF] AS CHAR(8))
	WHERE  [DDD REF] = '11'
			   AND LEN([FONE REF]) = 8
               AND SUBSTRING([FONE REF], 1, 1) IN ( '6', '7', '8', '9' )
    IF @@ERROR = 0
		BEGIN	
			INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3840')
	
	END
    
    ELSE
		BEGIN 
			INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3850')
	
		END
	
	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3860')		  
 

-- A PARTIR DAQUI É FEITO O UPDATE DOS TELEFONES QUE COMECAM COM 5....
INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3870')


--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5300 AND 5324

	
		UPDATE cadcontr
		SET [FONE REF] = 	CAST('9' AS CHAR(1))+ CAST([FONE REF] AS CHAR(8))
		WHERE [DDD REF] = '11'
			  AND LEN([FONE REF]) = 8
              AND CAST((SUBSTRING([FONE REF], 1, 4))AS INT) BETWEEN 5300 AND 5324
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3880')
		
		
			END
		
		ELSE
		
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3890')
		
		
			END			    

    
    
    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3900')
    
	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3910')    

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5472 AND 5474

		
		UPDATE cadcontr
		SET [FONE REF] = 	CAST('9' AS CHAR(1))+ CAST([FONE REF] AS CHAR(8))
		WHERE [DDD REF] = '11' 
			  AND LEN([FONE REF]) = 8
              AND CAST((SUBSTRING([FONE REF], 1, 4))AS INT) BETWEEN 5472 AND 5474
        
		IF @@ERROR = 0
			BEGIN 
		
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3920')
			END	
		ELSE 
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3930')
		 
		
			END			    
 
    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3940')
    
    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3950')


--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5779 AND 5786

		
		UPDATE cadcontr
		SET [FONE REF] = 	CAST('9' AS CHAR(1))+ CAST([FONE REF] AS CHAR(8))
		WHERE [DDD REF] = '11'
			  AND  LEN([FONE REF]) = 8
              AND CAST((SUBSTRING([FONE REF], 1, 4))AS INT) BETWEEN 5769 AND 5786
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3960')
			END
		ELSE 
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3970')
			
				
			END			    

INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3980')

INSERT INTO LOG_ANDRE VALUES (GETDATE(),'3990')

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5200 AND 5211

		
		UPDATE cadcontr
		SET [FONE REF] = 	CAST('9' AS CHAR(1))+ CAST([FONE REF] AS CHAR(8))
		WHERE [DDD REF] = '11'
			  AND LEN([FONE REF]) = 8
              AND CAST((SUBSTRING([FONE REF], 1, 4))AS INT) BETWEEN 5200 AND 5211
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'4000')
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'4010')
			END			    


INSERT INTO LOG_ANDRE VALUES (GETDATE(),'4020')

INSERT INTO LOG_ANDRE VALUES (GETDATE(),'4030')

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5214 AND 5251

		
		UPDATE cadcontr
		SET [FONE REF] = 	CAST('9' AS CHAR(1))+ CAST([FONE REF] AS CHAR(8))
		WHERE [DDD REF] = '11'
			  AND LEN([FONE REF]) = 8
		      AND CAST((SUBSTRING([FONE REF], 1, 4))AS INT) BETWEEN 5214 AND 5251
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'4040')
		
			END
		
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'4050')
		
		
			END			    


    
INSERT INTO LOG_ANDRE VALUES (GETDATE(),'4060')

INSERT INTO LOG_ANDRE VALUES (GETDATE(),'4070')    

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5268 AND 5299

		
		UPDATE cadcontr
		SET [FONE REF] = 	CAST('9' AS CHAR(1))+ CAST([FONE REF] AS CHAR(8))
		WHERE [DDD REF] = '11'
			  AND LEN([FONE REF]) = 8
              AND CAST((SUBSTRING([FONE REF], 1, 4))AS INT) BETWEEN 5268 AND 5299
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'4080')
				
			END
		
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'4090')
		    END			    
    

    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'5000')    

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'5010')

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5329 AND 5351

		
		UPDATE cadcontr
		SET [FONE REF] = 	CAST('9' AS CHAR(1))+ CAST([FONE REF] AS CHAR(8))
		WHERE [DDD REF] = '11'
			  AND LEN([FONE REF]) = 8
              AND CAST((SUBSTRING([FONE REF], 1, 4))AS INT) BETWEEN 5329 AND 5351
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'5020')
	
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'5030')
		
			END
    
	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'5040')				        

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'5050')

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5420 AND 5471

		
		UPDATE cadcontr
		SET [FONE REF] = 	CAST('9' AS CHAR(1))+ CAST([FONE REF] AS CHAR(8))
		WHERE [DDD REF] = '11' 
			  AND   LEN([FONE REF]) = 8
              AND CAST((SUBSTRING([FONE REF], 1, 4))AS INT) BETWEEN 5420 AND 5471
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'5060')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'5070')
		
			END			    


    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'5080')     

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'5090')    

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5475 AND 5499

		
		UPDATE cadcontr
		SET [FONE REF] = 	CAST('9' AS CHAR(1))+ CAST([FONE REF] AS CHAR(8))
		WHERE [DDD REF] = '11'
			  AND LEN([FONE REF]) = 8
              AND CAST((SUBSTRING([FONE REF], 1, 4))AS INT) BETWEEN 5475 AND 5499
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6000')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6010')
		
			END			    

    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6020')    

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6030')        

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5787 AND 5799

		UPDATE cadcontr
		SET [FONE REF] = 	CAST('9' AS CHAR(1))+ CAST([FONE REF] AS CHAR(8))
		WHERE  [DDD REF] = '11'
		       AND LEN([FONE REF]) = 8
               AND CAST((SUBSTRING([FONE REF], 1, 4))AS INT) BETWEEN 5787 AND 5799
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6040')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6050')
			END			    

    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6060')

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6070')    

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5252 AND 5267

		
		UPDATE cadcontr
		SET [FONE REF] = 	CAST('9' AS CHAR(1))+ CAST([FONE REF] AS CHAR(8))
		WHERE  [DDD REF] = '11'
			   AND LEN([FONE REF]) = 8
               AND CAST((SUBSTRING([FONE REF], 1, 4))AS INT) BETWEEN 5252 AND 5267
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6080')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6090')
		
			END			    

    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6100')    

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6110')    

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5400 AND 5419

		
		UPDATE cadcontr
		SET [FONE REF] = 	CAST('9' AS CHAR(1))+ CAST([FONE REF] AS CHAR(8))
		WHERE LEN([FONE REF]) = 8
			  AND [DDD REF] = '11'
              AND CAST((SUBSTRING([FONE REF], 1, 4))AS INT) BETWEEN 5400 AND 5419
		IF @@ERROR = 0
			BEGIN 
			INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6120')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6130')
						
			END			    

    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6140')     
    
    

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5700 AND 5768

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6150')
		
		UPDATE cadcontr
		SET [FONE REF] = 	CAST('9' AS CHAR(1))+ CAST([FONE REF] AS CHAR(8))
		WHERE [DDD REF] = '11'
			  AND  LEN([FONE REF]) = 8
              AND CAST((SUBSTRING([FONE REF], 1, 4))AS INT) BETWEEN 5700 AND 5768
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6160')
		
			END
		ELSE 
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6170')
			END			    
                
    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6180')        
    
-----------------------------------------------------------------------------------------------
    
 	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6190')


--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE COMECAM COM 6,7,8 E 9

    
	UPDATE cadcontr
	SET    cl_fon = CAST('9' AS CHAR(1))+ CAST(cl_fon AS CHAR(8))
	WHERE  cl_ddd = 11
		   AND LEN(cl_fon) = 8
           AND SUBSTRING(cl_fon, 1, 1) IN ( '6', '7', '8', '9' )
    IF @@ERROR = 0
		BEGIN	
			INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6200')
	
		END
    
    ELSE
		BEGIN 
			INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6210')
	
		END
	
	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6220')		  
 

-- A PARTIR DAQUI É FEITO O UPDATE DOS TELEFONES QUE COMECAM COM 5....
INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6230')


--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5300 AND 5324

		
		UPDATE cadcontr
		SET cl_fon = 	CAST('9' AS CHAR(1))+ CAST(cl_fon AS CHAR(8))
		WHERE cl_ddd = 11
			  AND LEN(cl_fon) = 8
              AND CAST((SUBSTRING(cl_fon, 1, 4))AS INT) BETWEEN 5300 AND 5324
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6240')
				
			END
		
		ELSE
		
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6250')
				
			END			    

    
    
    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6260')
    
	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6270')    

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5472 AND 5474

		
		UPDATE cadcontr
		SET cl_fon = 	CAST('9' AS CHAR(1))+ CAST(cl_fon AS CHAR(8))
		WHERE cl_ddd = 11 
			  AND LEN(cl_fon) = 8
              AND CAST((SUBSTRING(cl_fon, 1, 4))AS INT) BETWEEN 5472 AND 5474
        
		IF @@ERROR = 0
			BEGIN 
		
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6280')
			END	
		ELSE 
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6290')
		 
		
			END			    
 
    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6300')
    
    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6310')


--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5779 AND 5786

		
		UPDATE cadcontr
		SET cl_fon = 	CAST('9' AS CHAR(1))+ CAST(cl_fon AS CHAR(8))
		WHERE cl_ddd = 11
			  AND  LEN(cl_fon) = 8
              AND CAST((SUBSTRING(cl_fon, 1, 4))AS INT) BETWEEN 5769 AND 5786
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6320')
			END
		ELSE 
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6330')
			
				
			END			    

INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6340')

INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6350')

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5200 AND 5211

		UPDATE cadcontr
		SET cl_fon = 	CAST('9' AS CHAR(1))+ CAST(cl_fon AS CHAR(8))
		WHERE cl_ddd = 11
			  AND LEN(cl_fon) = 8
              AND CAST((SUBSTRING(cl_fon, 1, 4))AS INT) BETWEEN 5200 AND 5211
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6360')
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6370')
			END			    


INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6380')

INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6390')

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5214 AND 5251

		
		UPDATE cadcontr
		SET cl_fon = 	CAST('9' AS CHAR(1))+ CAST(cl_fon AS CHAR(8))
		WHERE cl_ddd = 11
			  AND LEN(cl_fon) = 8
			  AND CAST((SUBSTRING(cl_fon, 1, 4))AS INT) BETWEEN 5214 AND 5251
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6400')
		
			END
		
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6410')
		
		
			END			    


    
INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6420')

INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6430')    

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5268 AND 5299

		
		UPDATE cadcontr
		SET cl_fon = 	CAST('9' AS CHAR(1))+ CAST(cl_fon AS CHAR(8))
		WHERE cl_ddd = 11
			  AND LEN(cl_fon) = 8
              AND CAST((SUBSTRING(cl_fon, 1, 4))AS INT) BETWEEN 5268 AND 5299
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6450')
				
			END
		
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6460')
		
			END			    
    

    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6470')    

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6480')

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5329 AND 5351

		
		UPDATE cadcontr
		SET cl_fon = 	CAST('9' AS CHAR(1))+ CAST(cl_fon AS CHAR(8))
		WHERE cl_ddd = 11
			  AND LEN(cl_fon) = 8
              AND CAST((SUBSTRING(cl_fon, 1, 4))AS INT) BETWEEN 5329 AND 5351
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6490')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6500')
		
			END
    
	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6510')				        

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6520')

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5420 AND 5471

		
		UPDATE cadcontr
		SET cl_fon = 	CAST('9' AS CHAR(1))+ CAST(cl_fon AS CHAR(8))
		WHERE cl_ddd = 11 
		      AND   LEN(cl_fon) = 8
              AND CAST((SUBSTRING(cl_fon, 1, 4))AS INT) BETWEEN 5420 AND 5471
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6530')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6540')
		
			END			    


    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6550')     

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6560')    

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5475 AND 5499

		
		UPDATE cadcontr
		SET cl_fon = 	CAST('9' AS CHAR(1))+ CAST(cl_fon AS CHAR(8))
		WHERE cl_ddd = 11
		      AND LEN(cl_fon) = 8
              AND CAST((SUBSTRING(cl_fon, 1, 4))AS INT) BETWEEN 5475 AND 5499
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6560')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6570')
		
			END			    

    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6580')    

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6590')        

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5787 AND 5799

		
		UPDATE cadcontr
		SET cl_fon = 	CAST('9' AS CHAR(1))+ CAST(cl_fon AS CHAR(8))
		WHERE  cl_ddd = 11
			   AND LEN(cl_fon) = 8
               AND CAST((SUBSTRING(cl_fon, 1, 4))AS INT) BETWEEN 5787 AND 5799
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6600')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6610')
		
			END			    

    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6620')

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6630')    

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5252 AND 5267

		
		UPDATE cadcontr
		SET cl_fon = 	CAST('9' AS CHAR(1))+ CAST(cl_fon AS CHAR(8))
		WHERE  cl_ddd = 11
			   AND LEN(cl_fon) = 8
               AND CAST((SUBSTRING(cl_fon, 1, 4))AS INT) BETWEEN 5252 AND 5267
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6640')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6650')
		
			END			    

    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6660')    

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6670')    

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5400 AND 5419

		
		UPDATE cadcontr
		SET cl_fon = 	CAST('9' AS CHAR(1))+ CAST(cl_fon AS CHAR(8))
		WHERE LEN(cl_fon) = 8
			  AND cl_ddd = 11
              AND CAST((SUBSTRING(cl_fon, 1, 4))AS INT) BETWEEN 5400 AND 5419
		IF @@ERROR = 0
			BEGIN 
			INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6680')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6690')
				
			END			    

    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6700')     
    
    

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5700 AND 5768

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6710')
		
		UPDATE cadcontr
		SET cl_fon = 	CAST('9' AS CHAR(1))+ CAST(cl_fon AS CHAR(8))
		WHERE cl_ddd = 11
			  AND  LEN(cl_fon) = 8
              AND CAST((SUBSTRING(cl_fon, 1, 4))AS INT) BETWEEN 5700 AND 5768
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6720')
		
			END
		ELSE 
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6730')
		
			END			    
                
    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6740')    

-----------------------------------------------------------------------------------------------
 	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6750')


--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE COMECAM COM 6,7,8 E 9

    
	UPDATE cadcontr
	SET    lt_fon = CAST('9' AS CHAR(1))+ CAST(lt_fon AS CHAR(8))
	WHERE  lt_ddd = 11
		   AND LEN(lt_fon) = 8
           AND SUBSTRING(lt_fon, 1, 1) IN ( '6', '7', '8', '9' )
    IF @@ERROR = 0
		BEGIN	
			INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6760')
	
		END
    
    ELSE
		BEGIN 
			INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6770')
	
		END
	
	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6780')		  
 

-- A PARTIR DAQUI É FEITO O UPDATE DOS TELEFONES QUE COMECAM COM 5....
INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6790')


--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5300 AND 5324

		
		UPDATE cadcontr
		SET lt_fon = 	CAST('9' AS CHAR(1))+ CAST(lt_fon AS CHAR(8))
		WHERE lt_ddd = 11
			  AND LEN(lt_fon) = 8
              AND CAST((SUBSTRING(lt_fon, 1, 4))AS INT) BETWEEN 5300 AND 5324
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6800')
				
			END
		
		ELSE
		
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6810')
				
			END			    

    
    
    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6820')
    
	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6830')    

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5472 AND 5474

		
		UPDATE cadcontr
		SET lt_fon = 	CAST('9' AS CHAR(1))+ CAST(lt_fon AS CHAR(8))
		WHERE lt_ddd = 11 
			  AND LEN(lt_fon) = 8
              AND CAST((SUBSTRING(lt_fon, 1, 4))AS INT) BETWEEN 5472 AND 5474
        
		IF @@ERROR = 0
			BEGIN 
		
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6840')
			END	
		ELSE 
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6850')
		 
		
			END			    
 
    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6860')
    
    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6870')


--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5779 AND 5786

		
		UPDATE cadcontr
		SET lt_fon = 	CAST('9' AS CHAR(1))+ CAST(lt_fon AS CHAR(8))
		WHERE lt_ddd = 11
			  AND  LEN(lt_fon) = 8
              AND CAST((SUBSTRING(lt_fon, 1, 4))AS INT) BETWEEN 5769 AND 5786
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6880')
			END
		ELSE 
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6890')
			
				
			END			    

INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6900')

INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6910')

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5200 AND 5211

		UPDATE cadcontr
		SET lt_fon = 	CAST('9' AS CHAR(1))+ CAST(lt_fon AS CHAR(8))
		WHERE lt_ddd = 11
			  AND LEN(lt_fon) = 8
              AND CAST((SUBSTRING(lt_fon, 1, 4))AS INT) BETWEEN 5200 AND 5211
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6920')
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6930')
			END			    


INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6940')

INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6950')

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5214 AND 5251

		
		UPDATE cadcontr
		SET lt_fon = 	CAST('9' AS CHAR(1))+ CAST(lt_fon AS CHAR(8))
		WHERE lt_ddd = 11
			  AND LEN(lt_fon) = 8
			  AND CAST((SUBSTRING(lt_fon, 1, 4))AS INT) BETWEEN 5214 AND 5251
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6960')
		
			END
		
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6970')
		
		
			END			    


    
INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6980')

INSERT INTO LOG_ANDRE VALUES (GETDATE(),'6990')    

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5268 AND 5299

		
		UPDATE cadcontr
		SET lt_fon = 	CAST('9' AS CHAR(1))+ CAST(lt_fon AS CHAR(8))
		WHERE lt_ddd = 11
			  AND LEN(lt_fon) = 8
              AND CAST((SUBSTRING(lt_fon, 1, 4))AS INT) BETWEEN 5268 AND 5299
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'7000')
				
			END
		
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'7010')
		
			END			    
    

    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'7020')    

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'7030')

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5329 AND 5351

		
		UPDATE cadcontr
		SET lt_fon = 	CAST('9' AS CHAR(1))+ CAST(lt_fon AS CHAR(8))
		WHERE lt_ddd = 11
			  AND LEN(lt_fon) = 8
              AND CAST((SUBSTRING(lt_fon, 1, 4))AS INT) BETWEEN 5329 AND 5351
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'7040')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'7050')
		
			END
    
	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'7060')				        

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'7070')

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5420 AND 5471

		
		UPDATE cadcontr
		SET lt_fon = 	CAST('9' AS CHAR(1))+ CAST(lt_fon AS CHAR(8))
		WHERE lt_ddd = 11 
		      AND   LEN(lt_fon) = 8
              AND CAST((SUBSTRING(lt_fon, 1, 4))AS INT) BETWEEN 5420 AND 5471
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'7080')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'7090')
		
			END			    


    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'7100')     

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'7110')    

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5475 AND 5499

		
		UPDATE cadcontr
		SET lt_fon = 	CAST('9' AS CHAR(1))+ CAST(lt_fon AS CHAR(8))
		WHERE lt_ddd = 11
		      AND LEN(lt_fon) = 8
              AND CAST((SUBSTRING(lt_fon, 1, 4))AS INT) BETWEEN 5475 AND 5499
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'7120')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'7130')
		
			END			    

    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'7140')    

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'7150')        

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5787 AND 5799

		
		UPDATE cadcontr
		SET lt_fon = 	CAST('9' AS CHAR(1))+ CAST(lt_fon AS CHAR(8))
		WHERE  lt_ddd = 11
			   AND LEN(lt_fon) = 8
               AND CAST((SUBSTRING(lt_fon, 1, 4))AS INT) BETWEEN 5787 AND 5799
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'7160')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'7170')
		
			END			    

    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'7180')

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'7190')    

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5252 AND 5267

		
		UPDATE cadcontr
		SET lt_fon = 	CAST('9' AS CHAR(1))+ CAST(lt_fon AS CHAR(8))
		WHERE  lt_ddd = 11
			   AND LEN(lt_fon) = 8
               AND CAST((SUBSTRING(lt_fon, 1, 4))AS INT) BETWEEN 5252 AND 5267
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'7200')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'7210')
		
			END			    

    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'7220')    

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'7230')    

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5400 AND 5419

		
		UPDATE cadcontr
		SET lt_fon = 	CAST('9' AS CHAR(1))+ CAST(lt_fon AS CHAR(8))
		WHERE LEN(lt_fon) = 8
			  AND lt_ddd = 11
              AND CAST((SUBSTRING(lt_fon, 1, 4))AS INT) BETWEEN 5400 AND 5419
		IF @@ERROR = 0
			BEGIN 
			INSERT INTO LOG_ANDRE VALUES (GETDATE(),'7240')
		
			END
		ELSE
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'7250')
				
			END			    

    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'7260')     
    
    

--COMECO DA INSTRUÇÃO PARA ADCIONAR O NUMERO 9 NA FRENTE DOS TELEFONES QUE ESTÃO ENTRE 5700 AND 5768

	INSERT INTO LOG_ANDRE VALUES (GETDATE(),'7270')
		
		UPDATE cadcontr
		SET lt_fon = 	CAST('9' AS CHAR(1))+ CAST(lt_fon AS CHAR(8))
		WHERE lt_ddd = 11
			  AND  LEN(lt_fon) = 8
              AND CAST((SUBSTRING(lt_fon, 1, 4))AS INT) BETWEEN 5700 AND 5768
		IF @@ERROR = 0
			BEGIN 
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'7280')
		
			END
		ELSE 
			BEGIN
				INSERT INTO LOG_ANDRE VALUES (GETDATE(),'7290')
		
			END			    
                
    INSERT INTO LOG_ANDRE VALUES (GETDATE(),'7300')    
-----------------------------------------------------------------------------------------------

