USE ROSARIO
GO

--DROP TABLE PRODUTO_TMP
/*
SELECT TOP 1 * FROM TT_PRO
SELECT TOP 1 * FROM TD_CL2
SELECT TOP 1 * FROM TD_CL1
SELECT TOP 1 * FROM TD_CL3
SELECT TOP 1 * FROM TD_CL4
SELECT TOP 1 * FROM TT_EAN
SELECT TOP 1 * FROM TT_PXF
SELECT TOP 1 * FROM TT_PRE
SELECT TOP 1 * FROM TT_GRA
SELECT TOP 1 * FROM TD_DEP
*/

SELECT DISTINCT
TT_PRO.DESMAT,
--REPLACE(TT_PRO.REFBAS, '.', '') AS REFBAS,
TT_PRO.REFBAS AS REFBAS,
--TT_PRO.DESMAT  AS 'DESC COMPRAS',
TT_PRO.DESMAT + ' ' + TT_PRO.ESPMAT AS 'DESC_COMPLETA',
CASE TD_DEP.DESDEP
	WHEN 'JOIAS' THEN 'JOI'
	WHEN 'MONTBLANC' THEN 'IE'
	WHEN 'OCULOS' THEN 'OC'
	WHEN 'RELOGIOS' THEN 'REL'
	WHEN 'UTILIDADES DOMESTICAS' THEN 'UD'
	WHEN 'DECORAÇÃO' THEN 'DEC'
	WHEN 'ELETRODOMESTICOS' THEN 'ELD'
	WHEN 'FOTOGRAÇÃO' THEN 'FG'
	WHEN 'ACESSORIOS' THEN 'AC'
	WHEN 'DIVERSOS' THEN 'DIV'
	WHEN 'ELETRODOMESTICOS' THEN 'ELE'
	ELSE TD_DEP.DESDEP
END AS DESDEP,
GG.TD_CL1_CLASS1 AS CLASS_DESC,
GG.G_GRUPO,
GG.GRUPO,
CASE TD_DEP.DESDEP
	WHEN 'JOIAS' THEN 'PC'
	WHEN 'OCULOS' THEN 'PC'
	WHEN 'RELOGIOS' THEN 'PC'
	ELSE 'UN'
END AS UNIDADE,
TT_PRO.DEPART,
TT_PRO.CLASS1,
--TD_CL2.CLASS2,
SB.[Codigo Capta] AS SGRUS,
TD_CL3.CLASS3,
TT_PRO.CLASS4,
CASE TD_CL4.CODTAB
	WHEN 3 THEN 'M'
	WHEN 4 THEN 'F'
END AS CODTAB,
TT_EAN.CODEAN,
TT_PXF.PRECOM AS pcuss,
CASE TT_PRE.CODMOE
	WHEN 0 THEN 'RS'
	WHEN 1 THEN 'OF'
END AS CODMOE,
TT_PRE.PRECOV,
TT_GRA.PRECOM AS custofs,
TT_PRO.FILMAT+TT_PRO.CODMAT AS FILMAT_CODMAT
--INTO PRODUTO_TMP
FROM TT_PRO
LEFT JOIN TD_CL1 ON TD_CL1.CODTAB = TT_PRO.CLASS1
--LEFT JOIN TD_CL2 ON TD_CL2.CODTAB = TT_PRO.CLASS2
LEFT JOIN IMPORT_SUBGRUPOS SB ON SB.class2 =  TT_PRO.CLASS2
LEFT JOIN TD_CL3 ON TD_CL3.CODTAB = TT_PRO.CLASS3
LEFT JOIN TD_CL4 ON TD_CL4.CODTAB = TT_PRO.CLASS4
LEFT JOIN TT_EAN ON TT_EAN.FILMAT+TT_EAN.CODMAT = TT_PRO.FILMAT+TT_PRO.CODMAT
LEFT JOIN TT_PXF ON TT_PXF.FILMAT+TT_PXF.CODMAT = TT_PRO.FILMAT+TT_PRO.CODMAT
LEFT JOIN TT_PRE ON  TT_PRE.FILMAT+TT_PRE.CODMAT = TT_PRO.FILMAT+TT_PRO.CODMAT 
LEFT JOIN TT_GRA ON TT_GRA.REFPRO = REPLACE(TT_PRO.REFBAS, '.', '')
LEFT JOIN TD_DEP ON TD_DEP.CODTAB = TT_PRO.DEPART
LEFT JOIN GRANDE_GRUPO GG ON GG.TT_PRO_DEPART = TT_PRO.DEPART AND GG.TT_PRO_COD_CLASS1 = TT_PRO.CLASS1
WHERE TD_DEP.DESDEP NOT IN ( 'ARMACOES','NOMINATION')
--AND TT_PRO.FILMAT+TT_PRO.CODMAT =  '00127518'
--AND TT_PRO.DESMAT LIKE '%PULSEIRA%'

---------------------------------------------------------

/*
BEGIN TRAN

UPDATE PRODUTO_TMP
SET GRUPO = 'DIV'
WHERE GRUPO = ''

COMMIT
*/