USE ROSARIO
GO

/*
DROP TABLE TT_CLI_NEW

SELECT * INTO TT_CLI_NEW FROM (SELECT * FROM TT_CLI WHERE FILCLI + CODCLI IN( SELECT FILCLI + CODCLI FROM TT_VEN )
UNION
SELECT * FROM TT_CLI WHERE FILCLI + CODCLI NOT IN( SELECT FILCLI + CODCLI FROM TT_VEN )
AND FLGTIP='1') TMP
*/

--SELECT * FROM TT_END

--SELECT * FROM TT_CLI_NEW

SELECT 
CASE TT_CLI_NEW.FLGTIP WHEN 0 THEN 'CLIVAR'    WHEN 1 THEN  'FORNECEDOR' END AS FLGTIP,
CASE TT_CLI_NEW.FILCLI  WHEN 'LCL' THEN 'LCH'  WHEN '001' THEN 'LMT' ELSE  TT_CLI_NEW.FILCLI END FILCLI ,
TT_CLI_NEW.NOMCLI,
TT_CLI_NEW.NUMDOC,
CASE TT_CLI_NEW.ESTCIV WHEN 1 THEN 'SOLTEIRO' WHEN 2 THEN 'CASADO' END AS ESTCIV,
CASE TT_CLI_NEW.CODSEX WHEN 1 THEN 'MASCULINO'      WHEN 2 THEN 'FEMININO' END AS CODSEX,
TT_CLI_NEW.DATOPE,
TT_CLI_NEW.DATNAS,
TT_CLI_NEW.TIPDOC,
TT_CLI_NEW.ULTNOM,
--TT_CLI_NEW.INSEST,
TT_CLI_NEW.ID_ORG,
TT_CLI_NEW.ID_EST,
TT_SPC.E_MAIL,
TT_END.CODPAI,
TT_END.CODCEP + TT_END.CODLOG AS CEP,
TT_END.CODCID,
TT_END.NOMCID,
TT_END.SIGEST,
TT_END.ENDERE,
TT_END.NUMERO,
TT_END.COMPLE,
TT_END.BAIRRO,
TT_END.CODDDD,
TT_END.NUMFON,
TT_END.NUMFAX,
TT_CLI_NEW.OBSOUT
FROM TT_CLI_NEW
LEFT JOIN TT_END ON TT_CLI_NEW.CODCLI = TT_END.CODCLI AND TT_CLI_NEW.FILCLI = TT_END.FILCLI 
LEFT JOIN TT_SPC ON TT_SPC.CODCLI = TT_CLI_NEW.CODCLI  AND TT_CLI_NEW.FILCLI = TT_SPC.FILCLI
--WHERE TT_CLI_NEW.FILCLI = '001'
