truncate table SLVMOVC
truncate table SLVSER
truncate table SLVSERE
truncate table slvmovi
truncate table slvratcc
truncate table slvsere
truncate table slvinteg
truncate table slvripi
truncate table slvricmi
truncate table cptlog
