--OLD

/*
USE ROSARIO
GO

SELECT LEFT(GRUPO,3) AS GRUPOSEQ, ROW_NUMBER() OVER(PARTITION BY GRUPO ORDER BY GRUPO ASC) AS Row, *
INTO PRODUTO_TMP2
FROM PRODUTO_TMP
WHERE GRUPO IS  NOT NULL 

SELECT 
CASE LEN(GRUPOSEQ) WHEN  2 THEN GRUPOSEQ+cast(replicate('0', 6-len(ROW))as varchar) + cast((ROW) as varchar) 
ELSE GRUPOSEQ+cast(replicate('0', 5-len(ROW))as varchar) + cast((ROW) as varchar)  END AS CPROS , *
INTO PRODUTO_TMP3
FROM PRODUTO_TMP2
ORDER BY GRUPOSEQ ASC

DROP TABLE PRODUTO_TMP
DROP TABLE PRODUTO_TMP2
GO

SP_RENAME PRODUTO_TMP3, PRODUTO_TMP

SELECT * FROM PRODUTO_TMP
*/


/***************************************************************/

--ATUAL

USE ROSARIO
GO

SELECT LEFT(GRUPO,3) AS GRUPOSEQ, ROW_NUMBER() OVER(PARTITION BY GRUPO ORDER BY GRUPO ASC) AS Row, *
INTO PRODUTO_TMP2
FROM PRODUTO_TMP
WHERE GRUPO IS  NOT NULL 

SELECT 
GRUPOSEQ+cast(replicate('0', 5-len(ROW))as varchar) + cast((ROW) as varchar)  AS CPROS , *
INTO PRODUTO_TMP3
FROM PRODUTO_TMP2
ORDER BY GRUPOSEQ ASC

SELECT * FROM PRODUTO_TMP3

DROP TABLE PRODUTO_TMP
DROP TABLE PRODUTO_TMP2
GO

SP_RENAME PRODUTO_TMP3, PRODUTO_TMP

SELECT * FROM PRODUTO_TMP