USE ROSARIO
GO
--SELECT * FROM ROSARIO..PRODUTO_TMP
--SELECT * FROM ROSARIO..SLJCOMPO_TMP
--SELECT * FROM ROSARIO_ERP..SLJPRO_RR

SELECT 
P.GRUPO+REFBAS AS CPROS,
C.DESC2_MATS AS MATS,
C.DESC2_QTDS AS QUANTIDADE,
C.DESC2_PESO AS PESO,
'GEM' AS CGRUS
FROM PRODUTO_TMP P
JOIN SLJCOMPO_TMP C ON C.CPROS_MATS = P.FILMAT_CODMAT
WHERE C.DESC2_MATS IS NOT NULL

