begin tran
insert into ACORDO01
(EMPRESA,N_NUMERO,PARCELA,PARCIAL,NUMPRES,TIPO,VENCIMENTO,
PRINCIPAL,CORRECAO,JUROS,MULTA,HONORARIO,DTACORDO,VENC_ACORDO,
CONTRATO,DTPAGTO,CONTA,DTPRCONTA,PGTO_DC,RECIBO,DTPLANILHA,
ULTIMO,ATENDENTE,DISPONIVEL,DTEMISSAO,DAC,REPASSE,CARTORIO,
VLR_PARCELA,FAIXA,FILIAL,CD_PRODUTO,DT_PREST_PREVIS,
DT_REAPRESENTAC,DT_ENVIO,DT_CHEQUE_DEVOL,DT_ACORD_CANCEL,
VR_PAGAMENTO,CD_ALINEA,CD_FILIAL_ACORD,TX_HONO_CREDIC,DT_RETORN_CREDI,
IND_D_C_F,CD_BANCO,CD_AGENCIA,CD_CONTA,DT_BOM_PARA,NR_SERIE_RECIBO,
TX_DESCONTO,TX_HONORARIO,VR_PG_DINHEIRO,VR_PG_OP,NR_OP,VR_PG_CHEQUE,
OBSERVACAO,DT_VENCTO_ORIG,DT_VENCTO_ALTER,DT_CANCELADO,VR_TX_BOLETO,
VR_DESCONTO,CD_CART_BOLETO,CD_BARRA,DT_EMISSAO_BOL,NR_BOLETO,CD_EXCECAO,
QT_DIAS_ATRASO,TX_JUROS,TX_MULTA,QT_PARCELAS,VR_DESPESA,CD_SIT_ACORDO,
CD_DECISAO_ACOR,NR_ACORDO,NR_DOC_ACORDO,VR_AJUIZADO,VR_NOTIFICADO)


select EMPRESA,N_NUMERO,PARCELA,PARCIAL,NUMPRES,TIPO,VENCIMENTO,
PRINCIPAL,CORRECAO,JUROS,MULTA,HONORARIO,DTACORDO,VENC_ACORDO,
CONTRATO,DTPAGTO,CONTA,DTPRCONTA,PGTO_DC,RECIBO,DTPLANILHA,
ULTIMO,ATENDENTE,DISPONIVEL,DTEMISSAO,DAC,REPASSE,CARTORIO,
VLR_PARCELA,FAIXA,FILIAL,CD_PRODUTO,DT_PREST_PREVIS,
DT_REAPRESENTAC,DT_ENVIO,DT_CHEQUE_DEVOL,DT_ACORD_CANCEL,
VR_PAGAMENTO,CD_ALINEA,CD_FILIAL_ACORD,TX_HONO_CREDIC,DT_RETORN_CREDI,
IND_D_C_F,CD_BANCO,CD_AGENCIA,CD_CONTA,DT_BOM_PARA,NR_SERIE_RECIBO,
TX_DESCONTO,TX_HONORARIO,VR_PG_DINHEIRO,VR_PG_OP,NR_OP,VR_PG_CHEQUE,
OBSERVACAO,DT_VENCTO_ORIG,DT_VENCTO_ALTER,DT_CANCELADO,VR_TX_BOLETO,
VR_DESCONTO,CD_CART_BOLETO,CD_BARRA,DT_EMISSAO_BOL,NR_BOLETO,CD_EXCECAO,
QT_DIAS_ATRASO,TX_JUROS,TX_MULTA,QT_PARCELAS,VR_DESPESA,CD_SIT_ACORDO,
CD_DECISAO_ACOR,NR_ACORDO,NR_DOC_ACORDO,VR_AJUIZADO,VR_NOTIFICADO

from ACORDO01

where EMPRESA = 105 and N_NUMERO = 21271486

commit