use LOPRODUC

select count(1)
from TBFLYTEL
where DATEDIFF(DAY,DATA,GETDATE()) >  = 60

select count(1)
from [192.168.0.14].[lofinasa].[cadcontr]
where DATEDIFF(DAY,DATA,GETDATE()) >  = 60


select *
from  [192.168.0.44].neo_espelho.dbo.contratos


USE LOFINASA
SELECT TOP 10 CAD.CL_CIC
FROM CADCONTR AS CAD
LEFT JOIN  [192.168.0.44].neo_espelho.dbo.DEVEDORES AS NEO
ON CAST(LTRIM(RTRIM(NEO.NUMEROCGCCPF)) AS NUMERIC(15) )= CAST(LTRIM(RTRIM(CAD.CL_CIC)) AS NUMERIC(15))
WHERE LEN(LTRIM(RTRIM(NEO.NUMEROCGCCPF))) > 0
AND NEO.NUMEROCGCCPF IS NULL

SELECT	COUNT(1)FROM [192.168.0.44].neo_espelho.dbo.DEVEDORES AS NEO

SELECT RECNUM, CL_CIC,C_DAT
FROM CADCONTR 
--WHERE CAST(LTRIM(RTRIM(CL_CIC)) AS NUMERIC)= 0
 WHERE ISNUMERIC(cl_cic) = 0

BEGIN TRAN
UPDATE CADCONTR
SET CL_CIC = '80338874000192'
WHERE  RECNUM = 488343
COMMIT

SELECT *
FROM [192.168.0.44].neo_espelho.dbo.DEVEDORES AS NEO
--WHERE LEN(LTRIM(RTRIM(NEO.NUMEROCGCCPF)))= 0
WHERE ISNUMERIC(NEO.NUMEROCGCCPF) = 0

UPDATE [192.168.0.44].neo_espelho.dbo.DEVEDORES
SET	   NUMEROCGCCPF = '11111111111'
WHERE  NumeroContrato = '1676188220'

UPDATE [192.168.0.44].neo_espelho.dbo.DEVEDORES
SET	   NUMEROCGCCPF = '11111111112'
WHERE  NumeroContrato = '00000000000001'


SELECT TOP 1 * FROM [192.168.0.44].neo_espelho.dbo.DEVEDORES AS NEO WHERE 
SELECT * FROM [192.168.0.44].neo_espelho.dbo.DEVEDORES AS NEO 

WHERE TIPOPESSOA = 'J'
USE LOFINASA
SELECT TOP 10 CAD.CL_CIC
FROM CADCONTR AS CAD



USE consulta
INSERT INTO CPF_DW
SELECT CL_CIC FROM lofinasa.dbo.CADCONTR 

USE consulta
INSERT INTO CPF_NEO
SELECT NUMEROCGCCPF FROM [192.168.0.44].neo_espelho.dbo.DEVEDORES


SELECT DW.CPF_DW
FROM CPF_DW AS DW
LEFT JOIN  CPF_NEO AS NEO
ON DW.CPF_DW = NEO.CPF_NEO 
WHERE  NEO.CPF_NEO IS NULL

SELECT NEO.CPF_NEO
FROM CPF_DW AS DW
RIGHT JOIN  CPF_NEO AS NEO
ON DW.CPF_DW = NEO.CPF_NEO 
WHERE  DW.CPF_DW IS NULL


SELECT DW.CPF_DW
FROM CPF_DW AS DW
INNER JOIN  CPF_NEO AS NEO
ON DW.CPF_DW = NEO.CPF_NEO 
WHERE  NEO.CPF_NEO IS NULL






