--ALTERAR COLUNA EM UMA TABELA EXISTENTE
ALTER TABLE fstcampo ALTER COLUMN RESUMOS CHAR(40)

--ADD COLUNA EM UMA TABELA EXISTENTE
ALTER TABLE fstcampo ADD COLUNA CHAR(10) NOT NULL DEFAULT''

--ALTERAR COLUNA EM UMA TABELA EXISTENTE  TABELA GRANDE
ALTER TABLE sljgdmi ALTER COLUMN cidas CHAR(30)

--CRIAR INDICE
CREATE INDEX IX_TESTE ON fstcampo(COLUNA)

INSERT INTO fstcampo (COLUNA) VALUES ('A')

DROP INDEX IX_TESTE ON fstcampo

select * from fstcampo

INSERT INTO fstcampo (COLUNA) VALUES ('C')

UPDATE fstcampo 
SET COLUNA = 'A'
WHERE COLUNA = 'C'

DELETE FROM fstcampo
WHERE COLUNA = 'A'