--CHECA DE EXISTE NULO
SELECT * FROM SLJESTPE
WHERE chksubn IS NULL

--CASO EXISTA EXECUTAR:
UPDATE SLJESTPE
SET chksubn = 0
WHERE chksubn IS NULL

--ALTERA DE NULO PARA NÃO NULO
ALTER TABLE SLJESTPE ALTER COLUMN chksubn BIT NOT NULL

--VERIFICA SE EXISTE TIPO BIT NULO
SELECT 
T.NAME AS 'TYPE', 
OBJECT_NAME(C.object_id) AS 'TABLE', 
C.name AS 'COLUMN', 
C.IS_NULLABLE
FROM SYS.columns C
JOIN SYS.types T ON T.user_type_id = C.user_type_id
WHERE C.user_type_id = 104
AND c.is_nullable = 1
AND OBJECT_NAME(C.object_id) NOT LIKE '%SYS%'
