ECHO INICIANDO Transferencia>C:\OUTTRANSF.TXT
ECHO|DATE/T>>C:\OUTTRANSF.TXT
ECHO|TIME/T>>C:\OUTTRANSF.TXT

cd\ 

XCOPY C:\* D:\Teste /s


ECHO FIM DA Transferencia>>C:\OUTTRANSF.TXT
ECHO|DATE/T>>C:\OUTTRANSF.TXT
ECHO|TIME/T>>C:\OUTTRANSF.TXT

