USE [InMemoryDB]
go

--GarbageCollector

--TransactionalLogInMemory

--	DROP TABLE InMemoryTable
--GO
--	DROP TABLE InDiskTables

CREATE TABLE InDiskTables 
(
	[c1] INT NOT NULL,
	[c2] CHAR(150) NOT NULL	
) 
GO
CREATE UNIQUE NONCLUSTERED INDEX idxncl_indisktables_c1
ON InDiskTables (c1)

BEGIN TRANSACTION
DECLARE @i INT = 0
WHILE (@i < 150)
	BEGIN
		INSERT INTO InDiskTables VALUES (@i, REPLICATE('1',100))
		SET @i = @i + 1
	END
COMMIT TRANSACTION

SELECT *
FROM sys.partitions 
WHERE OBJECT_ID = OBJECT_ID('InDiskTables')

SELECT *
FROM sys.fn_dblog(NULL,NULL)
WHERE PartitionId = 72057594040287232 
	OR PartitionId = 72057594040352768 

GO

CREATE TABLE InMemoryTable
(
	[c1] INT NOT NULL PRIMARY KEY NONCLUSTERED HASH WITH(BUCKET_COUNT = 1000000),
	[c2] CHAR(150) NOT NULL	
) WITH (MEMORY_OPTIMIZED = ON, DURABILITY = SCHEMA_AND_DATA)
GO

BEGIN TRANSACTION
DECLARE @i INT = 0
WHILE (@i < 150)
	BEGIN
		INSERT INTO InMemoryTable VALUES (@i, REPLICATE('1',100))
		SET @i = @i + 1
	END
COMMIT TRANSACTION

SELECT *
FROM sys.fn_dblog(NULL,NULL)
