/****** Object:  Default [DF__CONFIGURA__vlMax__4BC21919]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[CONFIGURACAOCREDITOIPTU] ADD  DEFAULT ((20)) FOR [vlMaximoAbatimentoIPTU]
GO
/****** Object:  Default [DF__INCONSIST__inSit__41049384]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[INCONSISTENCIAFISCALIZACAO] ADD  DEFAULT ('P') FOR [inSituacao]
GO
/****** Object:  Default [DF__INSCRICAO__inPro__2EB0D91F]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[INSCRICAOMUNICIPAL] ADD  DEFAULT ((0)) FOR [inProvisorio]
GO
/****** Object:  Default [DF__ISSRLCRen__Tipo___75435199]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[ISSRLCRen_Leg_Contribuinte] ADD  DEFAULT ((0)) FOR [Tipo_Industria]
GO
/****** Object:  Default [DF__ISSRLCRen__Tipo___763775D2]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[ISSRLCRen_Leg_Contribuinte] ADD  DEFAULT ((0)) FOR [Tipo_Comercio]
GO
/****** Object:  Default [DF__ISSRLCRen__Tipo___772B9A0B]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[ISSRLCRen_Leg_Contribuinte] ADD  DEFAULT ((0)) FOR [Tipo_Prestador]
GO
/****** Object:  Default [DF__ISSRLCRen__Tipo___781FBE44]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[ISSRLCRen_Leg_Contribuinte] ADD  DEFAULT ((0)) FOR [Tipo_Outros]
GO
/****** Object:  Default [DF__ISSRNCRen__Tipo___00B50445]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[ISSRNCRen_Contribuinte] ADD  CONSTRAINT [DF__ISSRNCRen__Tipo___00B50445]  DEFAULT ((0)) FOR [Tipo_Industria]
GO
/****** Object:  Default [DF__ISSRNCRen__Tipo___01A9287E]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[ISSRNCRen_Contribuinte] ADD  CONSTRAINT [DF__ISSRNCRen__Tipo___01A9287E]  DEFAULT ((0)) FOR [Tipo_Comercio]
GO
/****** Object:  Default [DF__ISSRNCRen__Tipo___029D4CB7]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[ISSRNCRen_Contribuinte] ADD  CONSTRAINT [DF__ISSRNCRen__Tipo___029D4CB7]  DEFAULT ((0)) FOR [Tipo_Prestador]
GO
/****** Object:  Default [DF__ISSRNCRen__Tipo___039170F0]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[ISSRNCRen_Contribuinte] ADD  CONSTRAINT [DF__ISSRNCRen__Tipo___039170F0]  DEFAULT ((0)) FOR [Tipo_Outros]
GO
/****** Object:  Default [DF__ISSRNCRen__inSta__04859529]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[ISSRNCRen_Contribuinte] ADD  CONSTRAINT [DF__ISSRNCRen__inSta__04859529]  DEFAULT ((0)) FOR [inStatus]
GO
/****** Object:  Default [DF__PERMISSAO__inGer__7C9A5A9E]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[PERMISSAOUSUARIONFE] ADD  DEFAULT ('0') FOR [inGerarCartaCorrecao]
GO
/****** Object:  Default [DF__PERMISSAO__inGer__7D8E7ED7]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[PERMISSAOUSUARIONFE] ADD  DEFAULT ('0') FOR [inGerarArquivoRetorno]
GO
/****** Object:  Default [DF__PREFEITUR__nrAno__3469B275]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[PREFEITURA] ADD  DEFAULT ((2000)) FOR [nrAnoInicialContrCivil]
GO
/****** Object:  Default [DF__PREFEITUR__nrDia__6AC5C326]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[PREFEITURA] ADD  DEFAULT ((15)) FOR [nrDiaMaxEmiEstimExcedente]
GO
/****** Object:  Default [DF__PREFEITUR__nrMes__6BB9E75F]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[PREFEITURA] ADD  DEFAULT ((1)) FOR [nrMesMaxEmiEstimExcedente]
GO
/****** Object:  Check [chkOnzeDezessete]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[CONFIGBOLETOBANCARIO]  WITH CHECK ADD  CONSTRAINT [chkOnzeDezessete] CHECK  (([qtNossoNumero]=(17) OR [qtNossoNumero]=(11)))
GO
ALTER TABLE [dbo].[CONFIGBOLETOBANCARIO] CHECK CONSTRAINT [chkOnzeDezessete]
GO
/****** Object:  Check [chknrDiaMaxExercicioAnterior]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[PREFEITURA]  WITH NOCHECK ADD  CONSTRAINT [chknrDiaMaxExercicioAnterior] CHECK  (([nrDiaMaxExercicioAnterior]=(31) OR [nrDiaMaxExercicioAnterior]=(30) OR [nrDiaMaxExercicioAnterior]=(29) OR [nrDiaMaxExercicioAnterior]=(28) OR [nrDiaMaxExercicioAnterior]=(27) OR [nrDiaMaxExercicioAnterior]=(26) OR [nrDiaMaxExercicioAnterior]=(25) OR [nrDiaMaxExercicioAnterior]=(24) OR [nrDiaMaxExercicioAnterior]=(23) OR [nrDiaMaxExercicioAnterior]=(22) OR [nrDiaMaxExercicioAnterior]=(21) OR [nrDiaMaxExercicioAnterior]=(20) OR [nrDiaMaxExercicioAnterior]=(19) OR [nrDiaMaxExercicioAnterior]=(18) OR [nrDiaMaxExercicioAnterior]=(17) OR [nrDiaMaxExercicioAnterior]=(16) OR [nrDiaMaxExercicioAnterior]=(15) OR [nrDiaMaxExercicioAnterior]=(14) OR [nrDiaMaxExercicioAnterior]=(13) OR [nrDiaMaxExercicioAnterior]=(12) OR [nrDiaMaxExercicioAnterior]=(11) OR [nrDiaMaxExercicioAnterior]=(10) OR [nrDiaMaxExercicioAnterior]=(9) OR [nrDiaMaxExercicioAnterior]=(8) OR [nrDiaMaxExercicioAnterior]=(7) OR [nrDiaMaxExercicioAnterior]=(6) OR [nrDiaMaxExercicioAnterior]=(5) OR [nrDiaMaxExercicioAnterior]=(4) OR [nrDiaMaxExercicioAnterior]=(3) OR [nrDiaMaxExercicioAnterior]=(2) OR [nrDiaMaxExercicioAnterior]=(1)))
GO
ALTER TABLE [dbo].[PREFEITURA] CHECK CONSTRAINT [chknrDiaMaxExercicioAnterior]
GO
/****** Object:  Check [chknrMesMaxExercicioAnterior]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[PREFEITURA]  WITH NOCHECK ADD  CONSTRAINT [chknrMesMaxExercicioAnterior] CHECK  (([nrMesMaxExercicioAnterior]=(12) OR [nrMesMaxExercicioAnterior]=(11) OR [nrMesMaxExercicioAnterior]=(10) OR [nrMesMaxExercicioAnterior]=(9) OR [nrMesMaxExercicioAnterior]=(8) OR [nrMesMaxExercicioAnterior]=(7) OR [nrMesMaxExercicioAnterior]=(6) OR [nrMesMaxExercicioAnterior]=(5) OR [nrMesMaxExercicioAnterior]=(4) OR [nrMesMaxExercicioAnterior]=(3) OR [nrMesMaxExercicioAnterior]=(2) OR [nrMesMaxExercicioAnterior]=(1)))
GO
ALTER TABLE [dbo].[PREFEITURA] CHECK CONSTRAINT [chknrMesMaxExercicioAnterior]
GO
/****** Object:  ForeignKey [fkAGENDADORTAREFALOG_AGENDADORTAREFA]    Script Date: 04/02/2013 11:32:18 ******/
ALTER TABLE [dbo].[AGENDADORTAREFALOG]  WITH CHECK ADD  CONSTRAINT [fkAGENDADORTAREFALOG_AGENDADORTAREFA] FOREIGN KEY([cdAgendadorTarefa])
REFERENCES [dbo].[AGENDADORTAREFA] ([cdAgendadorTarefa])
GO
ALTER TABLE [dbo].[AGENDADORTAREFALOG] CHECK CONSTRAINT [fkAGENDADORTAREFALOG_AGENDADORTAREFA]
GO
/****** Object:  ForeignKey [fkAGENDADORTAREFALOG_LOGERROS]    Script Date: 04/02/2013 11:32:18 ******/
ALTER TABLE [dbo].[AGENDADORTAREFALOG]  WITH CHECK ADD  CONSTRAINT [fkAGENDADORTAREFALOG_LOGERROS] FOREIGN KEY([cdLogErro])
REFERENCES [dbo].[LOGERROS] ([cdEvento])
GO
ALTER TABLE [dbo].[AGENDADORTAREFALOG] CHECK CONSTRAINT [fkAGENDADORTAREFALOG_LOGERROS]
GO
/****** Object:  ForeignKey [fkAGRUCONTRAESCOLAR_ATIVIDADE]    Script Date: 04/02/2013 11:32:18 ******/
ALTER TABLE [dbo].[AGRUPAMENTOCONTRATOESCOLAR]  WITH CHECK ADD  CONSTRAINT [fkAGRUCONTRAESCOLAR_ATIVIDADE] FOREIGN KEY([cdAtividade])
REFERENCES [dbo].[ATIVIDADE] ([cdAtividade])
GO
ALTER TABLE [dbo].[AGRUPAMENTOCONTRATOESCOLAR] CHECK CONSTRAINT [fkAGRUCONTRAESCOLAR_ATIVIDADE]
GO
/****** Object:  ForeignKey [fkAGRUCONTRATOESCOLAR_PESSOA]    Script Date: 04/02/2013 11:32:18 ******/
ALTER TABLE [dbo].[AGRUPAMENTOCONTRATOESCOLAR]  WITH CHECK ADD  CONSTRAINT [fkAGRUCONTRATOESCOLAR_PESSOA] FOREIGN KEY([cdPessoa])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[AGRUPAMENTOCONTRATOESCOLAR] CHECK CONSTRAINT [fkAGRUCONTRATOESCOLAR_PESSOA]
GO
/****** Object:  ForeignKey [fkATIVIDADE_GRUPOATIVIDADE]    Script Date: 04/02/2013 11:32:18 ******/
ALTER TABLE [dbo].[ATIVIDADE]  WITH CHECK ADD  CONSTRAINT [fkATIVIDADE_GRUPOATIVIDADE] FOREIGN KEY([cdGrupoAtividade])
REFERENCES [dbo].[GRUPOATIVIDADE] ([cdGrupoAtividade])
GO
ALTER TABLE [dbo].[ATIVIDADE] CHECK CONSTRAINT [fkATIVIDADE_GRUPOATIVIDADE]
GO
/****** Object:  ForeignKey [fkATIVIDADE_SEGMENTOATIVIDADE]    Script Date: 04/02/2013 11:32:18 ******/
ALTER TABLE [dbo].[ATIVIDADE]  WITH CHECK ADD  CONSTRAINT [fkATIVIDADE_SEGMENTOATIVIDADE] FOREIGN KEY([cdSegmentoAtividade])
REFERENCES [dbo].[SEGMENTOATIVIDADE] ([cdSegmentoAtividade])
GO
ALTER TABLE [dbo].[ATIVIDADE] CHECK CONSTRAINT [fkATIVIDADE_SEGMENTOATIVIDADE]
GO
/****** Object:  ForeignKey [fkAUTORIZACAOAIDF_PESCANCEL]    Script Date: 04/02/2013 11:32:18 ******/
ALTER TABLE [dbo].[AUTORIZACAOAIDF]  WITH CHECK ADD  CONSTRAINT [fkAUTORIZACAOAIDF_PESCANCEL] FOREIGN KEY([cdPessoaCancelamento])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[AUTORIZACAOAIDF] CHECK CONSTRAINT [fkAUTORIZACAOAIDF_PESCANCEL]
GO
/****** Object:  ForeignKey [fkAUTORIZACAOAIDF_PESFISCAL]    Script Date: 04/02/2013 11:32:18 ******/
ALTER TABLE [dbo].[AUTORIZACAOAIDF]  WITH CHECK ADD  CONSTRAINT [fkAUTORIZACAOAIDF_PESFISCAL] FOREIGN KEY([cdPessoaFiscal])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[AUTORIZACAOAIDF] CHECK CONSTRAINT [fkAUTORIZACAOAIDF_PESFISCAL]
GO
/****** Object:  ForeignKey [fkAUTORIZAIDF_ENDERECO]    Script Date: 04/02/2013 11:32:18 ******/
ALTER TABLE [dbo].[AUTORIZACAOAIDF]  WITH CHECK ADD  CONSTRAINT [fkAUTORIZAIDF_ENDERECO] FOREIGN KEY([cdEndereco])
REFERENCES [dbo].[ENDERECO] ([cdEndereco])
GO
ALTER TABLE [dbo].[AUTORIZACAOAIDF] CHECK CONSTRAINT [fkAUTORIZAIDF_ENDERECO]
GO
/****** Object:  ForeignKey [fkAUTORIZAIDF_PESSOA]    Script Date: 04/02/2013 11:32:18 ******/
ALTER TABLE [dbo].[AUTORIZACAOAIDF]  WITH CHECK ADD  CONSTRAINT [fkAUTORIZAIDF_PESSOA] FOREIGN KEY([cdPessoa])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[AUTORIZACAOAIDF] CHECK CONSTRAINT [fkAUTORIZAIDF_PESSOA]
GO
/****** Object:  ForeignKey [fkAUTORIZAIDF_PESSOAJURI]    Script Date: 04/02/2013 11:32:18 ******/
ALTER TABLE [dbo].[AUTORIZACAOAIDF]  WITH CHECK ADD  CONSTRAINT [fkAUTORIZAIDF_PESSOAJURI] FOREIGN KEY([cdPessoaGrafica])
REFERENCES [dbo].[PESSOAJURIDICA] ([cdPessoa])
GO
ALTER TABLE [dbo].[AUTORIZACAOAIDF] CHECK CONSTRAINT [fkAUTORIZAIDF_PESSOAJURI]
GO
/****** Object:  ForeignKey [fkAUTORIZAIDF_SERIENOTAFISCAL]    Script Date: 04/02/2013 11:32:18 ******/
ALTER TABLE [dbo].[AUTORIZACAOAIDF]  WITH CHECK ADD  CONSTRAINT [fkAUTORIZAIDF_SERIENOTAFISCAL] FOREIGN KEY([cdSerieAutorizada])
REFERENCES [dbo].[SERIENOTAFISCAL] ([cdSerieNotaFiscal])
GO
ALTER TABLE [dbo].[AUTORIZACAOAIDF] CHECK CONSTRAINT [fkAUTORIZAIDF_SERIENOTAFISCAL]
GO
/****** Object:  ForeignKey [fkAUTORIZAIDF_SERIENOTAFISCAL2]    Script Date: 04/02/2013 11:32:18 ******/
ALTER TABLE [dbo].[AUTORIZACAOAIDF]  WITH CHECK ADD  CONSTRAINT [fkAUTORIZAIDF_SERIENOTAFISCAL2] FOREIGN KEY([cdSerieSolicitacao])
REFERENCES [dbo].[SERIENOTAFISCAL] ([cdSerieNotaFiscal])
GO
ALTER TABLE [dbo].[AUTORIZACAOAIDF] CHECK CONSTRAINT [fkAUTORIZAIDF_SERIENOTAFISCAL2]
GO
/****** Object:  ForeignKey [fkAUTORIZACAODOCUMENTORECIBO_INSCRICAOMUNICIPAL]    Script Date: 04/02/2013 11:32:18 ******/
ALTER TABLE [dbo].[AUTORIZACAODOCUMENTORECIBO]  WITH CHECK ADD  CONSTRAINT [fkAUTORIZACAODOCUMENTORECIBO_INSCRICAOMUNICIPAL] FOREIGN KEY([cdInscricaoMunicipal])
REFERENCES [dbo].[INSCRICAOMUNICIPAL] ([cdInscricaoMunicipal])
GO
ALTER TABLE [dbo].[AUTORIZACAODOCUMENTORECIBO] CHECK CONSTRAINT [fkAUTORIZACAODOCUMENTORECIBO_INSCRICAOMUNICIPAL]
GO
/****** Object:  ForeignKey [fkAUTORIZACAODOCUMENTORECIBO_USUARIO01]    Script Date: 04/02/2013 11:32:18 ******/
ALTER TABLE [dbo].[AUTORIZACAODOCUMENTORECIBO]  WITH CHECK ADD  CONSTRAINT [fkAUTORIZACAODOCUMENTORECIBO_USUARIO01] FOREIGN KEY([cdUsuarioInclusao])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[AUTORIZACAODOCUMENTORECIBO] CHECK CONSTRAINT [fkAUTORIZACAODOCUMENTORECIBO_USUARIO01]
GO
/****** Object:  ForeignKey [fkAUTORIZACAODOCUMENTORECIBO_USUARIO02]    Script Date: 04/02/2013 11:32:18 ******/
ALTER TABLE [dbo].[AUTORIZACAODOCUMENTORECIBO]  WITH CHECK ADD  CONSTRAINT [fkAUTORIZACAODOCUMENTORECIBO_USUARIO02] FOREIGN KEY([cdUsuarioExclusao])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[AUTORIZACAODOCUMENTORECIBO] CHECK CONSTRAINT [fkAUTORIZACAODOCUMENTORECIBO_USUARIO02]
GO
/****** Object:  ForeignKey [fkAUTORIZACAOFORAORD_SERIENTFI]    Script Date: 04/02/2013 11:32:18 ******/
ALTER TABLE [dbo].[AUTORIZACAOFORAORDEM]  WITH CHECK ADD  CONSTRAINT [fkAUTORIZACAOFORAORD_SERIENTFI] FOREIGN KEY([cdSerieNotaFiscal])
REFERENCES [dbo].[SERIENOTAFISCAL] ([cdSerieNotaFiscal])
GO
ALTER TABLE [dbo].[AUTORIZACAOFORAORDEM] CHECK CONSTRAINT [fkAUTORIZACAOFORAORD_SERIENTFI]
GO
/****** Object:  ForeignKey [fkAUTORIZACAOFORAORDEM_PESSOA]    Script Date: 04/02/2013 11:32:18 ******/
ALTER TABLE [dbo].[AUTORIZACAOFORAORDEM]  WITH CHECK ADD  CONSTRAINT [fkAUTORIZACAOFORAORDEM_PESSOA] FOREIGN KEY([cdPessoa])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[AUTORIZACAOFORAORDEM] CHECK CONSTRAINT [fkAUTORIZACAOFORAORDEM_PESSOA]
GO
/****** Object:  ForeignKey [fkAUTORIZACAOFORAORDEM_PESSOA2]    Script Date: 04/02/2013 11:32:18 ******/
ALTER TABLE [dbo].[AUTORIZACAOFORAORDEM]  WITH CHECK ADD  CONSTRAINT [fkAUTORIZACAOFORAORDEM_PESSOA2] FOREIGN KEY([cdPessoaFiscalSituacao])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[AUTORIZACAOFORAORDEM] CHECK CONSTRAINT [fkAUTORIZACAOFORAORDEM_PESSOA2]
GO
/****** Object:  ForeignKey [fkCARTACORRECAO_NOTAFISCAL]    Script Date: 04/02/2013 11:32:18 ******/
ALTER TABLE [dbo].[CARTACORRECAO]  WITH CHECK ADD  CONSTRAINT [fkCARTACORRECAO_NOTAFISCAL] FOREIGN KEY([cdNotaFiscal])
REFERENCES [dbo].[NOTAFISCAL] ([cdNotaFiscal])
GO
ALTER TABLE [dbo].[CARTACORRECAO] CHECK CONSTRAINT [fkCARTACORRECAO_NOTAFISCAL]
GO
/****** Object:  ForeignKey [fkCDCPAGAMENTO_PAGAMENTO]    Script Date: 04/02/2013 11:32:18 ******/
ALTER TABLE [dbo].[CDCPAGAMENTO]  WITH CHECK ADD  CONSTRAINT [fkCDCPAGAMENTO_PAGAMENTO] FOREIGN KEY([cdPagamento])
REFERENCES [dbo].[PAGAMENTO] ([cdPagamento])
GO
ALTER TABLE [dbo].[CDCPAGAMENTO] CHECK CONSTRAINT [fkCDCPAGAMENTO_PAGAMENTO]
GO
/****** Object:  ForeignKey [fkCHAVEAUTENTICACAOREQUISICAO_REQUISICAOAUTORIZACAONFE]    Script Date: 04/02/2013 11:32:18 ******/
ALTER TABLE [dbo].[CHAVEAUTENTICACAOREQUISICAO]  WITH CHECK ADD  CONSTRAINT [fkCHAVEAUTENTICACAOREQUISICAO_REQUISICAOAUTORIZACAONFE] FOREIGN KEY([cdRequisicaoAutorizacaoNfe])
REFERENCES [dbo].[REQUISICAOAUTORIZACAONFE] ([cdRequisicaoAutorizacaoNfe])
GO
ALTER TABLE [dbo].[CHAVEAUTENTICACAOREQUISICAO] CHECK CONSTRAINT [fkCHAVEAUTENTICACAOREQUISICAO_REQUISICAOAUTORIZACAONFE]
GO
/****** Object:  ForeignKey [fkCHAVEAUTENTICACAOREQUISICAO_USUARIO01]    Script Date: 04/02/2013 11:32:18 ******/
ALTER TABLE [dbo].[CHAVEAUTENTICACAOREQUISICAO]  WITH CHECK ADD  CONSTRAINT [fkCHAVEAUTENTICACAOREQUISICAO_USUARIO01] FOREIGN KEY([cdUsuarioInclusao])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[CHAVEAUTENTICACAOREQUISICAO] CHECK CONSTRAINT [fkCHAVEAUTENTICACAOREQUISICAO_USUARIO01]
GO
/****** Object:  ForeignKey [fkCHAVEAUTENTICACAOREQUISICAO_USUARIO02]    Script Date: 04/02/2013 11:32:18 ******/
ALTER TABLE [dbo].[CHAVEAUTENTICACAOREQUISICAO]  WITH CHECK ADD  CONSTRAINT [fkCHAVEAUTENTICACAOREQUISICAO_USUARIO02] FOREIGN KEY([cdUsuarioDesativacao])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[CHAVEAUTENTICACAOREQUISICAO] CHECK CONSTRAINT [fkCHAVEAUTENTICACAOREQUISICAO_USUARIO02]
GO
/****** Object:  ForeignKey [fkPAGAMENTO_USUARIO]    Script Date: 04/02/2013 11:32:18 ******/
ALTER TABLE [dbo].[CODIGOPAGAMENTO]  WITH CHECK ADD  CONSTRAINT [fkPAGAMENTO_USUARIO] FOREIGN KEY([cdUsuarioReimpressao])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[CODIGOPAGAMENTO] CHECK CONSTRAINT [fkPAGAMENTO_USUARIO]
GO
/****** Object:  ForeignKey [fkPAGAMENTO_USUARIO2]    Script Date: 04/02/2013 11:32:18 ******/
ALTER TABLE [dbo].[CODIGOPAGAMENTO]  WITH CHECK ADD  CONSTRAINT [fkPAGAMENTO_USUARIO2] FOREIGN KEY([cdUsuarioDeclarante])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[CODIGOPAGAMENTO] CHECK CONSTRAINT [fkPAGAMENTO_USUARIO2]
GO
/****** Object:  ForeignKey [fkCOMPENSACAO_PESSOA]    Script Date: 04/02/2013 11:32:18 ******/
ALTER TABLE [dbo].[COMPENSACAO]  WITH CHECK ADD  CONSTRAINT [fkCOMPENSACAO_PESSOA] FOREIGN KEY([cdPessoaContribuinte])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[COMPENSACAO] CHECK CONSTRAINT [fkCOMPENSACAO_PESSOA]
GO
/****** Object:  ForeignKey [fkCOMPENSACAO_USUARIO]    Script Date: 04/02/2013 11:32:18 ******/
ALTER TABLE [dbo].[COMPENSACAO]  WITH CHECK ADD  CONSTRAINT [fkCOMPENSACAO_USUARIO] FOREIGN KEY([cdUsuario])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[COMPENSACAO] CHECK CONSTRAINT [fkCOMPENSACAO_USUARIO]
GO
/****** Object:  ForeignKey [fkCONFIGAIDF_USUARIO]    Script Date: 04/02/2013 11:32:18 ******/
ALTER TABLE [dbo].[CONFIGAIDF]  WITH CHECK ADD  CONSTRAINT [fkCONFIGAIDF_USUARIO] FOREIGN KEY([cdUsuario])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[CONFIGAIDF] CHECK CONSTRAINT [fkCONFIGAIDF_USUARIO]
GO
/****** Object:  ForeignKey [fkCONFIGBOLETOBANCARIO_BANCOS]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[CONFIGBOLETOBANCARIO]  WITH CHECK ADD  CONSTRAINT [fkCONFIGBOLETOBANCARIO_BANCOS] FOREIGN KEY([cdBanco])
REFERENCES [dbo].[BANCOS] ([cdBanco])
GO
ALTER TABLE [dbo].[CONFIGBOLETOBANCARIO] CHECK CONSTRAINT [fkCONFIGBOLETOBANCARIO_BANCOS]
GO
/****** Object:  ForeignKey [fkCONFIGBOLETOBANCARIO_USUARIO]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[CONFIGBOLETOBANCARIO]  WITH CHECK ADD  CONSTRAINT [fkCONFIGBOLETOBANCARIO_USUARIO] FOREIGN KEY([cdUsuario])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[CONFIGBOLETOBANCARIO] CHECK CONSTRAINT [fkCONFIGBOLETOBANCARIO_USUARIO]
GO
/****** Object:  ForeignKey [fkCONFIGURACAODEDUCAONOTAFISCAL_PESSOA]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[CONFIGURACAODEDUCAONOTAFISCAL]  WITH CHECK ADD  CONSTRAINT [fkCONFIGURACAODEDUCAONOTAFISCAL_PESSOA] FOREIGN KEY([cdPessoaContribuinte])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[CONFIGURACAODEDUCAONOTAFISCAL] CHECK CONSTRAINT [fkCONFIGURACAODEDUCAONOTAFISCAL_PESSOA]
GO
/****** Object:  ForeignKey [fkCONFIGURACAODEDUCAONOTAFISCAL_USUARIO01]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[CONFIGURACAODEDUCAONOTAFISCAL]  WITH CHECK ADD  CONSTRAINT [fkCONFIGURACAODEDUCAONOTAFISCAL_USUARIO01] FOREIGN KEY([cdUsuarioInclusao])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[CONFIGURACAODEDUCAONOTAFISCAL] CHECK CONSTRAINT [fkCONFIGURACAODEDUCAONOTAFISCAL_USUARIO01]
GO
/****** Object:  ForeignKey [fkCONFIGURACAODEDUCAONOTAFISCAL_USUARIO02]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[CONFIGURACAODEDUCAONOTAFISCAL]  WITH CHECK ADD  CONSTRAINT [fkCONFIGURACAODEDUCAONOTAFISCAL_USUARIO02] FOREIGN KEY([cdUsuarioEdicao])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[CONFIGURACAODEDUCAONOTAFISCAL] CHECK CONSTRAINT [fkCONFIGURACAODEDUCAONOTAFISCAL_USUARIO02]
GO
/****** Object:  ForeignKey [fkCONFIGURACAODEDUCAONOTAFISCAL_USUARIO03]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[CONFIGURACAODEDUCAONOTAFISCAL]  WITH CHECK ADD  CONSTRAINT [fkCONFIGURACAODEDUCAONOTAFISCAL_USUARIO03] FOREIGN KEY([cdUsuarioExclusao])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[CONFIGURACAODEDUCAONOTAFISCAL] CHECK CONSTRAINT [fkCONFIGURACAODEDUCAONOTAFISCAL_USUARIO03]
GO
/****** Object:  ForeignKey [fkCONFIGURACAONOTAFISCALATIVIDADE_ATIVIDADE]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[CONFIGURACAONOTAFISCALATIVIDADE]  WITH CHECK ADD  CONSTRAINT [fkCONFIGURACAONOTAFISCALATIVIDADE_ATIVIDADE] FOREIGN KEY([cdAtividade])
REFERENCES [dbo].[ATIVIDADE] ([cdAtividade])
GO
ALTER TABLE [dbo].[CONFIGURACAONOTAFISCALATIVIDADE] CHECK CONSTRAINT [fkCONFIGURACAONOTAFISCALATIVIDADE_ATIVIDADE]
GO
/****** Object:  ForeignKey [fkCONFIGURACAONOTAFISCALATIVIDADE_CONFIGURACAONOTAFISCAL]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[CONFIGURACAONOTAFISCALATIVIDADE]  WITH CHECK ADD  CONSTRAINT [fkCONFIGURACAONOTAFISCALATIVIDADE_CONFIGURACAONOTAFISCAL] FOREIGN KEY([cdConfiguracaoNotaFiscal])
REFERENCES [dbo].[CONFIGURACAONOTAFISCAL] ([cdConfiguracaoNotaFiscal])
GO
ALTER TABLE [dbo].[CONFIGURACAONOTAFISCALATIVIDADE] CHECK CONSTRAINT [fkCONFIGURACAONOTAFISCALATIVIDADE_CONFIGURACAONOTAFISCAL]
GO
/****** Object:  ForeignKey [fkCONFIGURACAONOTAFISCALPESSOA_CONFIGURACAONOTAFISCAL]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[CONFIGURACAONOTAFISCALPESSOA]  WITH CHECK ADD  CONSTRAINT [fkCONFIGURACAONOTAFISCALPESSOA_CONFIGURACAONOTAFISCAL] FOREIGN KEY([cdConfiguracaoNotaFiscal])
REFERENCES [dbo].[CONFIGURACAONOTAFISCAL] ([cdConfiguracaoNotaFiscal])
GO
ALTER TABLE [dbo].[CONFIGURACAONOTAFISCALPESSOA] CHECK CONSTRAINT [fkCONFIGURACAONOTAFISCALPESSOA_CONFIGURACAONOTAFISCAL]
GO
/****** Object:  ForeignKey [fkCONFIGURACAONOTAFISCALPESSOA_PESSOA]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[CONFIGURACAONOTAFISCALPESSOA]  WITH CHECK ADD  CONSTRAINT [fkCONFIGURACAONOTAFISCALPESSOA_PESSOA] FOREIGN KEY([cdPessoa])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[CONFIGURACAONOTAFISCALPESSOA] CHECK CONSTRAINT [fkCONFIGURACAONOTAFISCALPESSOA_PESSOA]
GO
/****** Object:  ForeignKey [fkCONTADOR_PESSOA]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[CONTADOR]  WITH CHECK ADD  CONSTRAINT [fkCONTADOR_PESSOA] FOREIGN KEY([cdPessoa])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[CONTADOR] CHECK CONSTRAINT [fkCONTADOR_PESSOA]
GO
/****** Object:  ForeignKey [fkCONTRATOESCOLAR_IMPORTACAOLANCAMENTOITENS]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[CONTRATOESCOLAR]  WITH CHECK ADD  CONSTRAINT [fkCONTRATOESCOLAR_IMPORTACAOLANCAMENTOITENS] FOREIGN KEY([cdImportacaoLancamentoItens])
REFERENCES [dbo].[IMPORTACAOLANCAMENTOITENS] ([cdImportacaoLancamentoItens])
GO
ALTER TABLE [dbo].[CONTRATOESCOLAR] CHECK CONSTRAINT [fkCONTRATOESCOLAR_IMPORTACAOLANCAMENTOITENS]
GO
/****** Object:  ForeignKey [fkCONTRATOESCOLAR_PESSOA]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[CONTRATOESCOLAR]  WITH CHECK ADD  CONSTRAINT [fkCONTRATOESCOLAR_PESSOA] FOREIGN KEY([cdPessoa])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[CONTRATOESCOLAR] CHECK CONSTRAINT [fkCONTRATOESCOLAR_PESSOA]
GO
/****** Object:  ForeignKey [fkCONTRIFISCALIZACAO_PESSOA]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[CONTRIBUINTEFISCALIZACAO]  WITH CHECK ADD  CONSTRAINT [fkCONTRIFISCALIZACAO_PESSOA] FOREIGN KEY([cdPessoa])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[CONTRIBUINTEFISCALIZACAO] CHECK CONSTRAINT [fkCONTRIFISCALIZACAO_PESSOA]
GO
/****** Object:  ForeignKey [fkCONTRIFISCALIZACAO_PESSOA2]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[CONTRIBUINTEFISCALIZACAO]  WITH CHECK ADD  CONSTRAINT [fkCONTRIFISCALIZACAO_PESSOA2] FOREIGN KEY([cdPessoaFiscal])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[CONTRIBUINTEFISCALIZACAO] CHECK CONSTRAINT [fkCONTRIFISCALIZACAO_PESSOA2]
GO
/****** Object:  ForeignKey [fkCONTRIPESSOAUSUARIO_PESSOA]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[CONTRIBUINTEPESSOAUSUARIO]  WITH CHECK ADD  CONSTRAINT [fkCONTRIPESSOAUSUARIO_PESSOA] FOREIGN KEY([cdPessoaContribuinte])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[CONTRIBUINTEPESSOAUSUARIO] CHECK CONSTRAINT [fkCONTRIPESSOAUSUARIO_PESSOA]
GO
/****** Object:  ForeignKey [fkCONTRIPESSOAUSUARIO_PESSOA2]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[CONTRIBUINTEPESSOAUSUARIO]  WITH CHECK ADD  CONSTRAINT [fkCONTRIPESSOAUSUARIO_PESSOA2] FOREIGN KEY([cdPessoaResponsavel])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[CONTRIBUINTEPESSOAUSUARIO] CHECK CONSTRAINT [fkCONTRIPESSOAUSUARIO_PESSOA2]
GO
/****** Object:  ForeignKey [fkCONTRIPESSOAUSUARIO_USUARIO]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[CONTRIBUINTEPESSOAUSUARIO]  WITH CHECK ADD  CONSTRAINT [fkCONTRIPESSOAUSUARIO_USUARIO] FOREIGN KEY([cdUsuario])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[CONTRIBUINTEPESSOAUSUARIO] CHECK CONSTRAINT [fkCONTRIPESSOAUSUARIO_USUARIO]
GO
/****** Object:  ForeignKey [fkCONTROLECOMPENSACAO_PESSOA]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[CONTROLECOMPENSACAO]  WITH CHECK ADD  CONSTRAINT [fkCONTROLECOMPENSACAO_PESSOA] FOREIGN KEY([cdPessoaContribuinte])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[CONTROLECOMPENSACAO] CHECK CONSTRAINT [fkCONTROLECOMPENSACAO_PESSOA]
GO
/****** Object:  ForeignKey [fkCONTROLECOMPENSACAO_USUARIO]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[CONTROLECOMPENSACAO]  WITH CHECK ADD  CONSTRAINT [fkCONTROLECOMPENSACAO_USUARIO] FOREIGN KEY([cdUsuario])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[CONTROLECOMPENSACAO] CHECK CONSTRAINT [fkCONTROLECOMPENSACAO_USUARIO]
GO
/****** Object:  ForeignKey [fkCREDENCIACONTADOR_PESSOA]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[CREDENCIACONTADOR]  WITH CHECK ADD  CONSTRAINT [fkCREDENCIACONTADOR_PESSOA] FOREIGN KEY([cdPessoaContador])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[CREDENCIACONTADOR] CHECK CONSTRAINT [fkCREDENCIACONTADOR_PESSOA]
GO
/****** Object:  ForeignKey [fkCREDENCIACONTADOR_PESSOA2]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[CREDENCIACONTADOR]  WITH CHECK ADD  CONSTRAINT [fkCREDENCIACONTADOR_PESSOA2] FOREIGN KEY([cdPessoaCredenciamento])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[CREDENCIACONTADOR] CHECK CONSTRAINT [fkCREDENCIACONTADOR_PESSOA2]
GO
/****** Object:  ForeignKey [fkCREDENCIACONTADOR_PESSOA3]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[CREDENCIACONTADOR]  WITH CHECK ADD  CONSTRAINT [fkCREDENCIACONTADOR_PESSOA3] FOREIGN KEY([cdPessoaDescredenciamento])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[CREDENCIACONTADOR] CHECK CONSTRAINT [fkCREDENCIACONTADOR_PESSOA3]
GO
/****** Object:  ForeignKey [fkCREDENCIAGRAF_PESSOA]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[CREDENCIAGRAFICA]  WITH CHECK ADD  CONSTRAINT [fkCREDENCIAGRAF_PESSOA] FOREIGN KEY([cdFiscalCredenciador])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[CREDENCIAGRAFICA] CHECK CONSTRAINT [fkCREDENCIAGRAF_PESSOA]
GO
/****** Object:  ForeignKey [fkCREDENCIAGRAF_PESSOA2]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[CREDENCIAGRAFICA]  WITH CHECK ADD  CONSTRAINT [fkCREDENCIAGRAF_PESSOA2] FOREIGN KEY([cdGrafica])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[CREDENCIAGRAFICA] CHECK CONSTRAINT [fkCREDENCIAGRAF_PESSOA2]
GO
/****** Object:  ForeignKey [fkCREDENCIAGRAF_PESSOA3]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[CREDENCIAGRAFICA]  WITH CHECK ADD  CONSTRAINT [fkCREDENCIAGRAF_PESSOA3] FOREIGN KEY([cdFiscalDescredenciador])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[CREDENCIAGRAFICA] CHECK CONSTRAINT [fkCREDENCIAGRAF_PESSOA3]
GO
/****** Object:  ForeignKey [fkCREDITOIPTU_CADASTROTOMADORCREDITOS]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[CREDITOIPTU]  WITH CHECK ADD  CONSTRAINT [fkCREDITOIPTU_CADASTROTOMADORCREDITOS] FOREIGN KEY([cdCadastroTomadorCreditos])
REFERENCES [dbo].[CADASTROTOMADORCREDITOS] ([cdCadastroTomadorCreditos])
GO
ALTER TABLE [dbo].[CREDITOIPTU] CHECK CONSTRAINT [fkCREDITOIPTU_CADASTROTOMADORCREDITOS]
GO
/****** Object:  ForeignKey [fkDADOSPROMOCIONAIS_PESSOA]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[DADOSPROMOCIONAIS]  WITH CHECK ADD  CONSTRAINT [fkDADOSPROMOCIONAIS_PESSOA] FOREIGN KEY([cdPessoa])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[DADOSPROMOCIONAIS] CHECK CONSTRAINT [fkDADOSPROMOCIONAIS_PESSOA]
GO
/****** Object:  ForeignKey [fkDADOSPROMOCIONAIS_USUARIO]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[DADOSPROMOCIONAIS]  WITH CHECK ADD  CONSTRAINT [fkDADOSPROMOCIONAIS_USUARIO] FOREIGN KEY([cdUsuarioFiscal])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[DADOSPROMOCIONAIS] CHECK CONSTRAINT [fkDADOSPROMOCIONAIS_USUARIO]
GO
/****** Object:  ForeignKey [fkDEDUCAOCONSTRUCAOCIVIL_PAGAMENTO]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[DEDUCAOCONSTRUCAOCIVIL]  WITH NOCHECK ADD  CONSTRAINT [fkDEDUCAOCONSTRUCAOCIVIL_PAGAMENTO] FOREIGN KEY([cdPagamento])
REFERENCES [dbo].[PAGAMENTO] ([cdPagamento])
GO
ALTER TABLE [dbo].[DEDUCAOCONSTRUCAOCIVIL] CHECK CONSTRAINT [fkDEDUCAOCONSTRUCAOCIVIL_PAGAMENTO]
GO
/****** Object:  ForeignKey [fkDENUNCIA_USUARIO]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[DENUNCIA]  WITH CHECK ADD  CONSTRAINT [fkDENUNCIA_USUARIO] FOREIGN KEY([cdUsuarioFinalizacao])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[DENUNCIA] CHECK CONSTRAINT [fkDENUNCIA_USUARIO]
GO
/****** Object:  ForeignKey [fkDESCONTORECOLHIMENTO_PESSOA]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[DESCONTORECOLHIMENTO]  WITH CHECK ADD  CONSTRAINT [fkDESCONTORECOLHIMENTO_PESSOA] FOREIGN KEY([cdPessoa])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[DESCONTORECOLHIMENTO] CHECK CONSTRAINT [fkDESCONTORECOLHIMENTO_PESSOA]
GO
/****** Object:  ForeignKey [fkDESCRICAOSERVICONFECONTRIBUINTE_PESSOA]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[DESCRICAOSERVICONFECONTRIBUINTE]  WITH CHECK ADD  CONSTRAINT [fkDESCRICAOSERVICONFECONTRIBUINTE_PESSOA] FOREIGN KEY([cdPessoa])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[DESCRICAOSERVICONFECONTRIBUINTE] CHECK CONSTRAINT [fkDESCRICAOSERVICONFECONTRIBUINTE_PESSOA]
GO
/****** Object:  ForeignKey [fkDOCUMENTO_ATIVIDADE]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[DOCUMENTO]  WITH CHECK ADD  CONSTRAINT [fkDOCUMENTO_ATIVIDADE] FOREIGN KEY([cdAtividade])
REFERENCES [dbo].[ATIVIDADE] ([cdAtividade])
GO
ALTER TABLE [dbo].[DOCUMENTO] CHECK CONSTRAINT [fkDOCUMENTO_ATIVIDADE]
GO
/****** Object:  ForeignKey [fkDOCUMENTO_IMPORTACAOLANCAMENTOITENS]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[DOCUMENTO]  WITH CHECK ADD  CONSTRAINT [fkDOCUMENTO_IMPORTACAOLANCAMENTOITENS] FOREIGN KEY([cdImportacaoLancamentoItens])
REFERENCES [dbo].[IMPORTACAOLANCAMENTOITENS] ([cdImportacaoLancamentoItens])
GO
ALTER TABLE [dbo].[DOCUMENTO] CHECK CONSTRAINT [fkDOCUMENTO_IMPORTACAOLANCAMENTOITENS]
GO
/****** Object:  ForeignKey [fkDOCUMENTO_ITEMATIVIDADE]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[DOCUMENTO]  WITH CHECK ADD  CONSTRAINT [fkDOCUMENTO_ITEMATIVIDADE] FOREIGN KEY([cdItemAtividade])
REFERENCES [dbo].[ITEMATIVIDADE] ([cdItemAtividade])
GO
ALTER TABLE [dbo].[DOCUMENTO] CHECK CONSTRAINT [fkDOCUMENTO_ITEMATIVIDADE]
GO
/****** Object:  ForeignKey [fkDOCUMENTO_PESSOA]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[DOCUMENTO]  WITH CHECK ADD  CONSTRAINT [fkDOCUMENTO_PESSOA] FOREIGN KEY([cdPessoaPrestador])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[DOCUMENTO] CHECK CONSTRAINT [fkDOCUMENTO_PESSOA]
GO
/****** Object:  ForeignKey [fkDOCUMENTO_PESSOA1]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[DOCUMENTO]  WITH CHECK ADD  CONSTRAINT [fkDOCUMENTO_PESSOA1] FOREIGN KEY([cdPessoaTomador])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[DOCUMENTO] CHECK CONSTRAINT [fkDOCUMENTO_PESSOA1]
GO
/****** Object:  ForeignKey [fkDOCUMENTO_SERIENOTAFISCAL]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[DOCUMENTO]  WITH CHECK ADD  CONSTRAINT [fkDOCUMENTO_SERIENOTAFISCAL] FOREIGN KEY([cdSerieNotaFiscal])
REFERENCES [dbo].[SERIENOTAFISCAL] ([cdSerieNotaFiscal])
GO
ALTER TABLE [dbo].[DOCUMENTO] CHECK CONSTRAINT [fkDOCUMENTO_SERIENOTAFISCAL]
GO
/****** Object:  ForeignKey [fkDOCUMENTO_TIPODOCUMENTO]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[DOCUMENTO]  WITH CHECK ADD  CONSTRAINT [fkDOCUMENTO_TIPODOCUMENTO] FOREIGN KEY([cdTipoDocumento])
REFERENCES [dbo].[TIPODOCUMENTO] ([cdTipoDocumento])
GO
ALTER TABLE [dbo].[DOCUMENTO] CHECK CONSTRAINT [fkDOCUMENTO_TIPODOCUMENTO]
GO
/****** Object:  ForeignKey [fkDOCUMENTOANULADO_NOTAFISCAL]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[DOCUMENTOANULADO]  WITH CHECK ADD  CONSTRAINT [fkDOCUMENTOANULADO_NOTAFISCAL] FOREIGN KEY([cdNotaFiscal])
REFERENCES [dbo].[NOTAFISCAL] ([cdNotaFiscal])
GO
ALTER TABLE [dbo].[DOCUMENTOANULADO] CHECK CONSTRAINT [fkDOCUMENTOANULADO_NOTAFISCAL]
GO
/****** Object:  ForeignKey [fkDOCUMENTOANULADO_PESSOA]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[DOCUMENTOANULADO]  WITH CHECK ADD  CONSTRAINT [fkDOCUMENTOANULADO_PESSOA] FOREIGN KEY([cdPessoa])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[DOCUMENTOANULADO] CHECK CONSTRAINT [fkDOCUMENTOANULADO_PESSOA]
GO
/****** Object:  ForeignKey [fkDOCUMENTOANULADO_SERIEFISCAL]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[DOCUMENTOANULADO]  WITH CHECK ADD  CONSTRAINT [fkDOCUMENTOANULADO_SERIEFISCAL] FOREIGN KEY([cdSerieNotaFiscal])
REFERENCES [dbo].[SERIENOTAFISCAL] ([cdSerieNotaFiscal])
GO
ALTER TABLE [dbo].[DOCUMENTOANULADO] CHECK CONSTRAINT [fkDOCUMENTOANULADO_SERIEFISCAL]
GO
/****** Object:  ForeignKey [fkDOCUMENTONOTAFISCAL_DOCUMENTO]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[DOCUMENTONOTAFISCAL]  WITH CHECK ADD  CONSTRAINT [fkDOCUMENTONOTAFISCAL_DOCUMENTO] FOREIGN KEY([cdDocumento])
REFERENCES [dbo].[DOCUMENTO] ([cdDocumento])
GO
ALTER TABLE [dbo].[DOCUMENTONOTAFISCAL] CHECK CONSTRAINT [fkDOCUMENTONOTAFISCAL_DOCUMENTO]
GO
/****** Object:  ForeignKey [fkDOCUMENTONOTAFISCAL_NOTAFISCAL]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[DOCUMENTONOTAFISCAL]  WITH CHECK ADD  CONSTRAINT [fkDOCUMENTONOTAFISCAL_NOTAFISCAL] FOREIGN KEY([cdNotafiscal])
REFERENCES [dbo].[NOTAFISCAL] ([cdNotaFiscal])
GO
ALTER TABLE [dbo].[DOCUMENTONOTAFISCAL] CHECK CONSTRAINT [fkDOCUMENTONOTAFISCAL_NOTAFISCAL]
GO
/****** Object:  ForeignKey [fkDOCRETIFICADO_DOCUMENTO]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[DOCUMENTORETIFICADO]  WITH CHECK ADD  CONSTRAINT [fkDOCRETIFICADO_DOCUMENTO] FOREIGN KEY([cdDocumento])
REFERENCES [dbo].[DOCUMENTO] ([cdDocumento])
GO
ALTER TABLE [dbo].[DOCUMENTORETIFICADO] CHECK CONSTRAINT [fkDOCRETIFICADO_DOCUMENTO]
GO
/****** Object:  ForeignKey [fkDOCUMENTORETIFICADO_USUARIO]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[DOCUMENTORETIFICADO]  WITH CHECK ADD  CONSTRAINT [fkDOCUMENTORETIFICADO_USUARIO] FOREIGN KEY([cdUsuarioRetificacao])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[DOCUMENTORETIFICADO] CHECK CONSTRAINT [fkDOCUMENTORETIFICADO_USUARIO]
GO
/****** Object:  ForeignKey [fkDOWNLOADOFFLINE_PESSOA]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[DOWNLOADOFFLINE]  WITH CHECK ADD  CONSTRAINT [fkDOWNLOADOFFLINE_PESSOA] FOREIGN KEY([cdPessoa])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[DOWNLOADOFFLINE] CHECK CONSTRAINT [fkDOWNLOADOFFLINE_PESSOA]
GO
/****** Object:  ForeignKey [fkDOWNLOADOFFLINE_USUARIO]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[DOWNLOADOFFLINE]  WITH CHECK ADD  CONSTRAINT [fkDOWNLOADOFFLINE_USUARIO] FOREIGN KEY([cdUsuario])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[DOWNLOADOFFLINE] CHECK CONSTRAINT [fkDOWNLOADOFFLINE_USUARIO]
GO
/****** Object:  ForeignKey [fkEMAILENTIDADE_ENVIOEMAIL]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[EMAILENTIDADE]  WITH CHECK ADD  CONSTRAINT [fkEMAILENTIDADE_ENVIOEMAIL] FOREIGN KEY([cdEnvioEmail])
REFERENCES [dbo].[ENVIOEMAIL] ([cdEnvioEmail])
GO
ALTER TABLE [dbo].[EMAILENTIDADE] CHECK CONSTRAINT [fkEMAILENTIDADE_ENVIOEMAIL]
GO
/****** Object:  ForeignKey [fkENDERECO_PESSOA]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[ENDERECO]  WITH CHECK ADD  CONSTRAINT [fkENDERECO_PESSOA] FOREIGN KEY([cdPessoa])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[ENDERECO] CHECK CONSTRAINT [fkENDERECO_PESSOA]
GO
/****** Object:  ForeignKey [fkENVIOEMAILPAI_ENVIOEMAILFILHA]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[ENVIOEMAIL]  WITH CHECK ADD  CONSTRAINT [fkENVIOEMAILPAI_ENVIOEMAILFILHA] FOREIGN KEY([cdEmailOrigem])
REFERENCES [dbo].[ENVIOEMAIL] ([cdEnvioEmail])
GO
ALTER TABLE [dbo].[ENVIOEMAIL] CHECK CONSTRAINT [fkENVIOEMAILPAI_ENVIOEMAILFILHA]
GO
/****** Object:  ForeignKey [fkEXCECAOATIVIDADE_ATIVIDADE]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[EXCECAOATIVIDADE]  WITH CHECK ADD  CONSTRAINT [fkEXCECAOATIVIDADE_ATIVIDADE] FOREIGN KEY([cdAtividade])
REFERENCES [dbo].[ATIVIDADE] ([cdAtividade])
GO
ALTER TABLE [dbo].[EXCECAOATIVIDADE] CHECK CONSTRAINT [fkEXCECAOATIVIDADE_ATIVIDADE]
GO
/****** Object:  ForeignKey [fkEXCECAOATIVIDADE_PESSOA]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[EXCECAOATIVIDADE]  WITH CHECK ADD  CONSTRAINT [fkEXCECAOATIVIDADE_PESSOA] FOREIGN KEY([cdPessoa])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[EXCECAOATIVIDADE] CHECK CONSTRAINT [fkEXCECAOATIVIDADE_PESSOA]
GO
/****** Object:  ForeignKey [fkFERIADO_USUARIO]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[FERIADO]  WITH CHECK ADD  CONSTRAINT [fkFERIADO_USUARIO] FOREIGN KEY([cdUsuario])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[FERIADO] CHECK CONSTRAINT [fkFERIADO_USUARIO]
GO
/****** Object:  ForeignKey [fkFERIADOFIXO_USUARIO]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[FERIADOFIXO]  WITH CHECK ADD  CONSTRAINT [fkFERIADOFIXO_USUARIO] FOREIGN KEY([cdUsuarioCadastramento])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[FERIADOFIXO] CHECK CONSTRAINT [fkFERIADOFIXO_USUARIO]
GO
/****** Object:  ForeignKey [fkGUIAPAGAMENTOANTIGA_USUARIOEDICAO]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[GUIAPAGAMENTOANTIGA]  WITH CHECK ADD  CONSTRAINT [fkGUIAPAGAMENTOANTIGA_USUARIOEDICAO] FOREIGN KEY([cdUsuarioEdicao])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[GUIAPAGAMENTOANTIGA] CHECK CONSTRAINT [fkGUIAPAGAMENTOANTIGA_USUARIOEDICAO]
GO
/****** Object:  ForeignKey [fkGUIAPAGAMENTOANTIGA_USUARIOEXCLUSAO]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[GUIAPAGAMENTOANTIGA]  WITH CHECK ADD  CONSTRAINT [fkGUIAPAGAMENTOANTIGA_USUARIOEXCLUSAO] FOREIGN KEY([cdUsuarioExclusao])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[GUIAPAGAMENTOANTIGA] CHECK CONSTRAINT [fkGUIAPAGAMENTOANTIGA_USUARIOEXCLUSAO]
GO
/****** Object:  ForeignKey [fkGUIAPAGAMENTOANTIGA_USUARIOINCLUSAO]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[GUIAPAGAMENTOANTIGA]  WITH CHECK ADD  CONSTRAINT [fkGUIAPAGAMENTOANTIGA_USUARIOINCLUSAO] FOREIGN KEY([cdUsuarioInclusao])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[GUIAPAGAMENTOANTIGA] CHECK CONSTRAINT [fkGUIAPAGAMENTOANTIGA_USUARIOINCLUSAO]
GO
/****** Object:  ForeignKey [fkGUIAREEMBOLSO_PESSOA]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[GUIAREEMBOLSO]  WITH CHECK ADD  CONSTRAINT [fkGUIAREEMBOLSO_PESSOA] FOREIGN KEY([cdContribuinte])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[GUIAREEMBOLSO] CHECK CONSTRAINT [fkGUIAREEMBOLSO_PESSOA]
GO
/****** Object:  ForeignKey [fkGUIAREEMBOLSO_USUARIO_EDICAO]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[GUIAREEMBOLSO]  WITH CHECK ADD  CONSTRAINT [fkGUIAREEMBOLSO_USUARIO_EDICAO] FOREIGN KEY([cdUsuarioEdicao])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[GUIAREEMBOLSO] CHECK CONSTRAINT [fkGUIAREEMBOLSO_USUARIO_EDICAO]
GO
/****** Object:  ForeignKey [fkGUIAREEMBOLSO_USUARIO_EXCLUSAO]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[GUIAREEMBOLSO]  WITH CHECK ADD  CONSTRAINT [fkGUIAREEMBOLSO_USUARIO_EXCLUSAO] FOREIGN KEY([cdUsuarioExclusao])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[GUIAREEMBOLSO] CHECK CONSTRAINT [fkGUIAREEMBOLSO_USUARIO_EXCLUSAO]
GO
/****** Object:  ForeignKey [fkGUIAREEMBOLSO_USUARIO_INCLUSAO]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[GUIAREEMBOLSO]  WITH CHECK ADD  CONSTRAINT [fkGUIAREEMBOLSO_USUARIO_INCLUSAO] FOREIGN KEY([cdUsuarioInclusao])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[GUIAREEMBOLSO] CHECK CONSTRAINT [fkGUIAREEMBOLSO_USUARIO_INCLUSAO]
GO
/****** Object:  ForeignKey [fkGUIAREEMBOLSOPAGAMENTO_GUIAREEMBOLSO]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[GUIAREEMBOLSOPAGAMENTO]  WITH CHECK ADD  CONSTRAINT [fkGUIAREEMBOLSOPAGAMENTO_GUIAREEMBOLSO] FOREIGN KEY([cdGuiaReembolso])
REFERENCES [dbo].[GUIAREEMBOLSO] ([cdGuiaReembolso])
GO
ALTER TABLE [dbo].[GUIAREEMBOLSOPAGAMENTO] CHECK CONSTRAINT [fkGUIAREEMBOLSOPAGAMENTO_GUIAREEMBOLSO]
GO
/****** Object:  ForeignKey [fkGUIAREEMBOLSOPAGAMENTO_PAGAMENTO]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[GUIAREEMBOLSOPAGAMENTO]  WITH CHECK ADD  CONSTRAINT [fkGUIAREEMBOLSOPAGAMENTO_PAGAMENTO] FOREIGN KEY([cdPagamento])
REFERENCES [dbo].[PAGAMENTO] ([cdPagamento])
GO
ALTER TABLE [dbo].[GUIAREEMBOLSOPAGAMENTO] CHECK CONSTRAINT [fkGUIAREEMBOLSOPAGAMENTO_PAGAMENTO]
GO
/****** Object:  ForeignKey [fkHISTORICOIMPRESSAONOTAFISCAL_NOTAFISCAL]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[HISTORICOIMPRESSAONOTAFISCAL]  WITH CHECK ADD  CONSTRAINT [fkHISTORICOIMPRESSAONOTAFISCAL_NOTAFISCAL] FOREIGN KEY([cdNotaFiscal])
REFERENCES [dbo].[NOTAFISCAL] ([cdNotaFiscal])
GO
ALTER TABLE [dbo].[HISTORICOIMPRESSAONOTAFISCAL] CHECK CONSTRAINT [fkHISTORICOIMPRESSAONOTAFISCAL_NOTAFISCAL]
GO
/****** Object:  ForeignKey [fkHISTORICOIMPRESSAONOTAFISCAL_USUARIO]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[HISTORICOIMPRESSAONOTAFISCAL]  WITH CHECK ADD  CONSTRAINT [fkHISTORICOIMPRESSAONOTAFISCAL_USUARIO] FOREIGN KEY([cdUsuarioLogado])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[HISTORICOIMPRESSAONOTAFISCAL] CHECK CONSTRAINT [fkHISTORICOIMPRESSAONOTAFISCAL_USUARIO]
GO
/****** Object:  ForeignKey [fkHISTORICOMOVIMENTACAOCREDITO]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[HISTORICOMOVIMENTACAOCREDITO]  WITH CHECK ADD  CONSTRAINT [fkHISTORICOMOVIMENTACAOCREDITO] FOREIGN KEY([cdHistoricoMovimentacaoCreditoDevolucao])
REFERENCES [dbo].[HISTORICOMOVIMENTACAOCREDITO] ([cdHistoricoMovimentacaoCredito])
GO
ALTER TABLE [dbo].[HISTORICOMOVIMENTACAOCREDITO] CHECK CONSTRAINT [fkHISTORICOMOVIMENTACAOCREDITO]
GO
/****** Object:  ForeignKey [fkHISTORICOMOVIMENTACAOCREDITO_CADASTROTOMADORCREDITOS]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[HISTORICOMOVIMENTACAOCREDITO]  WITH CHECK ADD  CONSTRAINT [fkHISTORICOMOVIMENTACAOCREDITO_CADASTROTOMADORCREDITOS] FOREIGN KEY([cdTomadorOrigem])
REFERENCES [dbo].[CADASTROTOMADORCREDITOS] ([cdCadastroTomadorCreditos])
GO
ALTER TABLE [dbo].[HISTORICOMOVIMENTACAOCREDITO] CHECK CONSTRAINT [fkHISTORICOMOVIMENTACAOCREDITO_CADASTROTOMADORCREDITOS]
GO
/****** Object:  ForeignKey [fkHISTORICOMOVIMENTACAOCREDITO_CADASTROTOMADORCREDITOS2]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[HISTORICOMOVIMENTACAOCREDITO]  WITH CHECK ADD  CONSTRAINT [fkHISTORICOMOVIMENTACAOCREDITO_CADASTROTOMADORCREDITOS2] FOREIGN KEY([cdTomadorDestino])
REFERENCES [dbo].[CADASTROTOMADORCREDITOS] ([cdCadastroTomadorCreditos])
GO
ALTER TABLE [dbo].[HISTORICOMOVIMENTACAOCREDITO] CHECK CONSTRAINT [fkHISTORICOMOVIMENTACAOCREDITO_CADASTROTOMADORCREDITOS2]
GO
/****** Object:  ForeignKey [fkHISTORICOMOVIMENTACAOCREDITO_CDCIPTU]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[HISTORICOMOVIMENTACAOCREDITO]  WITH CHECK ADD  CONSTRAINT [fkHISTORICOMOVIMENTACAOCREDITO_CDCIPTU] FOREIGN KEY([cdCDCIPTU])
REFERENCES [dbo].[CDCIPTU] ([CDCDCIPTU])
GO
ALTER TABLE [dbo].[HISTORICOMOVIMENTACAOCREDITO] CHECK CONSTRAINT [fkHISTORICOMOVIMENTACAOCREDITO_CDCIPTU]
GO
/****** Object:  ForeignKey [fkTRANSMISSAOARQ_PESSOA]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[IMPORTACAOLANCAMENTO]  WITH CHECK ADD  CONSTRAINT [fkTRANSMISSAOARQ_PESSOA] FOREIGN KEY([cdPessoa])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[IMPORTACAOLANCAMENTO] CHECK CONSTRAINT [fkTRANSMISSAOARQ_PESSOA]
GO
/****** Object:  ForeignKey [fkTRANSMISSAOARQ_USUARIO]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[IMPORTACAOLANCAMENTO]  WITH CHECK ADD  CONSTRAINT [fkTRANSMISSAOARQ_USUARIO] FOREIGN KEY([cdUsuario])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[IMPORTACAOLANCAMENTO] CHECK CONSTRAINT [fkTRANSMISSAOARQ_USUARIO]
GO
/****** Object:  ForeignKey [fkIMPORTACAOLANCAMENTOITENS_IMPORTACAOLANCAMENTO]    Script Date: 04/02/2013 11:32:19 ******/
ALTER TABLE [dbo].[IMPORTACAOLANCAMENTOITENS]  WITH CHECK ADD  CONSTRAINT [fkIMPORTACAOLANCAMENTOITENS_IMPORTACAOLANCAMENTO] FOREIGN KEY([cdImportacaoLancamento])
REFERENCES [dbo].[IMPORTACAOLANCAMENTO] ([cdImportacaoLancamento])
GO
ALTER TABLE [dbo].[IMPORTACAOLANCAMENTOITENS] CHECK CONSTRAINT [fkIMPORTACAOLANCAMENTOITENS_IMPORTACAOLANCAMENTO]
GO
/****** Object:  ForeignKey [fkINCONSISTENCIAFISCALIZACAO_TIPOINCONSISTENCIA]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[INCONSISTENCIAFISCALIZACAO]  WITH CHECK ADD  CONSTRAINT [fkINCONSISTENCIAFISCALIZACAO_TIPOINCONSISTENCIA] FOREIGN KEY([cdTipoInconsistencia])
REFERENCES [dbo].[TIPOINCONSISTENCIA] ([cdTipoInconsistencia])
GO
ALTER TABLE [dbo].[INCONSISTENCIAFISCALIZACAO] CHECK CONSTRAINT [fkINCONSISTENCIAFISCALIZACAO_TIPOINCONSISTENCIA]
GO
/****** Object:  ForeignKey [fkINCONSISTENCIAFISCALIZACAOHISTORICO_INCONSISTENCIAFISCALIZACAO]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[INCONSISTENCIAFISCALIZACAOHISTORICO]  WITH CHECK ADD  CONSTRAINT [fkINCONSISTENCIAFISCALIZACAOHISTORICO_INCONSISTENCIAFISCALIZACAO] FOREIGN KEY([cdInconsistenciaFiscalizacao])
REFERENCES [dbo].[INCONSISTENCIAFISCALIZACAO] ([cdInconsistenciaFiscalizacao])
GO
ALTER TABLE [dbo].[INCONSISTENCIAFISCALIZACAOHISTORICO] CHECK CONSTRAINT [fkINCONSISTENCIAFISCALIZACAOHISTORICO_INCONSISTENCIAFISCALIZACAO]
GO
/****** Object:  ForeignKey [fkINCONSISTENCIAFISCALIZACAOLOG_INCONSISTENCIAFISCALIZACAO]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[INCONSISTENCIAFISCALIZACAOLOG]  WITH CHECK ADD  CONSTRAINT [fkINCONSISTENCIAFISCALIZACAOLOG_INCONSISTENCIAFISCALIZACAO] FOREIGN KEY([cdInconsistenciaFiscalizacao])
REFERENCES [dbo].[INCONSISTENCIAFISCALIZACAO] ([cdInconsistenciaFiscalizacao])
GO
ALTER TABLE [dbo].[INCONSISTENCIAFISCALIZACAOLOG] CHECK CONSTRAINT [fkINCONSISTENCIAFISCALIZACAOLOG_INCONSISTENCIAFISCALIZACAO]
GO
/****** Object:  ForeignKey [fkINCONSISTENCIAFISCALIZACAOLOG_PESSOA]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[INCONSISTENCIAFISCALIZACAOLOG]  WITH CHECK ADD  CONSTRAINT [fkINCONSISTENCIAFISCALIZACAOLOG_PESSOA] FOREIGN KEY([cdPessoaEncaminhamento])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[INCONSISTENCIAFISCALIZACAOLOG] CHECK CONSTRAINT [fkINCONSISTENCIAFISCALIZACAOLOG_PESSOA]
GO
/****** Object:  ForeignKey [fkINCONSISTENCIAFISCALIZACAOLOG_PESSOA2]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[INCONSISTENCIAFISCALIZACAOLOG]  WITH CHECK ADD  CONSTRAINT [fkINCONSISTENCIAFISCALIZACAOLOG_PESSOA2] FOREIGN KEY([cdPessoaResponsavel])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[INCONSISTENCIAFISCALIZACAOLOG] CHECK CONSTRAINT [fkINCONSISTENCIAFISCALIZACAOLOG_PESSOA2]
GO
/****** Object:  ForeignKey [fkINCONSISTENCIAITENIMPORTACAO_IMPORTACAOLANCAMENTOITENS]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[INCONSISTENCIAITENIMPORTACAO]  WITH CHECK ADD  CONSTRAINT [fkINCONSISTENCIAITENIMPORTACAO_IMPORTACAOLANCAMENTOITENS] FOREIGN KEY([cdImportacaoLancamentoItens])
REFERENCES [dbo].[IMPORTACAOLANCAMENTOITENS] ([cdImportacaoLancamentoItens])
GO
ALTER TABLE [dbo].[INCONSISTENCIAITENIMPORTACAO] CHECK CONSTRAINT [fkINCONSISTENCIAITENIMPORTACAO_IMPORTACAOLANCAMENTOITENS]
GO
/****** Object:  ForeignKey [fkINDICECORREMONE_USUARIO]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[INDICECORRECAOMONETARIA]  WITH CHECK ADD  CONSTRAINT [fkINDICECORREMONE_USUARIO] FOREIGN KEY([cdUsuario])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[INDICECORRECAOMONETARIA] CHECK CONSTRAINT [fkINDICECORREMONE_USUARIO]
GO
/****** Object:  ForeignKey [fkINDICEMUNICIPIO_USUARIO]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[INDICEMUNICIPIO]  WITH CHECK ADD  CONSTRAINT [fkINDICEMUNICIPIO_USUARIO] FOREIGN KEY([cdUsuario])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[INDICEMUNICIPIO] CHECK CONSTRAINT [fkINDICEMUNICIPIO_USUARIO]
GO
/****** Object:  ForeignKey [fkINSCRICAOMUNICIPAL_PESSOA]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[INSCRICAOMUNICIPAL]  WITH CHECK ADD  CONSTRAINT [fkINSCRICAOMUNICIPAL_PESSOA] FOREIGN KEY([cdPessoa])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[INSCRICAOMUNICIPAL] CHECK CONSTRAINT [fkINSCRICAOMUNICIPAL_PESSOA]
GO
/****** Object:  ForeignKey [fkRLA_RLC]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[ISSRLARen_Leg_Atividade]  WITH NOCHECK ADD  CONSTRAINT [fkRLA_RLC] FOREIGN KEY([Id_Contribuinte])
REFERENCES [dbo].[ISSRLCRen_Leg_Contribuinte] ([ID_Contribuinte])
GO
ALTER TABLE [dbo].[ISSRLARen_Leg_Atividade] CHECK CONSTRAINT [fkRLA_RLC]
GO
/****** Object:  ForeignKey [fkRLP_RLC]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[ISSRLPRen_Leg_Publicidade]  WITH NOCHECK ADD  CONSTRAINT [fkRLP_RLC] FOREIGN KEY([Id_Contribuinte])
REFERENCES [dbo].[ISSRLCRen_Leg_Contribuinte] ([ID_Contribuinte])
GO
ALTER TABLE [dbo].[ISSRLPRen_Leg_Publicidade] CHECK CONSTRAINT [fkRLP_RLC]
GO
/****** Object:  ForeignKey [fkRLP_RTP]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[ISSRLPRen_Leg_Publicidade]  WITH NOCHECK ADD  CONSTRAINT [fkRLP_RTP] FOREIGN KEY([Id_Tipo_Publicidade])
REFERENCES [dbo].[ISSRTPRen_Tipo_Puplic] ([ID_TipoPublicidade])
GO
ALTER TABLE [dbo].[ISSRLPRen_Leg_Publicidade] CHECK CONSTRAINT [fkRLP_RTP]
GO
/****** Object:  ForeignKey [fkRLS_RLC]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[ISSRLSRen_Leg_Socio]  WITH CHECK ADD  CONSTRAINT [fkRLS_RLC] FOREIGN KEY([Id_Contribuinte])
REFERENCES [dbo].[ISSRLCRen_Leg_Contribuinte] ([ID_Contribuinte])
GO
ALTER TABLE [dbo].[ISSRLSRen_Leg_Socio] CHECK CONSTRAINT [fkRLS_RLC]
GO
/****** Object:  ForeignKey [fkRA_RC]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[ISSRNARen_Atividade]  WITH NOCHECK ADD  CONSTRAINT [fkRA_RC] FOREIGN KEY([Id_Contribuinte])
REFERENCES [dbo].[ISSRNCRen_Contribuinte] ([ID_Contribuinte])
GO
ALTER TABLE [dbo].[ISSRNARen_Atividade] CHECK CONSTRAINT [fkRA_RC]
GO
/****** Object:  ForeignKey [fkRP_RC]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[ISSRNPRen_Publicidade]  WITH NOCHECK ADD  CONSTRAINT [fkRP_RC] FOREIGN KEY([Id_Contribuinte])
REFERENCES [dbo].[ISSRNCRen_Contribuinte] ([ID_Contribuinte])
GO
ALTER TABLE [dbo].[ISSRNPRen_Publicidade] CHECK CONSTRAINT [fkRP_RC]
GO
/****** Object:  ForeignKey [fkRS_RC]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[ISSRNSRen_Socio]  WITH NOCHECK ADD  CONSTRAINT [fkRS_RC] FOREIGN KEY([Id_Contribuinte])
REFERENCES [dbo].[ISSRNCRen_Contribuinte] ([ID_Contribuinte])
GO
ALTER TABLE [dbo].[ISSRNSRen_Socio] CHECK CONSTRAINT [fkRS_RC]
GO
/****** Object:  ForeignKey [fkITEMPAGAMENTO_PAGAMENTO]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[ITEMPAGAMENTO]  WITH CHECK ADD  CONSTRAINT [fkITEMPAGAMENTO_PAGAMENTO] FOREIGN KEY([cdPagamento])
REFERENCES [dbo].[PAGAMENTO] ([cdPagamento])
GO
ALTER TABLE [dbo].[ITEMPAGAMENTO] CHECK CONSTRAINT [fkITEMPAGAMENTO_PAGAMENTO]
GO
/****** Object:  ForeignKey [fkLANCAMENTOBANCARIO_ATI]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[LANCAMENTOBANCARIO]  WITH CHECK ADD  CONSTRAINT [fkLANCAMENTOBANCARIO_ATI] FOREIGN KEY([cdAtividade])
REFERENCES [dbo].[ATIVIDADE] ([cdAtividade])
GO
ALTER TABLE [dbo].[LANCAMENTOBANCARIO] CHECK CONSTRAINT [fkLANCAMENTOBANCARIO_ATI]
GO
/****** Object:  ForeignKey [fkLANCAMENTOBANCARIO_IMPORTACAOLANCAMENTOITENS]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[LANCAMENTOBANCARIO]  WITH CHECK ADD  CONSTRAINT [fkLANCAMENTOBANCARIO_IMPORTACAOLANCAMENTOITENS] FOREIGN KEY([cdImportacaoLancamentoItens])
REFERENCES [dbo].[IMPORTACAOLANCAMENTOITENS] ([cdImportacaoLancamentoItens])
GO
ALTER TABLE [dbo].[LANCAMENTOBANCARIO] CHECK CONSTRAINT [fkLANCAMENTOBANCARIO_IMPORTACAOLANCAMENTOITENS]
GO
/****** Object:  ForeignKey [fkLANCAMENTOBANCARIO_PESSOA]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[LANCAMENTOBANCARIO]  WITH CHECK ADD  CONSTRAINT [fkLANCAMENTOBANCARIO_PESSOA] FOREIGN KEY([cdPessoa])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[LANCAMENTOBANCARIO] CHECK CONSTRAINT [fkLANCAMENTOBANCARIO_PESSOA]
GO
/****** Object:  ForeignKey [fkLANCBANCARIO_CODIGOCOSIF]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[LANCAMENTOBANCARIO]  WITH CHECK ADD  CONSTRAINT [fkLANCBANCARIO_CODIGOCOSIF] FOREIGN KEY([cdCodigoCosif])
REFERENCES [dbo].[CODIGOCOSIF] ([cdCodigoCosif])
GO
ALTER TABLE [dbo].[LANCAMENTOBANCARIO] CHECK CONSTRAINT [fkLANCBANCARIO_CODIGOCOSIF]
GO
/****** Object:  ForeignKey [fkLOGALTERACAONOTAFISCAL_NOTAFISCAL01]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[LOGALTERACAONOTAFISCAL]  WITH CHECK ADD  CONSTRAINT [fkLOGALTERACAONOTAFISCAL_NOTAFISCAL01] FOREIGN KEY([cdNotaFiscal])
REFERENCES [dbo].[NOTAFISCAL] ([cdNotaFiscal])
GO
ALTER TABLE [dbo].[LOGALTERACAONOTAFISCAL] CHECK CONSTRAINT [fkLOGALTERACAONOTAFISCAL_NOTAFISCAL01]
GO
/****** Object:  ForeignKey [fkLOGALTERACAONOTAFISCAL_USUARIO01]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[LOGALTERACAONOTAFISCAL]  WITH CHECK ADD  CONSTRAINT [fkLOGALTERACAONOTAFISCAL_USUARIO01] FOREIGN KEY([cdUsuarioInclusao])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[LOGALTERACAONOTAFISCAL] CHECK CONSTRAINT [fkLOGALTERACAONOTAFISCAL_USUARIO01]
GO
/****** Object:  ForeignKey [fkLOGALTERACAOSENHA_PESSOA]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[LOGALTERACAOSENHA]  WITH CHECK ADD  CONSTRAINT [fkLOGALTERACAOSENHA_PESSOA] FOREIGN KEY([cdPessoa])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[LOGALTERACAOSENHA] CHECK CONSTRAINT [fkLOGALTERACAOSENHA_PESSOA]
GO
/****** Object:  ForeignKey [fkLOGALTERACAOSENHA_USUARIO]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[LOGALTERACAOSENHA]  WITH CHECK ADD  CONSTRAINT [fkLOGALTERACAOSENHA_USUARIO] FOREIGN KEY([cdUsuario])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[LOGALTERACAOSENHA] CHECK CONSTRAINT [fkLOGALTERACAOSENHA_USUARIO]
GO
/****** Object:  ForeignKey [fkLOGALTERACAOSENHA_USUARIO2]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[LOGALTERACAOSENHA]  WITH CHECK ADD  CONSTRAINT [fkLOGALTERACAOSENHA_USUARIO2] FOREIGN KEY([cdUsuarioOperacao])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[LOGALTERACAOSENHA] CHECK CONSTRAINT [fkLOGALTERACAOSENHA_USUARIO2]
GO
/****** Object:  ForeignKey [fkLOGAUDITORIA_TABELAAUDITORIA]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[LOGAUDITORIA]  WITH CHECK ADD  CONSTRAINT [fkLOGAUDITORIA_TABELAAUDITORIA] FOREIGN KEY([cdTabelaAuditoria])
REFERENCES [dbo].[TABELAAUDITORIA] ([cdTabelaAuditoria])
GO
ALTER TABLE [dbo].[LOGAUDITORIA] CHECK CONSTRAINT [fkLOGAUDITORIA_TABELAAUDITORIA]
GO
/****** Object:  ForeignKey [fkLOGAUDITORIA_TRANSACAO]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[LOGAUDITORIA]  WITH CHECK ADD  CONSTRAINT [fkLOGAUDITORIA_TRANSACAO] FOREIGN KEY([cdTransacao])
REFERENCES [dbo].[TRANSACAO] ([cdTransacao])
GO
ALTER TABLE [dbo].[LOGAUDITORIA] CHECK CONSTRAINT [fkLOGAUDITORIA_TRANSACAO]
GO
/****** Object:  ForeignKey [fkLOGAUDITORIA_USUARIO]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[LOGAUDITORIA]  WITH CHECK ADD  CONSTRAINT [fkLOGAUDITORIA_USUARIO] FOREIGN KEY([cdUsuario])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[LOGAUDITORIA] CHECK CONSTRAINT [fkLOGAUDITORIA_USUARIO]
GO
/****** Object:  ForeignKey [fkLOGEMAIL_ENVIOEMAIL]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[LOGEMAIL]  WITH CHECK ADD  CONSTRAINT [fkLOGEMAIL_ENVIOEMAIL] FOREIGN KEY([cdEnvioEmail])
REFERENCES [dbo].[ENVIOEMAIL] ([cdEnvioEmail])
GO
ALTER TABLE [dbo].[LOGEMAIL] CHECK CONSTRAINT [fkLOGEMAIL_ENVIOEMAIL]
GO
/****** Object:  ForeignKey [fkLOGEMAIL_SERVIDOREMAIL]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[LOGEMAIL]  WITH CHECK ADD  CONSTRAINT [fkLOGEMAIL_SERVIDOREMAIL] FOREIGN KEY([cdServidorEmail])
REFERENCES [dbo].[SERVIDOREMAIL] ([cdServidorEmail])
GO
ALTER TABLE [dbo].[LOGEMAIL] CHECK CONSTRAINT [fkLOGEMAIL_SERVIDOREMAIL]
GO
/****** Object:  ForeignKey [fkLOGWEBSERVICES_LOGERROS]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[LOGWEBSERVICES]  WITH CHECK ADD  CONSTRAINT [fkLOGWEBSERVICES_LOGERROS] FOREIGN KEY([cdLogErros])
REFERENCES [dbo].[LOGERROS] ([cdEvento])
GO
ALTER TABLE [dbo].[LOGWEBSERVICES] CHECK CONSTRAINT [fkLOGWEBSERVICES_LOGERROS]
GO
/****** Object:  ForeignKey [fkLOGWEBSERVICES_USUARIO]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[LOGWEBSERVICES]  WITH CHECK ADD  CONSTRAINT [fkLOGWEBSERVICES_USUARIO] FOREIGN KEY([cdUsuario])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[LOGWEBSERVICES] CHECK CONSTRAINT [fkLOGWEBSERVICES_USUARIO]
GO
/****** Object:  ForeignKey [fkMENSAGEMCOMUM_MENSAGEMCOMUM]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[MENSAGEMCOMUNICACAO]  WITH CHECK ADD  CONSTRAINT [fkMENSAGEMCOMUM_MENSAGEMCOMUM] FOREIGN KEY([cdMensagemOriginal])
REFERENCES [dbo].[MENSAGEMCOMUNICACAO] ([cdMensagemComunicacao])
GO
ALTER TABLE [dbo].[MENSAGEMCOMUNICACAO] CHECK CONSTRAINT [fkMENSAGEMCOMUM_MENSAGEMCOMUM]
GO
/****** Object:  ForeignKey [fkMENSAGEMCOMUM_PESSOA]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[MENSAGEMCOMUNICACAO]  WITH CHECK ADD  CONSTRAINT [fkMENSAGEMCOMUM_PESSOA] FOREIGN KEY([cdContribuinteDestino])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[MENSAGEMCOMUNICACAO] CHECK CONSTRAINT [fkMENSAGEMCOMUM_PESSOA]
GO
/****** Object:  ForeignKey [fkMENSAGEMCOMUM_PESSOA2]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[MENSAGEMCOMUNICACAO]  WITH CHECK ADD  CONSTRAINT [fkMENSAGEMCOMUM_PESSOA2] FOREIGN KEY([cdContribuinteOrigem])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[MENSAGEMCOMUNICACAO] CHECK CONSTRAINT [fkMENSAGEMCOMUM_PESSOA2]
GO
/****** Object:  ForeignKey [fkMENSAGEMCOMUM_USUARIO]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[MENSAGEMCOMUNICACAO]  WITH CHECK ADD  CONSTRAINT [fkMENSAGEMCOMUM_USUARIO] FOREIGN KEY([cdUsuarioFinalizador])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[MENSAGEMCOMUNICACAO] CHECK CONSTRAINT [fkMENSAGEMCOMUM_USUARIO]
GO
/****** Object:  ForeignKey [fkMENSAGEMCOMUM_USUARIO2]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[MENSAGEMCOMUNICACAO]  WITH CHECK ADD  CONSTRAINT [fkMENSAGEMCOMUM_USUARIO2] FOREIGN KEY([cdUsuarioEmissor])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[MENSAGEMCOMUNICACAO] CHECK CONSTRAINT [fkMENSAGEMCOMUM_USUARIO2]
GO
/****** Object:  ForeignKey [fkMSGMURALAVISO_USUARIO]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[MENSAGEMMURALAVISO]  WITH CHECK ADD  CONSTRAINT [fkMSGMURALAVISO_USUARIO] FOREIGN KEY([cdUsuario])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[MENSAGEMMURALAVISO] CHECK CONSTRAINT [fkMSGMURALAVISO_USUARIO]
GO
/****** Object:  ForeignKey [fkMENU_MENU]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[MENU]  WITH CHECK ADD  CONSTRAINT [fkMENU_MENU] FOREIGN KEY([cdMenuPai])
REFERENCES [dbo].[MENU] ([cdMenu])
GO
ALTER TABLE [dbo].[MENU] CHECK CONSTRAINT [fkMENU_MENU]
GO
/****** Object:  ForeignKey [fkMENU_PERMISSAOACESSO]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[MENU]  WITH CHECK ADD  CONSTRAINT [fkMENU_PERMISSAOACESSO] FOREIGN KEY([cdPermissaoAcesso])
REFERENCES [dbo].[PERMISSAOACESSO] ([cdPermissaoAcesso])
GO
ALTER TABLE [dbo].[MENU] CHECK CONSTRAINT [fkMENU_PERMISSAOACESSO]
GO
/****** Object:  ForeignKey [fkMENUAREADETRABALHO]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[MENUAREADETRABALHO]  WITH CHECK ADD  CONSTRAINT [fkMENUAREADETRABALHO] FOREIGN KEY([cdMenuAreaDeTrabalhoPai])
REFERENCES [dbo].[MENUAREADETRABALHO] ([cdMenuAreaDeTrabalho])
GO
ALTER TABLE [dbo].[MENUAREADETRABALHO] CHECK CONSTRAINT [fkMENUAREADETRABALHO]
GO
/****** Object:  ForeignKey [fkMENUAREADETRABALHO_PERMISSAOACESSO]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[MENUAREADETRABALHO]  WITH CHECK ADD  CONSTRAINT [fkMENUAREADETRABALHO_PERMISSAOACESSO] FOREIGN KEY([cdPermissaoAcesso])
REFERENCES [dbo].[PERMISSAOACESSO] ([cdPermissaoAcesso])
GO
ALTER TABLE [dbo].[MENUAREADETRABALHO] CHECK CONSTRAINT [fkMENUAREADETRABALHO_PERMISSAOACESSO]
GO
/****** Object:  ForeignKey [fkMESSEMMOVIMENTO_PESSOA]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[MESSEMMOVIMENTO]  WITH CHECK ADD  CONSTRAINT [fkMESSEMMOVIMENTO_PESSOA] FOREIGN KEY([cdPessoa])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[MESSEMMOVIMENTO] CHECK CONSTRAINT [fkMESSEMMOVIMENTO_PESSOA]
GO
/****** Object:  ForeignKey [fkMONPESSOANAOPAGAMENTO_INSCRICAOMUNICIPAL]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[MONPESSOANAOPAGAMENTO]  WITH CHECK ADD  CONSTRAINT [fkMONPESSOANAOPAGAMENTO_INSCRICAOMUNICIPAL] FOREIGN KEY([cdInscricaoMunicipal])
REFERENCES [dbo].[INSCRICAOMUNICIPAL] ([cdInscricaoMunicipal])
GO
ALTER TABLE [dbo].[MONPESSOANAOPAGAMENTO] CHECK CONSTRAINT [fkMONPESSOANAOPAGAMENTO_INSCRICAOMUNICIPAL]
GO
/****** Object:  ForeignKey [fkMOVIMENTACAOCREDITOIPTU_CADASTROTOMADORCREDITOS]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[MOVIMENTACAOCREDITOIPTU]  WITH NOCHECK ADD  CONSTRAINT [fkMOVIMENTACAOCREDITOIPTU_CADASTROTOMADORCREDITOS] FOREIGN KEY([cdCadastroTomadorCreditos])
REFERENCES [dbo].[CADASTROTOMADORCREDITOS] ([cdCadastroTomadorCreditos])
GO
ALTER TABLE [dbo].[MOVIMENTACAOCREDITOIPTU] CHECK CONSTRAINT [fkMOVIMENTACAOCREDITOIPTU_CADASTROTOMADORCREDITOS]
GO
/****** Object:  ForeignKey [fkNOTAFISCAL_IMPORTACAOLANCAMENTOITENS]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[NOTAFISCAL]  WITH CHECK ADD  CONSTRAINT [fkNOTAFISCAL_IMPORTACAOLANCAMENTOITENS] FOREIGN KEY([cdImportacaoLancamentoItens])
REFERENCES [dbo].[IMPORTACAOLANCAMENTOITENS] ([cdImportacaoLancamentoItens])
GO
ALTER TABLE [dbo].[NOTAFISCAL] CHECK CONSTRAINT [fkNOTAFISCAL_IMPORTACAOLANCAMENTOITENS]
GO
/****** Object:  ForeignKey [fkNOTAFISCAL_PESSOA]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[NOTAFISCAL]  WITH CHECK ADD  CONSTRAINT [fkNOTAFISCAL_PESSOA] FOREIGN KEY([cdPessoaPrestador])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[NOTAFISCAL] CHECK CONSTRAINT [fkNOTAFISCAL_PESSOA]
GO
/****** Object:  ForeignKey [fkNOTAFISCAL_PESSOA2]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[NOTAFISCAL]  WITH CHECK ADD  CONSTRAINT [fkNOTAFISCAL_PESSOA2] FOREIGN KEY([cdPessoaTomador])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[NOTAFISCAL] CHECK CONSTRAINT [fkNOTAFISCAL_PESSOA2]
GO
/****** Object:  ForeignKey [fkNOTAFISCAL_RPSTRANSMISSAOITEM]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[NOTAFISCAL]  WITH CHECK ADD  CONSTRAINT [fkNOTAFISCAL_RPSTRANSMISSAOITEM] FOREIGN KEY([cdRpsTransmissaoItem])
REFERENCES [dbo].[RPSTRANSMISSAOITEM] ([cdRPSTransmissaoItem])
GO
ALTER TABLE [dbo].[NOTAFISCAL] CHECK CONSTRAINT [fkNOTAFISCAL_RPSTRANSMISSAOITEM]
GO
/****** Object:  ForeignKey [fkNOTAFISCAL_SERIENOTAFISCAL]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[NOTAFISCAL]  WITH CHECK ADD  CONSTRAINT [fkNOTAFISCAL_SERIENOTAFISCAL] FOREIGN KEY([cdSerieNotaFiscal])
REFERENCES [dbo].[SERIENOTAFISCAL] ([cdSerieNotaFiscal])
GO
ALTER TABLE [dbo].[NOTAFISCAL] CHECK CONSTRAINT [fkNOTAFISCAL_SERIENOTAFISCAL]
GO
/****** Object:  ForeignKey [fkNOTAFISCAL_USUARIO]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[NOTAFISCAL]  WITH CHECK ADD  CONSTRAINT [fkNOTAFISCAL_USUARIO] FOREIGN KEY([cdUsuarioContribuinte])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[NOTAFISCAL] CHECK CONSTRAINT [fkNOTAFISCAL_USUARIO]
GO
/****** Object:  ForeignKey [fkNOTAFISCAL_USUARIO2]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[NOTAFISCAL]  WITH CHECK ADD  CONSTRAINT [fkNOTAFISCAL_USUARIO2] FOREIGN KEY([cdUsuarioCancelamento])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[NOTAFISCAL] CHECK CONSTRAINT [fkNOTAFISCAL_USUARIO2]
GO
/****** Object:  ForeignKey [fkNOTAFISCALHOMOLOGACAO_PESSOA]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[NOTAFISCALHOMOLOGACAO]  WITH CHECK ADD  CONSTRAINT [fkNOTAFISCALHOMOLOGACAO_PESSOA] FOREIGN KEY([cdPessoaPrestador])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[NOTAFISCALHOMOLOGACAO] CHECK CONSTRAINT [fkNOTAFISCALHOMOLOGACAO_PESSOA]
GO
/****** Object:  ForeignKey [fkNOTAFISCALIMAGEM_NOTAFISCAL]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[NOTAFISCALIMAGEM]  WITH CHECK ADD  CONSTRAINT [fkNOTAFISCALIMAGEM_NOTAFISCAL] FOREIGN KEY([cdNotaFiscal])
REFERENCES [dbo].[NOTAFISCAL] ([cdNotaFiscal])
GO
ALTER TABLE [dbo].[NOTAFISCALIMAGEM] CHECK CONSTRAINT [fkNOTAFISCALIMAGEM_NOTAFISCAL]
GO
/****** Object:  ForeignKey [fkNOTAFISCALITEM_ATIVIDADE]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[NOTAFISCALITEM]  WITH CHECK ADD  CONSTRAINT [fkNOTAFISCALITEM_ATIVIDADE] FOREIGN KEY([cdAtividade])
REFERENCES [dbo].[ATIVIDADE] ([cdAtividade])
GO
ALTER TABLE [dbo].[NOTAFISCALITEM] CHECK CONSTRAINT [fkNOTAFISCALITEM_ATIVIDADE]
GO
/****** Object:  ForeignKey [fkNOTAFISCALITEM_NOTAFISCAL]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[NOTAFISCALITEM]  WITH CHECK ADD  CONSTRAINT [fkNOTAFISCALITEM_NOTAFISCAL] FOREIGN KEY([cdNotaFiscal])
REFERENCES [dbo].[NOTAFISCAL] ([cdNotaFiscal])
GO
ALTER TABLE [dbo].[NOTAFISCALITEM] CHECK CONSTRAINT [fkNOTAFISCALITEM_NOTAFISCAL]
GO
/****** Object:  ForeignKey [fkOCORRENCIACONTRIBUINTE_PESSOA]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[OCORRENCIACONTRIBUINTE]  WITH CHECK ADD  CONSTRAINT [fkOCORRENCIACONTRIBUINTE_PESSOA] FOREIGN KEY([cdContribuinte])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[OCORRENCIACONTRIBUINTE] CHECK CONSTRAINT [fkOCORRENCIACONTRIBUINTE_PESSOA]
GO
/****** Object:  ForeignKey [fkOCORRENCIACONTRIBUINTE_USUARIO]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[OCORRENCIACONTRIBUINTE]  WITH CHECK ADD  CONSTRAINT [fkOCORRENCIACONTRIBUINTE_USUARIO] FOREIGN KEY([cdUsuario])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[OCORRENCIACONTRIBUINTE] CHECK CONSTRAINT [fkOCORRENCIACONTRIBUINTE_USUARIO]
GO
/****** Object:  ForeignKey [fkOCORRENCIACONTRIBUINTE_USUARIO1]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[OCORRENCIACONTRIBUINTE]  WITH CHECK ADD  CONSTRAINT [fkOCORRENCIACONTRIBUINTE_USUARIO1] FOREIGN KEY([cdUsuarioAlteracao])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[OCORRENCIACONTRIBUINTE] CHECK CONSTRAINT [fkOCORRENCIACONTRIBUINTE_USUARIO1]
GO
/****** Object:  ForeignKey [fkPAGAMENTO_ATIVIDADE]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[PAGAMENTO]  WITH CHECK ADD  CONSTRAINT [fkPAGAMENTO_ATIVIDADE] FOREIGN KEY([cdAtividade])
REFERENCES [dbo].[ATIVIDADE] ([cdAtividade])
GO
ALTER TABLE [dbo].[PAGAMENTO] CHECK CONSTRAINT [fkPAGAMENTO_ATIVIDADE]
GO
/****** Object:  ForeignKey [fkPAGAMENTO_BANCOS]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[PAGAMENTO]  WITH CHECK ADD  CONSTRAINT [fkPAGAMENTO_BANCOS] FOREIGN KEY([cdBanco])
REFERENCES [dbo].[BANCOS] ([cdBanco])
GO
ALTER TABLE [dbo].[PAGAMENTO] CHECK CONSTRAINT [fkPAGAMENTO_BANCOS]
GO
/****** Object:  ForeignKey [fkPAGAMENTO_CODIGOPAGAMENTO]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[PAGAMENTO]  WITH CHECK ADD  CONSTRAINT [fkPAGAMENTO_CODIGOPAGAMENTO] FOREIGN KEY([cdPagamento])
REFERENCES [dbo].[CODIGOPAGAMENTO] ([cdPagamento])
GO
ALTER TABLE [dbo].[PAGAMENTO] CHECK CONSTRAINT [fkPAGAMENTO_CODIGOPAGAMENTO]
GO
/****** Object:  ForeignKey [fkPAGAMENTO_ENDERECO]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[PAGAMENTO]  WITH CHECK ADD  CONSTRAINT [fkPAGAMENTO_ENDERECO] FOREIGN KEY([cdEndereco])
REFERENCES [dbo].[ENDERECO] ([cdEndereco])
GO
ALTER TABLE [dbo].[PAGAMENTO] CHECK CONSTRAINT [fkPAGAMENTO_ENDERECO]
GO
/****** Object:  ForeignKey [fkPAGAMENTO_PESSOA]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[PAGAMENTO]  WITH CHECK ADD  CONSTRAINT [fkPAGAMENTO_PESSOA] FOREIGN KEY([cdPessoa])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[PAGAMENTO] CHECK CONSTRAINT [fkPAGAMENTO_PESSOA]
GO
/****** Object:  ForeignKey [fkPAGAMENTO_TIPOGUIA]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[PAGAMENTO]  WITH CHECK ADD  CONSTRAINT [fkPAGAMENTO_TIPOGUIA] FOREIGN KEY([cdTipoGuia])
REFERENCES [dbo].[TIPOGUIA] ([cdTipoGuia])
GO
ALTER TABLE [dbo].[PAGAMENTO] CHECK CONSTRAINT [fkPAGAMENTO_TIPOGUIA]
GO
/****** Object:  ForeignKey [fkPAGAMENTO_USUARIO3]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[PAGAMENTO]  WITH CHECK ADD  CONSTRAINT [fkPAGAMENTO_USUARIO3] FOREIGN KEY([cdUsuarioCancelamento])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[PAGAMENTO] CHECK CONSTRAINT [fkPAGAMENTO_USUARIO3]
GO
/****** Object:  ForeignKey [fkPAGAMENTOAGRUCESCO_PAGAMENTO]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[PAGAMENTOAGRUCONTRATOESCOLAR]  WITH CHECK ADD  CONSTRAINT [fkPAGAMENTOAGRUCESCO_PAGAMENTO] FOREIGN KEY([cdPagamento])
REFERENCES [dbo].[PAGAMENTO] ([cdPagamento])
GO
ALTER TABLE [dbo].[PAGAMENTOAGRUCONTRATOESCOLAR] CHECK CONSTRAINT [fkPAGAMENTOAGRUCESCO_PAGAMENTO]
GO
/****** Object:  ForeignKey [fkPAGAMENTOAGRUESC_AGRUCTOESC]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[PAGAMENTOAGRUCONTRATOESCOLAR]  WITH CHECK ADD  CONSTRAINT [fkPAGAMENTOAGRUESC_AGRUCTOESC] FOREIGN KEY([cdAgrupamentoContratoEscolar])
REFERENCES [dbo].[AGRUPAMENTOCONTRATOESCOLAR] ([cdAgrupamentoContratoEscolar])
GO
ALTER TABLE [dbo].[PAGAMENTOAGRUCONTRATOESCOLAR] CHECK CONSTRAINT [fkPAGAMENTOAGRUESC_AGRUCTOESC]
GO
/****** Object:  ForeignKey [fkPAGAMENTODOCUMENTO_DOCUMENTO]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[PAGAMENTODOCUMENTO]  WITH CHECK ADD  CONSTRAINT [fkPAGAMENTODOCUMENTO_DOCUMENTO] FOREIGN KEY([cdDocumento])
REFERENCES [dbo].[DOCUMENTO] ([cdDocumento])
GO
ALTER TABLE [dbo].[PAGAMENTODOCUMENTO] CHECK CONSTRAINT [fkPAGAMENTODOCUMENTO_DOCUMENTO]
GO
/****** Object:  ForeignKey [fkPAGAMENTODOCUMENTO_PAGAMENTO]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[PAGAMENTODOCUMENTO]  WITH CHECK ADD  CONSTRAINT [fkPAGAMENTODOCUMENTO_PAGAMENTO] FOREIGN KEY([cdPagamento])
REFERENCES [dbo].[PAGAMENTO] ([cdPagamento])
GO
ALTER TABLE [dbo].[PAGAMENTODOCUMENTO] CHECK CONSTRAINT [fkPAGAMENTODOCUMENTO_PAGAMENTO]
GO
/****** Object:  ForeignKey [fkPAGDOCRETIFI_DOCRETIFICADO]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[PAGAMENTODOCUMENTORETIFICADO]  WITH CHECK ADD  CONSTRAINT [fkPAGDOCRETIFI_DOCRETIFICADO] FOREIGN KEY([cdDocumentoRetificado])
REFERENCES [dbo].[DOCUMENTORETIFICADO] ([cdDocumentoRetificado])
GO
ALTER TABLE [dbo].[PAGAMENTODOCUMENTORETIFICADO] CHECK CONSTRAINT [fkPAGDOCRETIFI_DOCRETIFICADO]
GO
/****** Object:  ForeignKey [fkPAGDOCRETIFICADO_PAGAMENTO]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[PAGAMENTODOCUMENTORETIFICADO]  WITH CHECK ADD  CONSTRAINT [fkPAGDOCRETIFICADO_PAGAMENTO] FOREIGN KEY([cdPagamento])
REFERENCES [dbo].[PAGAMENTO] ([cdPagamento])
GO
ALTER TABLE [dbo].[PAGAMENTODOCUMENTORETIFICADO] CHECK CONSTRAINT [fkPAGDOCRETIFICADO_PAGAMENTO]
GO
/****** Object:  ForeignKey [fkPAGAMENTOITEMATI_ITEMATI]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[PAGAMENTOITEMATIVIDADE]  WITH CHECK ADD  CONSTRAINT [fkPAGAMENTOITEMATI_ITEMATI] FOREIGN KEY([cdItemAtividade])
REFERENCES [dbo].[ITEMATIVIDADE] ([cdItemAtividade])
GO
ALTER TABLE [dbo].[PAGAMENTOITEMATIVIDADE] CHECK CONSTRAINT [fkPAGAMENTOITEMATI_ITEMATI]
GO
/****** Object:  ForeignKey [fkPAGAMENTOITEMATIVIDADE_PAG]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[PAGAMENTOITEMATIVIDADE]  WITH CHECK ADD  CONSTRAINT [fkPAGAMENTOITEMATIVIDADE_PAG] FOREIGN KEY([cdPagamento])
REFERENCES [dbo].[PAGAMENTO] ([cdPagamento])
GO
ALTER TABLE [dbo].[PAGAMENTOITEMATIVIDADE] CHECK CONSTRAINT [fkPAGAMENTOITEMATIVIDADE_PAG]
GO
/****** Object:  ForeignKey [fkPAGAMENTOLBANCARIO_LANCBANC]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[PAGAMENTOLANCBANCARIO]  WITH CHECK ADD  CONSTRAINT [fkPAGAMENTOLBANCARIO_LANCBANC] FOREIGN KEY([cdLancamentoBancario])
REFERENCES [dbo].[LANCAMENTOBANCARIO] ([cdLancamentoBancario])
GO
ALTER TABLE [dbo].[PAGAMENTOLANCBANCARIO] CHECK CONSTRAINT [fkPAGAMENTOLBANCARIO_LANCBANC]
GO
/****** Object:  ForeignKey [fkPAGAMENTOLBANCARIO_PAGAMENTO]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[PAGAMENTOLANCBANCARIO]  WITH CHECK ADD  CONSTRAINT [fkPAGAMENTOLBANCARIO_PAGAMENTO] FOREIGN KEY([cdPagamento])
REFERENCES [dbo].[PAGAMENTO] ([cdPagamento])
GO
ALTER TABLE [dbo].[PAGAMENTOLANCBANCARIO] CHECK CONSTRAINT [fkPAGAMENTOLBANCARIO_PAGAMENTO]
GO
/****** Object:  ForeignKey [fkPERFILPER_PERFILACESS]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[PERFILPERMISSAO]  WITH CHECK ADD  CONSTRAINT [fkPERFILPER_PERFILACESS] FOREIGN KEY([cdPerfilAcesso])
REFERENCES [dbo].[PERFILACESSO] ([cdPerfilAcesso])
GO
ALTER TABLE [dbo].[PERFILPERMISSAO] CHECK CONSTRAINT [fkPERFILPER_PERFILACESS]
GO
/****** Object:  ForeignKey [fkPERFILPER_PERMISSAOACESS]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[PERFILPERMISSAO]  WITH CHECK ADD  CONSTRAINT [fkPERFILPER_PERMISSAOACESS] FOREIGN KEY([cdPermissaoAcesso])
REFERENCES [dbo].[PERMISSAOACESSO] ([cdPermissaoAcesso])
GO
ALTER TABLE [dbo].[PERFILPERMISSAO] CHECK CONSTRAINT [fkPERFILPER_PERMISSAOACESS]
GO
/****** Object:  ForeignKey [fkPERIODOSEMPAGCONTRIBUINTE_MONPESSOANAOPAGAMENTO]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[PERIODOSEMPAGCONTRIBUINTE]  WITH CHECK ADD  CONSTRAINT [fkPERIODOSEMPAGCONTRIBUINTE_MONPESSOANAOPAGAMENTO] FOREIGN KEY([cdMonPessoaNaoPagamento])
REFERENCES [dbo].[MONPESSOANAOPAGAMENTO] ([cdMonPessoaNaoPagamento])
GO
ALTER TABLE [dbo].[PERIODOSEMPAGCONTRIBUINTE] CHECK CONSTRAINT [fkPERIODOSEMPAGCONTRIBUINTE_MONPESSOANAOPAGAMENTO]
GO
/****** Object:  ForeignKey [fkPERMISSAOACESSO_SEGATI]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[PERMISSAOACESSO]  WITH CHECK ADD  CONSTRAINT [fkPERMISSAOACESSO_SEGATI] FOREIGN KEY([cdSegmentoAtividade])
REFERENCES [dbo].[SEGMENTOATIVIDADE] ([cdSegmentoAtividade])
GO
ALTER TABLE [dbo].[PERMISSAOACESSO] CHECK CONSTRAINT [fkPERMISSAOACESSO_SEGATI]
GO
/****** Object:  ForeignKey [fkPERMISSAOUSUARIONFE_PESSOA]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[PERMISSAOUSUARIONFE]  WITH CHECK ADD  CONSTRAINT [fkPERMISSAOUSUARIONFE_PESSOA] FOREIGN KEY([cdPessoaContribuinte])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[PERMISSAOUSUARIONFE] CHECK CONSTRAINT [fkPERMISSAOUSUARIONFE_PESSOA]
GO
/****** Object:  ForeignKey [fkPERMISSAOUSUARIONFE_USUARIO]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[PERMISSAOUSUARIONFE]  WITH CHECK ADD  CONSTRAINT [fkPERMISSAOUSUARIONFE_USUARIO] FOREIGN KEY([cdUsuario])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[PERMISSAOUSUARIONFE] CHECK CONSTRAINT [fkPERMISSAOUSUARIONFE_USUARIO]
GO
/****** Object:  ForeignKey [fkPESSOA_TIPOCONTRIBUINTE]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[PESSOA]  WITH CHECK ADD  CONSTRAINT [fkPESSOA_TIPOCONTRIBUINTE] FOREIGN KEY([cdTipoContribuinte])
REFERENCES [dbo].[TIPOCONTRIBUINTE] ([cdTipoContribuinte])
GO
ALTER TABLE [dbo].[PESSOA] CHECK CONSTRAINT [fkPESSOA_TIPOCONTRIBUINTE]
GO
/****** Object:  ForeignKey [fkPESSOAATIITEMATI_ITEMATI]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[PESSOAATIITEMATI]  WITH CHECK ADD  CONSTRAINT [fkPESSOAATIITEMATI_ITEMATI] FOREIGN KEY([cdItemAtividade])
REFERENCES [dbo].[ITEMATIVIDADE] ([cdItemAtividade])
GO
ALTER TABLE [dbo].[PESSOAATIITEMATI] CHECK CONSTRAINT [fkPESSOAATIITEMATI_ITEMATI]
GO
/****** Object:  ForeignKey [fkPESSOAATIITEMATI_PESSOAATI]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[PESSOAATIITEMATI]  WITH CHECK ADD  CONSTRAINT [fkPESSOAATIITEMATI_PESSOAATI] FOREIGN KEY([cdPessoaAtividade])
REFERENCES [dbo].[PESSOAATIVIDADE] ([cdPessoaAtividade])
GO
ALTER TABLE [dbo].[PESSOAATIITEMATI] CHECK CONSTRAINT [fkPESSOAATIITEMATI_PESSOAATI]
GO
/****** Object:  ForeignKey [fkPESSOAATI_ATIVIDADE]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[PESSOAATIVIDADE]  WITH CHECK ADD  CONSTRAINT [fkPESSOAATI_ATIVIDADE] FOREIGN KEY([cdAtividade])
REFERENCES [dbo].[ATIVIDADE] ([cdAtividade])
GO
ALTER TABLE [dbo].[PESSOAATIVIDADE] CHECK CONSTRAINT [fkPESSOAATI_ATIVIDADE]
GO
/****** Object:  ForeignKey [fkPESSOAATI_PESSOA]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[PESSOAATIVIDADE]  WITH CHECK ADD  CONSTRAINT [fkPESSOAATI_PESSOA] FOREIGN KEY([cdPessoa])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[PESSOAATIVIDADE] CHECK CONSTRAINT [fkPESSOAATI_PESSOA]
GO
/****** Object:  ForeignKey [fkPESSOAESTRANGEIRA_PESSOA]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[PESSOAESTRANGEIRA]  WITH CHECK ADD  CONSTRAINT [fkPESSOAESTRANGEIRA_PESSOA] FOREIGN KEY([cdPessoa])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[PESSOAESTRANGEIRA] CHECK CONSTRAINT [fkPESSOAESTRANGEIRA_PESSOA]
GO
/****** Object:  ForeignKey [fkPESSOAESTRANGEIRA_PESSOA1]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[PESSOAESTRANGEIRA]  WITH CHECK ADD  CONSTRAINT [fkPESSOAESTRANGEIRA_PESSOA1] FOREIGN KEY([cdPessoaCadastramento])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[PESSOAESTRANGEIRA] CHECK CONSTRAINT [fkPESSOAESTRANGEIRA_PESSOA1]
GO
/****** Object:  ForeignKey [fkPESSOAFISICA_PESSOA]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[PESSOAFISICA]  WITH CHECK ADD  CONSTRAINT [fkPESSOAFISICA_PESSOA] FOREIGN KEY([cdPessoa])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[PESSOAFISICA] CHECK CONSTRAINT [fkPESSOAFISICA_PESSOA]
GO
/****** Object:  ForeignKey [fkPESSOAJURIDICA_PESSOA]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[PESSOAJURIDICA]  WITH CHECK ADD  CONSTRAINT [fkPESSOAJURIDICA_PESSOA] FOREIGN KEY([cdPessoa])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[PESSOAJURIDICA] CHECK CONSTRAINT [fkPESSOAJURIDICA_PESSOA]
GO
/****** Object:  ForeignKey [fkPESSOASIMPLESNACIONAL_PESSOA]    Script Date: 04/02/2013 11:32:20 ******/
ALTER TABLE [dbo].[PESSOASIMPLESNACIONAL]  WITH CHECK ADD  CONSTRAINT [fkPESSOASIMPLESNACIONAL_PESSOA] FOREIGN KEY([cdPessoa])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[PESSOASIMPLESNACIONAL] CHECK CONSTRAINT [fkPESSOASIMPLESNACIONAL_PESSOA]
GO
/****** Object:  ForeignKey [fkPROVIDENCIADENUNCIA_DENUNCIA]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[PROVIDENCIADENUNCIA]  WITH CHECK ADD  CONSTRAINT [fkPROVIDENCIADENUNCIA_DENUNCIA] FOREIGN KEY([cdDenuncia])
REFERENCES [dbo].[DENUNCIA] ([cdDenuncia])
GO
ALTER TABLE [dbo].[PROVIDENCIADENUNCIA] CHECK CONSTRAINT [fkPROVIDENCIADENUNCIA_DENUNCIA]
GO
/****** Object:  ForeignKey [fkPROVIDENCIADENUNCIA_USUARIO]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[PROVIDENCIADENUNCIA]  WITH CHECK ADD  CONSTRAINT [fkPROVIDENCIADENUNCIA_USUARIO] FOREIGN KEY([cdUsuarioFiscal])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[PROVIDENCIADENUNCIA] CHECK CONSTRAINT [fkPROVIDENCIADENUNCIA_USUARIO]
GO
/****** Object:  ForeignKey [fkREGIMEESTIMADO_PESSOAATI]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[REGIMEESTIMADO]  WITH CHECK ADD  CONSTRAINT [fkREGIMEESTIMADO_PESSOAATI] FOREIGN KEY([cdPessoaAtividade])
REFERENCES [dbo].[PESSOAATIVIDADE] ([cdPessoaAtividade])
GO
ALTER TABLE [dbo].[REGIMEESTIMADO] CHECK CONSTRAINT [fkREGIMEESTIMADO_PESSOAATI]
GO
/****** Object:  ForeignKey [fkCREQUISICAOAUTORIZACAONFE_ENDERECO]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[REQUISICAOAUTORIZACAONFE]  WITH CHECK ADD  CONSTRAINT [fkCREQUISICAOAUTORIZACAONFE_ENDERECO] FOREIGN KEY([cdEnderecoSolicitante])
REFERENCES [dbo].[ENDERECO] ([cdEndereco])
GO
ALTER TABLE [dbo].[REQUISICAOAUTORIZACAONFE] CHECK CONSTRAINT [fkCREQUISICAOAUTORIZACAONFE_ENDERECO]
GO
/****** Object:  ForeignKey [fkCREQUISICAOAUTORIZACAONFE_PESSOA]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[REQUISICAOAUTORIZACAONFE]  WITH CHECK ADD  CONSTRAINT [fkCREQUISICAOAUTORIZACAONFE_PESSOA] FOREIGN KEY([cdPessoaSolicitante])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[REQUISICAOAUTORIZACAONFE] CHECK CONSTRAINT [fkCREQUISICAOAUTORIZACAONFE_PESSOA]
GO
/****** Object:  ForeignKey [fkCREQUISICAOAUTORIZACAONFE_USUARIO]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[REQUISICAOAUTORIZACAONFE]  WITH CHECK ADD  CONSTRAINT [fkCREQUISICAOAUTORIZACAONFE_USUARIO] FOREIGN KEY([cdUsuarioSituacao])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[REQUISICAOAUTORIZACAONFE] CHECK CONSTRAINT [fkCREQUISICAOAUTORIZACAONFE_USUARIO]
GO
/****** Object:  ForeignKey [fkCREQUISICAOAUTORIZACAONFE_USUARIO2]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[REQUISICAOAUTORIZACAONFE]  WITH CHECK ADD  CONSTRAINT [fkCREQUISICAOAUTORIZACAONFE_USUARIO2] FOREIGN KEY([cdUsuarioSolicitante])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[REQUISICAOAUTORIZACAONFE] CHECK CONSTRAINT [fkCREQUISICAOAUTORIZACAONFE_USUARIO2]
GO
/****** Object:  ForeignKey [fkREQUISICAOSERIENOTAFISCAL_REQUISICAOAUTORIZACAONFE]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[REQUISICAOSERIENOTAFISCAL]  WITH CHECK ADD  CONSTRAINT [fkREQUISICAOSERIENOTAFISCAL_REQUISICAOAUTORIZACAONFE] FOREIGN KEY([cdRequisicaoAutorizacaoNfe])
REFERENCES [dbo].[REQUISICAOAUTORIZACAONFE] ([cdRequisicaoAutorizacaoNfe])
GO
ALTER TABLE [dbo].[REQUISICAOSERIENOTAFISCAL] CHECK CONSTRAINT [fkREQUISICAOSERIENOTAFISCAL_REQUISICAOAUTORIZACAONFE]
GO
/****** Object:  ForeignKey [fkREQUISICAOSERIENOTAFISCAL_SERIENOTAFISCAL]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[REQUISICAOSERIENOTAFISCAL]  WITH CHECK ADD  CONSTRAINT [fkREQUISICAOSERIENOTAFISCAL_SERIENOTAFISCAL] FOREIGN KEY([cdSerieNotaFiscal])
REFERENCES [dbo].[SERIENOTAFISCAL] ([cdSerieNotaFiscal])
GO
ALTER TABLE [dbo].[REQUISICAOSERIENOTAFISCAL] CHECK CONSTRAINT [fkREQUISICAOSERIENOTAFISCAL_SERIENOTAFISCAL]
GO
/****** Object:  ForeignKey [fkREQUISICAOSERIENOTAFISCALATIVIDADE_ATIVIDADE]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[REQUISICAOSERIENOTAFISCALATIVIDADE]  WITH CHECK ADD  CONSTRAINT [fkREQUISICAOSERIENOTAFISCALATIVIDADE_ATIVIDADE] FOREIGN KEY([cdAtividade])
REFERENCES [dbo].[ATIVIDADE] ([cdAtividade])
GO
ALTER TABLE [dbo].[REQUISICAOSERIENOTAFISCALATIVIDADE] CHECK CONSTRAINT [fkREQUISICAOSERIENOTAFISCALATIVIDADE_ATIVIDADE]
GO
/****** Object:  ForeignKey [fkREQUISICAOSERIENOTAFISCALATIVIDADE_REQUISICAOSERIENOTAFISCAL]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[REQUISICAOSERIENOTAFISCALATIVIDADE]  WITH CHECK ADD  CONSTRAINT [fkREQUISICAOSERIENOTAFISCALATIVIDADE_REQUISICAOSERIENOTAFISCAL] FOREIGN KEY([cdRequisicaoSerieNotaFiscal])
REFERENCES [dbo].[REQUISICAOSERIENOTAFISCAL] ([cdRequisicaoSerieNotaFiscal])
GO
ALTER TABLE [dbo].[REQUISICAOSERIENOTAFISCALATIVIDADE] CHECK CONSTRAINT [fkREQUISICAOSERIENOTAFISCALATIVIDADE_REQUISICAOSERIENOTAFISCAL]
GO
/****** Object:  ForeignKey [fkRPSAUTORIZACAOFORAPRAZO_PESSOA]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[RPSAUTORIZACAOFORAPRAZO]  WITH NOCHECK ADD  CONSTRAINT [fkRPSAUTORIZACAOFORAPRAZO_PESSOA] FOREIGN KEY([cdPessoaContribuinte])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[RPSAUTORIZACAOFORAPRAZO] CHECK CONSTRAINT [fkRPSAUTORIZACAOFORAPRAZO_PESSOA]
GO
/****** Object:  ForeignKey [fkRPSAUTORIZACAOFORAPRAZO_PESSOA2]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[RPSAUTORIZACAOFORAPRAZO]  WITH NOCHECK ADD  CONSTRAINT [fkRPSAUTORIZACAOFORAPRAZO_PESSOA2] FOREIGN KEY([cdPessoaFiscal])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[RPSAUTORIZACAOFORAPRAZO] CHECK CONSTRAINT [fkRPSAUTORIZACAOFORAPRAZO_PESSOA2]
GO
/****** Object:  ForeignKey [fkRPSAUTORIZACAOFORAPRAZO_USUARIO]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[RPSAUTORIZACAOFORAPRAZO]  WITH NOCHECK ADD  CONSTRAINT [fkRPSAUTORIZACAOFORAPRAZO_USUARIO] FOREIGN KEY([cdUsuarioFiscal])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[RPSAUTORIZACAOFORAPRAZO] CHECK CONSTRAINT [fkRPSAUTORIZACAOFORAPRAZO_USUARIO]
GO
/****** Object:  ForeignKey [fkRPSINCONSISTENCIA_RPSMENSAGEMINCONSISTENCIA]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[RPSINCONSISTENCIA]  WITH CHECK ADD  CONSTRAINT [fkRPSINCONSISTENCIA_RPSMENSAGEMINCONSISTENCIA] FOREIGN KEY([cdRPSMensagemInconsistencia])
REFERENCES [dbo].[RPSMENSAGEMINCONSISTENCIA] ([cdRPSMensagemInconsistencia])
GO
ALTER TABLE [dbo].[RPSINCONSISTENCIA] CHECK CONSTRAINT [fkRPSINCONSISTENCIA_RPSMENSAGEMINCONSISTENCIA]
GO
/****** Object:  ForeignKey [fkRPSINCONSISTENCIA_RPSTRANSMISSAO]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[RPSINCONSISTENCIA]  WITH CHECK ADD  CONSTRAINT [fkRPSINCONSISTENCIA_RPSTRANSMISSAO] FOREIGN KEY([cdRpsTransmissao])
REFERENCES [dbo].[RPSTRANSMISSAO] ([cdRPSTransmissao])
GO
ALTER TABLE [dbo].[RPSINCONSISTENCIA] CHECK CONSTRAINT [fkRPSINCONSISTENCIA_RPSTRANSMISSAO]
GO
/****** Object:  ForeignKey [fkRPSINCONSISTENCIA_RPSTRANSMISSAOITEM]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[RPSINCONSISTENCIA]  WITH CHECK ADD  CONSTRAINT [fkRPSINCONSISTENCIA_RPSTRANSMISSAOITEM] FOREIGN KEY([cdRPSTransmissaoItem])
REFERENCES [dbo].[RPSTRANSMISSAOITEM] ([cdRPSTransmissaoItem])
GO
ALTER TABLE [dbo].[RPSINCONSISTENCIA] CHECK CONSTRAINT [fkRPSINCONSISTENCIA_RPSTRANSMISSAOITEM]
GO
/****** Object:  ForeignKey [fkRPSRECIBO_RPSTRANSMISSAOITEM]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[RPSRECIBO]  WITH NOCHECK ADD  CONSTRAINT [fkRPSRECIBO_RPSTRANSMISSAOITEM] FOREIGN KEY([cdRpsTransmissaoItem])
REFERENCES [dbo].[RPSTRANSMISSAOITEM] ([cdRPSTransmissaoItem])
GO
ALTER TABLE [dbo].[RPSRECIBO] CHECK CONSTRAINT [fkRPSRECIBO_RPSTRANSMISSAOITEM]
GO
/****** Object:  ForeignKey [fkRPSTRANSMISSAO_PESSOA]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[RPSTRANSMISSAO]  WITH CHECK ADD  CONSTRAINT [fkRPSTRANSMISSAO_PESSOA] FOREIGN KEY([cdPessoaPrestador])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[RPSTRANSMISSAO] CHECK CONSTRAINT [fkRPSTRANSMISSAO_PESSOA]
GO
/****** Object:  ForeignKey [fkRPSTRANSMISSAO_USUARIO]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[RPSTRANSMISSAO]  WITH CHECK ADD  CONSTRAINT [fkRPSTRANSMISSAO_USUARIO] FOREIGN KEY([cdUsuarioTransmissor])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[RPSTRANSMISSAO] CHECK CONSTRAINT [fkRPSTRANSMISSAO_USUARIO]
GO
/****** Object:  ForeignKey [fkRPSTRANSMISSAOITEM_RPSTRANSMISSAO]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[RPSTRANSMISSAOITEM]  WITH CHECK ADD  CONSTRAINT [fkRPSTRANSMISSAOITEM_RPSTRANSMISSAO] FOREIGN KEY([cdRPSTransmissao])
REFERENCES [dbo].[RPSTRANSMISSAO] ([cdRPSTransmissao])
GO
ALTER TABLE [dbo].[RPSTRANSMISSAOITEM] CHECK CONSTRAINT [fkRPSTRANSMISSAOITEM_RPSTRANSMISSAO]
GO
/****** Object:  ForeignKey [fkSOCIOPESSOAJURIDICA_INSCRICAOMUNICIPAL]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[SOCIOPESSOAJURIDICA]  WITH CHECK ADD  CONSTRAINT [fkSOCIOPESSOAJURIDICA_INSCRICAOMUNICIPAL] FOREIGN KEY([cdInscricaoMunicipal])
REFERENCES [dbo].[INSCRICAOMUNICIPAL] ([cdInscricaoMunicipal])
GO
ALTER TABLE [dbo].[SOCIOPESSOAJURIDICA] CHECK CONSTRAINT [fkSOCIOPESSOAJURIDICA_INSCRICAOMUNICIPAL]
GO
/****** Object:  ForeignKey [fkSOCIOPESSOAJURIDICAITEM_INSCRICAOMUNICIPAL]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[SOCIOPESSOAJURIDICAITEM]  WITH CHECK ADD  CONSTRAINT [fkSOCIOPESSOAJURIDICAITEM_INSCRICAOMUNICIPAL] FOREIGN KEY([cdInscricaoMunicipal])
REFERENCES [dbo].[INSCRICAOMUNICIPAL] ([cdInscricaoMunicipal])
GO
ALTER TABLE [dbo].[SOCIOPESSOAJURIDICAITEM] CHECK CONSTRAINT [fkSOCIOPESSOAJURIDICAITEM_INSCRICAOMUNICIPAL]
GO
/****** Object:  ForeignKey [fkTIPOCONTRI_PERFILACESSO]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[TIPOCONTRIBUINTE]  WITH CHECK ADD  CONSTRAINT [fkTIPOCONTRI_PERFILACESSO] FOREIGN KEY([cdPerfilAcesso])
REFERENCES [dbo].[PERFILACESSO] ([cdPerfilAcesso])
GO
ALTER TABLE [dbo].[TIPOCONTRIBUINTE] CHECK CONSTRAINT [fkTIPOCONTRI_PERFILACESSO]
GO
/****** Object:  ForeignKey [fkTOMADORPREFERENCIAL_PESSOA]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[TOMADORPREFERENCIAL]  WITH CHECK ADD  CONSTRAINT [fkTOMADORPREFERENCIAL_PESSOA] FOREIGN KEY([cdPessoaTomador])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[TOMADORPREFERENCIAL] CHECK CONSTRAINT [fkTOMADORPREFERENCIAL_PESSOA]
GO
/****** Object:  ForeignKey [fkTOMADORPREFERENCIAL_PESSOA2]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[TOMADORPREFERENCIAL]  WITH CHECK ADD  CONSTRAINT [fkTOMADORPREFERENCIAL_PESSOA2] FOREIGN KEY([cdPessoaPrestador])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[TOMADORPREFERENCIAL] CHECK CONSTRAINT [fkTOMADORPREFERENCIAL_PESSOA2]
GO
/****** Object:  ForeignKey [fkTRANSACAO_TABELAAUDITORIA]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[TRANSACAO]  WITH CHECK ADD  CONSTRAINT [fkTRANSACAO_TABELAAUDITORIA] FOREIGN KEY([cdTabelaAuditoria])
REFERENCES [dbo].[TABELAAUDITORIA] ([cdTabelaAuditoria])
GO
ALTER TABLE [dbo].[TRANSACAO] CHECK CONSTRAINT [fkTRANSACAO_TABELAAUDITORIA]
GO
/****** Object:  ForeignKey [fkUSUARIO_PERFILACESSO]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[USUARIO]  WITH CHECK ADD  CONSTRAINT [fkUSUARIO_PERFILACESSO] FOREIGN KEY([cdPerfilAcesso])
REFERENCES [dbo].[PERFILACESSO] ([cdPerfilAcesso])
GO
ALTER TABLE [dbo].[USUARIO] CHECK CONSTRAINT [fkUSUARIO_PERFILACESSO]
GO
/****** Object:  ForeignKey [fkUSUARIOAUTORIZADORELEASE_USUARIO]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[USUARIOAUTORIZADORELEASE]  WITH CHECK ADD  CONSTRAINT [fkUSUARIOAUTORIZADORELEASE_USUARIO] FOREIGN KEY([cdUsuario])
REFERENCES [dbo].[USUARIO] ([cdUsuario])
GO
ALTER TABLE [dbo].[USUARIOAUTORIZADORELEASE] CHECK CONSTRAINT [fkUSUARIOAUTORIZADORELEASE_USUARIO]
GO
/****** Object:  ForeignKey [fkVIGENCIAALIQUOTAATI_ATI]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[VIGENCIAALIQUOTAATI]  WITH CHECK ADD  CONSTRAINT [fkVIGENCIAALIQUOTAATI_ATI] FOREIGN KEY([cdAliquota])
REFERENCES [dbo].[ALIQUOTA] ([cdAliquota])
GO
ALTER TABLE [dbo].[VIGENCIAALIQUOTAATI] CHECK CONSTRAINT [fkVIGENCIAALIQUOTAATI_ATI]
GO
/****** Object:  ForeignKey [fkVIGENCIAATI_ATIVIDADE]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[VIGENCIAALIQUOTAATI]  WITH CHECK ADD  CONSTRAINT [fkVIGENCIAATI_ATIVIDADE] FOREIGN KEY([cdAtividade])
REFERENCES [dbo].[ATIVIDADE] ([cdAtividade])
GO
ALTER TABLE [dbo].[VIGENCIAALIQUOTAATI] CHECK CONSTRAINT [fkVIGENCIAATI_ATIVIDADE]
GO
/****** Object:  ForeignKey [fkVIGENCIAALIQUOTAITEMATI_ATI]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[VIGENCIAALIQUOTAITEMATI]  WITH CHECK ADD  CONSTRAINT [fkVIGENCIAALIQUOTAITEMATI_ATI] FOREIGN KEY([cdAliquota])
REFERENCES [dbo].[ALIQUOTA] ([cdAliquota])
GO
ALTER TABLE [dbo].[VIGENCIAALIQUOTAITEMATI] CHECK CONSTRAINT [fkVIGENCIAALIQUOTAITEMATI_ATI]
GO
/****** Object:  ForeignKey [fkVIGENCIAITEMATI_ATIVIDADE]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[VIGENCIAALIQUOTAITEMATI]  WITH CHECK ADD  CONSTRAINT [fkVIGENCIAITEMATI_ATIVIDADE] FOREIGN KEY([cdAtividade])
REFERENCES [dbo].[ATIVIDADE] ([cdAtividade])
GO
ALTER TABLE [dbo].[VIGENCIAALIQUOTAITEMATI] CHECK CONSTRAINT [fkVIGENCIAITEMATI_ATIVIDADE]
GO
/****** Object:  ForeignKey [fkVIGENCIITEMATI_ITEMATI]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[VIGENCIAALIQUOTAITEMATI]  WITH CHECK ADD  CONSTRAINT [fkVIGENCIITEMATI_ITEMATI] FOREIGN KEY([cdItemAtividade])
REFERENCES [dbo].[ITEMATIVIDADE] ([cdItemAtividade])
GO
ALTER TABLE [dbo].[VIGENCIAALIQUOTAITEMATI] CHECK CONSTRAINT [fkVIGENCIITEMATI_ITEMATI]
GO
/****** Object:  ForeignKey [fkVINCULOCONTACONTRI_CONTADOR]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[VINCULOCONTADORCONTRIBUINTE]  WITH CHECK ADD  CONSTRAINT [fkVINCULOCONTACONTRI_CONTADOR] FOREIGN KEY([cdPessoaContador])
REFERENCES [dbo].[CONTADOR] ([cdPessoa])
GO
ALTER TABLE [dbo].[VINCULOCONTADORCONTRIBUINTE] CHECK CONSTRAINT [fkVINCULOCONTACONTRI_CONTADOR]
GO
/****** Object:  ForeignKey [fkVINCULOCONTACONTRI_PESSOA]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[VINCULOCONTADORCONTRIBUINTE]  WITH CHECK ADD  CONSTRAINT [fkVINCULOCONTACONTRI_PESSOA] FOREIGN KEY([cdPessoa])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[VINCULOCONTADORCONTRIBUINTE] CHECK CONSTRAINT [fkVINCULOCONTACONTRI_PESSOA]
GO
/****** Object:  ForeignKey [fkVINCULOCONTADORCONTRI_PESSOA]    Script Date: 04/02/2013 11:32:21 ******/
ALTER TABLE [dbo].[VINCULOCONTADORCONTRIBUINTE]  WITH CHECK ADD  CONSTRAINT [fkVINCULOCONTADORCONTRI_PESSOA] FOREIGN KEY([cdPessoaContador])
REFERENCES [dbo].[PESSOA] ([cdPessoa])
GO
ALTER TABLE [dbo].[VINCULOCONTADORCONTRIBUINTE] CHECK CONSTRAINT [fkVINCULOCONTADORCONTRI_PESSOA]
GO