/*************************
	CREATE INDEX
**************************/

-- Primeiro cria os Indices Clustered - PKs
ALTER TABLE [dbo].[DOCUMENTONOTAFISCAL] ADD  CONSTRAINT [pkDOCUMENTONOTAFISCAL] PRIMARY KEY CLUSTERED 
(
	[cdDocumentoNotaFiscal] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PAGAMENTODOCUMENTO] ADD  CONSTRAINT [pkPAGAMENTODOCUMENTO] PRIMARY KEY CLUSTERED 
(
	[cdPagamentoDocumento] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

ALTER TABLE [dbo].[NOTAFISCALITEM] ADD  CONSTRAINT [pkNOTAFISCALITEM] PRIMARY KEY CLUSTERED 
(
	[cdNotaFiscalIem] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RPSTRANSMISSAOITEM] ADD  CONSTRAINT [pkRPSTRANSMISSAOITEM] PRIMARY KEY CLUSTERED 
(
	[cdRPSTransmissaoItem] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = OFF) ON [PRIMARY]
GO

ALTER TABLE [dbo].[NOTAFISCAL] ADD  CONSTRAINT [pkNOTAFISCAL] PRIMARY KEY CLUSTERED 
(
	[cdNotaFiscal] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

ALTER TABLE [dbo].[DOCUMENTO] ADD  CONSTRAINT [pkDOCUMENTO] PRIMARY KEY CLUSTERED 
(
	[cdDocumento] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO



-- Criando os index NonClustered
CREATE UNIQUE NONCLUSTERED INDEX [ixDocumentoNotaFiscal02] ON [dbo].[DOCUMENTONOTAFISCAL]
(
	[cdDocumento] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ixDocumentoNotaFiscal03] ON [dbo].[DOCUMENTONOTAFISCAL]
(
	[cdNotafiscal] ASC,
	[cdDocumento] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ixPagamentoDocumento01] ON [dbo].[PAGAMENTODOCUMENTO]
(
	[cdDocumento] ASC,
	[inCancelado] ASC
)
INCLUDE ( 	[cdPagamento]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ixPagamentoDocumento02] ON [dbo].[PAGAMENTODOCUMENTO]
(
	[cdPagamento] ASC,
	[inCancelado] ASC
)
INCLUDE ( 	[cdDocumento]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ixNotaFiscalItem01] ON [dbo].[NOTAFISCALITEM]
(
	[cdNotaFiscal] ASC
)
INCLUDE ( 	[cdAtividade],
	[vlAliquota],
	[vlReceita],
	[vlIss],
	[inIssTomador],
	[vlDeducao]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = OFF, FILLFACTOR = 100) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ixRpsTransmissaoItem01] ON [dbo].[RPSTRANSMISSAOITEM]
(
	[cdRPSTransmissao] ASC
)
INCLUDE ( 	[dtRecibo],
	[inSituacaoRecibo],
	[vlRecibo],
	[inSubstTrib],
	[dcAutenticadorRecibo],
	[dcServico],
	[vlDeducao],
	[nrRecibo]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ixNotaFiscal01] ON [dbo].[NOTAFISCAL]
(
	[nrRecibo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ixNotaFiscal02] ON [dbo].[NOTAFISCAL]
(
	[cdRpsTransmissaoItem] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


CREATE UNIQUE NONCLUSTERED INDEX [ixNotaFiscal03] ON [dbo].[NOTAFISCAL]
(
	[nrNotaFiscal] ASC,
	[cdSerieNotaFiscal] ASC,
	[cdPessoaPrestador] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 70) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ixNotaFiscal04] ON [dbo].[NOTAFISCAL]
(
	[dtCancelamento] ASC,
	[cdPessoaTomador] ASC
)
INCLUDE ( 	[cdNotaFiscal],
	[dtEmissao],
	[cdPessoaPrestador],
	[vlNotaFiscal],
	[nrNotaFiscal],
	[cdSerieNotaFiscal],
	[nrRecibo],
	[dtRecibo]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ixNotaFiscal06] ON [dbo].[NOTAFISCAL]
(
	[cdPessoaPrestador] ASC,
	[cdNotaFiscal] ASC
)
INCLUDE ( 	[dtEmissao],
	[dtCancelamento],
	[cdPessoaTomador],
	[dcInfoAdicional],
	[vlNotaFiscal],
	[cdUsuarioContribuinte],
	[nrNotaFiscal],
	[cdSerieNotaFiscal],
	[dcAutenticador],
	[inIntegradoIss],
	[dcMotivoCancelamento],
	[cdUsuarioCancelamento],
	[dcEmailTomador],
	[nrRecibo],
	[dcAutenticadorRecibo],
	[dtRecibo]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ixDocumento01] ON [dbo].[DOCUMENTO]
(
	[nrDocumento] ASC,
	[cdPessoaPrestador] ASC,
	[cdPessoaTomador] ASC,
	[cdDocumento] ASC
)
INCLUDE ( 	[nrTipoDeclaracao]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ixDocumento02] ON [dbo].[DOCUMENTO]
(
	[nrExercicio] ASC,
	[nrMes] ASC,
	[nrTipoDeclaracao] ASC,
	[inSituacaoInconsistencia] ASC,
	[cdPessoaPrestador] ASC,
	[cdPessoaTomador] ASC,
	[inTeste] ASC
)
INCLUDE ( 	[cdDocumento],
	[vlIss],
	[vlReceita],
	[dtEmissao]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ixDocumento03] ON [dbo].[DOCUMENTO]
(
	[cdPessoaPrestador] ASC,
	[nrTipoDeclaracao] ASC,
	[cdPessoaTomador] ASC,
	[inTeste] ASC,
	[cdDocumento] ASC,
	[cdSerieNotaFiscal] ASC,
	[cdImportacaoLancamentoItens] ASC
)
INCLUDE ( 	[dcSerieNotaFiscal],
	[dtEmissao],
	[vlReceita],
	[nrDocumento],
	[vlIss],
	[nrMes],
	[vlAliquota],
	[nrExercicio],
	[inGeracaoPagamento],
	[inSubstituicaoTributaria],
	[cdAtividade],
	[cdItemAtividade],
	[cdTipoDocumento]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ixDocumento04] ON [dbo].[DOCUMENTO]
(
	[cdPessoaTomador] ASC,
	[cdPessoaPrestador] ASC,
	[inTeste] ASC,
	[nrTipoDeclaracao] ASC,
	[cdDocumento] ASC,
	[cdSerieNotaFiscal] ASC,
	[cdImportacaoLancamentoItens] ASC
)
INCLUDE ( 	[dcSerieNotaFiscal],
	[nrDocumento],
	[vlReceita],
	[dtEmissao]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ixDocumento05] ON [dbo].[DOCUMENTO]
(
	[nrMes] ASC,
	[nrExercicio] ASC,
	[cdPessoaPrestador] ASC
)
INCLUDE ( 	[vlIss],
	[vlReceita],
	[inSubstituicaoTributaria],
	[nrTipoDeclaracao]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
GO