/****************************************
				DROP INDEX
*****************************************/
DROP INDEX [ixNotaFiscalItem01] ON [dbo].[NOTAFISCALITEM]
GO

ALTER TABLE [dbo].[NOTAFISCALITEM] DROP CONSTRAINT [pkNOTAFISCALITEM]
GO

DROP INDEX [ixDocumentoNotaFiscal02] ON [dbo].[DOCUMENTONOTAFISCAL]
GO

DROP INDEX [ixDocumentoNotaFiscal03] ON [dbo].[DOCUMENTONOTAFISCAL]
GO

ALTER TABLE [dbo].[DOCUMENTONOTAFISCAL] DROP CONSTRAINT [pkDOCUMENTONOTAFISCAL]
GO

ALTER TABLE [dbo].[DOCUMENTO] DROP CONSTRAINT [pkDOCUMENTO]
GO

DROP INDEX [ixDocumento01] ON [dbo].[DOCUMENTO]
GO

DROP INDEX [ixDocumento02] ON [dbo].[DOCUMENTO]
GO

DROP INDEX [ixDocumento03] ON [dbo].[DOCUMENTO]
GO

DROP INDEX [ixDocumento04] ON [dbo].[DOCUMENTO]
GO

DROP INDEX [ixDocumento05] ON [dbo].[DOCUMENTO]
GO

ALTER TABLE [dbo].[NOTAFISCAL] DROP CONSTRAINT [pkNOTAFISCAL]
GO

DROP INDEX [ixNotaFiscal01] ON [dbo].[NOTAFISCAL]
GO

DROP INDEX [ixNotaFiscal02] ON [dbo].[NOTAFISCAL]
GO

DROP INDEX [ixNotaFiscal03] ON [dbo].[NOTAFISCAL]
GO

DROP INDEX [ixNotaFiscal04] ON [dbo].[NOTAFISCAL]
GO

DROP INDEX [ixNotaFiscal05] ON [dbo].[NOTAFISCAL]
GO

DROP INDEX [ixRpsTransmissaoItem01] ON [dbo].[RPSTRANSMISSAOITEM]
GO

ALTER TABLE [dbo].[RPSTRANSMISSAOITEM] DROP CONSTRAINT [pkRPSTRANSMISSAOITEM]
GO

ALTER TABLE [dbo].[PAGAMENTODOCUMENTO] DROP CONSTRAINT [pkPAGAMENTODOCUMENTO]
GO

DROP INDEX [ixPagamentoDocumento02] ON [dbo].[PAGAMENTODOCUMENTO]
GO

DROP INDEX [ixPagamentoDocumento01] ON [dbo].[PAGAMENTODOCUMENTO]
GO